### PR TITLE
Jonmv/faster query profile compilation

### PR DESCRIPTION
**Pull request by jonmv**
@bratseth please review. 

More to come, but this is a factor of more than π, so worth a merge imo.

### CODE REVIEW

**Comment by bratseth** [comment]
Truly great stuff!
The last commit fails on 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project container-search: Compilation failure: Compilation failure: 
[ERROR] /source/container-search/src/main/java/com/yahoo/search/query/profile/QueryProfileCompiler.java:[254,24] cannot find symbol
[ERROR]   symbol:   class Deque
[ERROR]   location: class com.yahoo.search.query.profile.QueryProfileCompiler.PathTree.Node
[ERROR] /source/container-search/src/main/java/com/yahoo/search/query/profile/QueryProfileCompiler.java:[57,57] incompatible types: com.yahoo.search.query.profile.DimensionBinding cannot be converted to com.yahoo.search.query.profile.compiled.Binding
[ERROR] /source/container-search/src/main/java/com/yahoo/search/query/profile/QueryProfileCompiler.java:[59,69] incompatible types: com.yahoo.search.query.profile.DimensionBinding cannot be converted to com.yahoo.search.query.profile.compiled.Binding
[ERROR] /source/container-search/src/main/java/com/yahoo/search/query/profile/QueryProfileCompiler.java:[61,65] incompatible types: com.yahoo.search.query.profile.DimensionBinding cannot be converted to com.yahoo.search.query.profile.compiled.Binding
[ERROR] /source/container-search/src/main/java/com/yahoo/search/query/profile/QueryProfileCompiler.java:[63,60] incompatible types: com.yahoo.search.query.profile.DimensionBinding cannot be converted to com.yahoo.search.query.profile.compiled.Binding
[ERROR] -> [Help 1]
[ERROR] 
```

**Comment by jonmv** [comment]
Argh, need to stop editing commit diffs.

**Comment by jonmv** [comment]
Collecting variants took 375s before, and is down to 20s. The rest took 75s and still does. Will try to work a little on this as well.

**Comment by jonmv** [comment]
Cache more names, that is ...

**Comment by jonmv** [comment]
450s to 30s now. PTAL. May still do some minor clean-up. It's also still possible to reduce the number of duplicate variants considered, but it's getting complicated now :)

**Comment by bratseth** [comment]
Merging! :-)

**Pull request merged**
