### PR TITLE
let LocationPreFilter contribute to global filter

### PR DESCRIPTION
**Pull request by arnej27959**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

@baldersheim please review
@jobergum @havardpe FYI

### CODE REVIEW

**Comment by arnej27959** [comment]
note: this needs testing to see if it helps or hurts performance.

**Review by baldersheim — APPROVED** [review]
This might be required too, but in #22075 there is only a LocationPostFilterBlueprint which will never allow term wise eval.
I assume https://github.com/vespa-engine/vespa/blob/master/searchlib/src/vespa/searchlib/attribute/attribute_blueprint_factory.cpp#L333 is were it fails out. And that will be the case if hit estimates are larger than 10%

**Comment by baldersheim** [comment]
@arnej27959 Should we proceed with this one anyway, or should we just close it ?

**Comment by baldersheim** [comment]
@arnej27959 Ping ref comment above, still valid or close ?

**Review by baldersheim — APPROVED** [review]

**Review by geirst — CHANGES_REQUESTED** [review]
Please add unit test as well: searchlib/src/tests/attribute/searchable/attributeblueprint_test.cpp.

**Comment by aressem** [comment]
@arnej27959 @geirst Integrate or close ?

**Comment by geirst** [comment]
The current behaviour is documented here: https://docs.vespa.ai/en/approximate-nn-hnsw.html#combining-approximate-nearest-neighbor-search-with-filters. We can just close this for now.

**Pull request closed without merging**
