### PR TITLE
Terminate standalone container cleanly on SIGINT/control-C

### PR DESCRIPTION
**Pull request by hakonhall**

### CODE REVIEW

**Comment by hmusum** [comment]
Adding @arnej27959 as reviewer, I suggest he takes a look at this

**Review by arnej27959 — CHANGES_REQUESTED** [review]
while this looks fine, it highlights the fact that we have the same code in two places.  Please also remove the CatchSigTerm class from vespajlib and change usage to new CatchSignals from yolean.

**Review by arnej27959 — APPROVED** [review]
looks good to me, you'll need to make a PR for vespa-yahoo repo updating metrics proxy also, to be merged at the same time as this.

**Comment by hakonhall** [comment]
You should have received that PR already?

**Pull request merged**
