### PR TITLE
Wrap lock and application and use it when persisting data

### PR DESCRIPTION
**Pull request by mpolden**
Replaces #3927

### CODE REVIEW

**Comment by bratseth** [comment]
Great!
A few things:
. I think the lock() method should return a LockedApplication. We don't really ever need the lock on its own. That means LockedApplication should be autocloseable, which is good too (it should also set its own application instance to null when closed).
- I don't think the reader methods should be moved to LockedApplication because then we have to lock to read things. I suggest that LockedApplication has a get() which returns the Application inside it instead.

This is quite large and already much better than it were so if you prefer we can merge (after mergestop left) and work more on it later.

**Comment by bratseth** [comment]
@jonmv fyi

**Comment by bratseth** [comment]
> You'd have to do something like this:
>
> try (LockedApplication app = controller().applications().lock("id")) {
>   LockedApplication updated = app.withProjectId(42);
>   controller().applications().store(updated);
> }
> but that makes it too easy to incorrectly call store(app) in my opinion.

Good point, I didn't think of that. I'm still not sure it isn't the better tradeoff anyway though.
You example reads much better as just

```
try (LockedApplication app = controller().applications().lock("id")) {
  controller().applications().store(app.withProjectId(42));
}
```
That doesn't always work, but using a nested method for more complex cases does.

But now that I think about it I think it may just be totally wrong for LockedApplication to be immutable. 
I suggest merging this and then we can try some things later on.

**Comment by jonmv** [comment]
With @bratseth's comments, this is very much what I thought about initially. 

I also implemented my suggestions with recursive `with`-building and keeping track of changes, so `store` fetches a fresh application and replays the changes on it, and then stores it; this removes the need for explicit locking, as long as you accept concurrent modifications (and still leaves the option to lock, of course). I think it also makes it harder to use the API wrong — however, the recursive `with` stuff got just a tiny bit esoteric, and I still have to come up with a good solution to prevent applying the same changes several times (if `store` is called multiple times with the same application), which is a problem unless all modifications are idempotent — hardly a sound assumption to make. 

So, while I think the solution is interesting, I don't think we should use it ... even though is makes for less code than what we have now ;)

**Comment by jonmv** [comment]
I think the solution in this here PR is a solid improvement; I also think we should establish a pattern of putting all the required `.with`-s in LockedApplication, to make it harder to do something wrong (by passing a stale DeploymentJobs, or whatever, to the fresh LockedApplication). It's not just for convencience.

**Pull request merged**
