### PR TITLE
Add back usePhraseSegmenting() to revert breaking API change MERGEOK

### PR DESCRIPTION
**Pull request by hmusum**

### CODE REVIEW

**Review by andreer — APPROVED** [review]

**Comment by bratseth** [comment]
👍 but we shouldn't really include config models from earlier non-released builds ...

**Comment by hmusum** [comment]
In CD we have to, since there are applications running on those versions

**Comment by bratseth** [comment]
Bu then we can't do clean reverts :disappointed:

**Comment by aressem** [comment]
Restoring CD to the most recent released version in prod before running would solve this (amongst several other things).

**Comment by bratseth** [comment]
Yep. It's just a +1 on that

**Pull request merged**
