### PR TITLE
Turn on reindexing by default

### PR DESCRIPTION
**Pull request by jonmv**
@vekterli please review and merge. @bjorncs FYI.

### CODE REVIEW

**Comment by jonmv** [comment]
Will not cause any actual reindexing unless this is explicitly triggered.

**Comment by baldersheim** [comment]
How do you trigger it explicit ?

**Comment by jonmv** [comment]
By an explicit API call to the config server, or (for hosted application) by submitting an application package which causes the indexing pipeline to change, with the appropriate validation override.

**Comment by jonmv** [comment]
[Documentation](https://docs.vespa.ai/documentation/reindexing)

**Review by vekterli — APPROVED** [review]

**Pull request merged**
