### PR TITLE
CMS is deprecated in JDK 9 and will be removed in a later release

### PR DESCRIPTION
**Pull request by gjoranv**
FYI: @baldersheim

- See http://openjdk.java.net/jeps/291

### CODE REVIEW

**Comment by bjorncs** [comment]
This will make G1 the default GC in Vespa 7. Is that okay @baldersheim  ?

**Review by bjorncs — APPROVED** [review]

**Comment by bjorncs** [comment]
The JEP 291 states that "for some applications CMS is a very good fit and might always outperform G1."

**Review by baldersheim — APPROVED** [review]
Let the future come

**Comment by baldersheim** [comment]
@bratseth This is a setting that we could bring in now. It is not necessary to make 7 switch even bigger.

**Comment by bratseth** [comment]
Do we have any information on the performance of G1 on Java 8 vs. 11?
If ithere isn't much difference it would be better to *not* do this on 7.

**Comment by bratseth** [comment]
... that is, do it now instead.

**Pull request merged**
