### PR TITLE
Jonmv/floating point window size

### PR DESCRIPTION
**Pull request by jonmv**
@baldersheim please review, but do not merge.

### CODE REVIEW

**Comment by jonmv** [comment]
Uh, first two commits should have been one.

**Review by baldersheim — APPROVED** [review]
Looks fine, but I think that @vekterli should weigh in too

**Review by vekterli — COMMENTED** [review]
The inner workings of this algorithm is about as transparent to me as a trying to stare through a plaster wall 😬 Adding some comments to the code base for the hows and whys of these tweaks would be very nice

**Comment by jonmv** [comment]
Yes, working on that, and a thorough unit test/playground.

**Comment by jonmv** [comment]
I have no further, significant changes, though, so may as well merge this now to see how it behaves in real scenarios.

**Pull request merged**
