### PR TITLE
Throw exception if resource-limits is specified

### PR DESCRIPTION
**Pull request by hmusum**
Please review only, cannot be merged until no customers in hosted specify `resource-limits` in services.xml

### CODE REVIEW

**Comment by hmusum** [comment]
@geirst please review only

**Review by geirst — APPROVED** [review]
👍

**Comment by hmusum** [comment]
Have to introduce a feature flag to be able to roll out this now. @geirst please take a look again

**Review by geirst — APPROVED** [review]
👍

**Pull request merged**
