### PR TITLE
Balder/reduce memory footprint for rankprofiles

### PR DESCRIPTION
**Pull request by baldersheim**
@bratseth PR

### CODE REVIEW

**Comment by bratseth** [comment]
Great, just one thing: searchlib/../rankingexpression is a public API, so you should add a 

```
    public final String toString(SerializationContext context, Deque<String> path, CompositeNode parent) {
        return toString(new StringBuilder(), context, path, parent).toString();
    }

```
to ExpressionNode.

**Review by bratseth — CHANGES_REQUESTED** [review]
See PR comment.

**Comment by baldersheim** [comment]
Ah, yes that was my intention after I had fixed the code. Forgotten.

**Comment by baldersheim** [comment]
@bratseth Now it should be ok.

**Review by bratseth — APPROVED** [review]

**Comment by bratseth** [comment]
👍 let's wait for factory to be ok though.

**Pull request merged**
