### PR TITLE
Use gzip by default for payloads > 512b

### PR DESCRIPTION
**Pull request by jonmv**
@bjorncs

### CODE REVIEW

**Review by bjorncs — APPROVED** [review]
Consider making compression a tri-state: default,off,gzip

**Comment by bjorncs** [comment]
FYI @baldersheim

**Comment by baldersheim** [comment]
Agree with default,none,gzip enum. I assume there might soon be zstd too.

**Comment by jonmv** [comment]
Do you want an explicit `default`, which is what the current <no setting> is? Is that needed?

**Comment by jonmv** [comment]
Updating --help in https://github.com/vespa-engine/vespa/pull/25451

**Comment by jonmv** [comment]
`auto`, perhaps?

**Pull request merged**
