### PR TITLE
Pick hosts randomized in RetryingJaxRsStrategy

### PR DESCRIPTION
**Pull request by hakonhall**
This explains the skewed traffic to servers of clients using RetryingJaxRsStrategy.

### CODE REVIEW

**Comment by bratseth** [comment]
I don't think we can merge this until we have changed the deploy API such that activate on an unprepared application will also prepare it, as we currently need affinity between those two calls when happening in close succession. If you would like to do that feel free :-)
Otherwise I hope to get to it soon...ish.

**Comment by hakonhall** [comment]
If the same RetryingJaxRsStrategy instance is used for both calls, we're still guaranteed the same order with this change. Is that good enough? If this is ApplicationController it's stability should be unchanged.

**Comment by hakonhall** [comment]
Actually, I think ApplicationController uses something else than RetryingJaxRsStrategy.

**Comment by bratseth** [comment]
Yes, ApplicationController uses ConfigServerClientImp, but that one is only using  RetryingJaxRsStrategy for some of the calls, and its own retrying implementation for other calls. Entropy ... Anyway prepare and activate is in the second category, so this change is fine.

**Pull request merged**
