### PR TITLE
Move rotation to application

### PR DESCRIPTION
**Pull request by mpolden**
Some things to consider:
* Model no longer allows multiple rotations for same application. I've verified that no application actually has multiple rotations.
* Moving of existing rotation data to application in `ApplicationController` constructor
* A side effect of this change is that deleting an application will free up the rotation. However, the DNS record will remain intact. This may cause problems if a deleted application is recreated and gets assigned a new rotation as the DNS record will point to the old (wrong) one.

A corresponding `services.xml` change needs to merged as well.

This change makes it easier to automatically clean up unused rotations. Just need to remember to clean up DNS records as well.

@tokle @andreer 

FYI @bratseth

### CODE REVIEW

**Review by tokle — APPROVED** [review]
Not too fond on the circular reference RotationRepository<->ApplicationController, but I can't see any better solution. @andreer any objections that we merge this?

**Comment by andreer** [comment]
This looks ok to me. Ideally I'd like to see deletion of applications also delete the CNAME created for the rotation - wouldn't that mean we'd never have to do any cleanup again?

**Comment by mpolden** [comment]
@andreer Of course, but want to do that in a separate PR as I found this change large enough. :-)

**Comment by andreer** [comment]
No argument from me there 👍

**Comment by bratseth** [comment]
Great!

**Pull request merged**
