### PR TITLE
Interns/verification reporting

### PR DESCRIPTION
**Pull request by olaaun**

### CODE REVIEW

**Comment by freva** [comment]
Looks like we could greatly simplify this code if `SpecVerifier` took in `HardwareInfo` (its only like 5 values? cpuCores, mainMemory, diskMemory, ips, fastDisk (bool)). Whatever calls this (Chef|node-admin) already has those values anyway?

**Comment by sgrostad** [comment]
I do not understand what that would simplify. Could you explain what part it will simplify?

**Comment by freva** [comment]
Most of the stuff under `verification/spec/noderepo`. So instead of taking in list of config servers, (or a after this PR, a single config server URL) to make a request against node-repo to get the hardware spec, the hardware spec could be passed in as arguments
`java -cp /path/to/maintainer.jar com.class.name.spec.SpecVerifier --cpucores 3 --memorygb 16 --diskgb 250 --ips 10.0.0.1,1234:5678:9abc::1234,::1 --fastdisk` These args can make the `HardwareInfo` instance and from there everything is the same.

This has the advantage that we wont need to duplicate code to create another node-repo client, and the existing clients already implement things like retries

**Comment by freva** [comment]
(Just leaving this here as a general note for possible future improvement, not specifically related to this PR)

**Comment by smorgrav** [comment]
Let me know when it is ready for review. If the git history/changes looks strange, I suggest resetting and rewriting the history as we talked about on the last PR.

**Comment by smorgrav** [comment]
LGTM

**Pull request merged**
