### PR TITLE
Tweak command documentation and argument validation

### PR DESCRIPTION
**Pull request by mpolden**
@bratseth

### CODE REVIEW

**Review by bratseth — APPROVED** [review]
Nice!

But I wonder how we ended up with such shit songs as examples ...

**Comment by mpolden** [comment]
I didn't even recognize the title. Coldplay?! 😞

**Comment by bratseth** [comment]
Abject failure 😞

**Comment by kkraune** [comment]
haha! when working on https://docs.vespa.ai/en/text-matching-ranking.html I needed some titles for all the use cases described there. I am quite sure songs can be replaced with _objectively_ high-quality ones, feel free (but don't break the documentation) 😎 😎

**Pull request merged**
