### PR TITLE
Revert "Use default value of jdisc.debug.resources."

### PR DESCRIPTION
**Pull request by jonmv**
Reverts vespa-engine/vespa#19303

@bjorncs @baldersheim this turned on debug references for all of CD 😝

### CODE REVIEW

**Review by hakonhall — APPROVED** [review]

**Comment by bjorncs** [comment]
Are you sure it was not because of the related feature flag change?

**Comment by jonmv** [comment]
Hmm, this wasn't _quite_ right, but the logservers were set to debugging mode, and they got so slow everything failed :)

**Comment by bjorncs** [comment]
Yes, the feature flag affected all admin type of clusters. We could not restrict the flag to metricsproxy only.

**Comment by hakonhall** [comment]
Couldn't you fetch with the CLUSTER_ID dimension set to the cluster name, i..e "metrics" for the metrics proxy?

It's a slight contract violation of CLUSTER_ID, as it is supposed to be `com.yahoo.config.provision.ClusterSpec.Id::value`, but as long as the serialized feature flag overrides matches whatever is done in code it should be fine.  We could update the CLUSTER_ID doc about this since the model and service monitor cares more about the cluster name (aka cluster id in service monitor) than the node's cluster spec ID.

Alternatively we could add a CLUSTER_NAME.

**Pull request merged**
