### PR TITLE
Lesters/model eval throw on error

### PR DESCRIPTION
**Pull request by lesters**
@bratseth Please review.

### CODE REVIEW

**Review by bratseth — APPROVED** [review]
What I wanted to achieve was to avoid having logic here to resolve and produce error messages, since we already have it in the model evaluation code (and it produces better messages than this). Anyway, feel free to merge this if you like.

**Comment by lesters** [comment]
I see, I should have explained this a bit better. The reason I removed that comment was that this handler has additional logic than what is handled in the model evaluation code, regarding discovery of models, functions and types. Also, the URL parsing had issues with urls of type "/modelname//" and "modelname//eval" - the double / would reduce to one /.

However, I agree that this should be handled in one place, I'll take another look regarding separating the evaluation and discovery.

**Comment by lesters** [comment]
@bratseth Please take a look at updated code. Most of the logic now is moved out of the handler, and the code in config model does not depend upon this handler now. Better information is given with regards to model discovery. More work is required when we have type information, but this should be good enough for now.

**Review by bratseth — APPROVED** [review]
Great

**Pull request merged**
