### PR TITLE
Make DockerOperations the API against Docker daemon

### PR DESCRIPTION
**Pull request by hakonhall**

### CODE REVIEW

**Review by freva — COMMENTED** [review]
Can't we just add 
```
boolean deleteUnusedDockerImages(List<DockerImage> wantedImages, Duration minImageAgeToDelete);
```
to `DockerOperations` and forward that directly to `Docker`? Right now, we leak `docker-api`s `Image` in `Docker`, and the only other user of `ContainerLite` could make with a method that just returns `List<ContainerName>` of managed containers.

**Comment by hakonhall** [comment]
> Right now, we leak docker-apis Image in Docker

Agree, the whole purpose of docker-api is to avoid leaking docker-java classes... Looks like it is easiest to put the impl back.

> the only other user of ContainerLite could make with a method that just returns List<ContainerName> of managed containers

I don't understand what you mean. The only other usage ends up with just a `count() == 0` on the number of running containers. So instead of returning a List<ContainerLite> the method could return boolean to hide the internals?

On name/ContainerName: listContainersCmd returns names as an array of X, where `X = "/" + name`. I'd prefer to avoid decoding this to a single ContainerName unless necessary.

**Comment by freva** [comment]
> So instead of returning a List the method could return boolean to hide the internals?

Yes, I just want to avoid returning `ContainerLite`. If you move the docker GC back to docker-api, then only user of `ContainerLite` will be the internal code, and it only needs to know if there are any running containers.
IMO, this can be simplified;
1) We don't really care about "all" containers, just the managed ones (i.e. if there is a manually started containers, we don't care about those, restarting docker should be ok).
2) All managed dead containers will be removed, so its fine to just check for number of managed containers (regardless of state).
Two ways of doing that: Have a super specific method that returns `boolean` answering the exact question or have a slightly more general method like listing the running containers. Without creating a new class, the only thing we can return is `ContainerName`.

> On name/ContainerName: listContainersCmd returns names as an array of X, where X = "/" + name. I'd prefer to avoid decoding this to a single ContainerName unless necessary.

Yes, its already handled in `DockerImpl` with this method: https://github.com/vespa-engine/vespa/blob/d5bfe2dcd0d1c5d8b4dd62d52c08cfb29be73f6d/docker-api/src/main/java/com/yahoo/vespa/hosted/dockerapi/DockerImpl.java#L295

We used to have that method before:
https://github.com/vespa-engine/vespa/commit/1178189e38a66e20c89d399f5898848613194066#diff-2f59b663d91b8e046a7b0cc0baeec5c7L341

**Comment by hakonhall** [comment]
PTAL

The PR now contains:
 - exposing deleteUnusedDockerImages from DockerOperations, and
 - adding a new noManagedContainersRunning implemented in Docker

**Review by freva — APPROVED** [review]

**Pull request merged**
