### PR TITLE
Gjoranv/metrics v2 in container 2

### PR DESCRIPTION
**Pull request by gjoranv**
Reapplies #11915 with one additional commit to exclude `httpclient` in container-dev.

### CODE REVIEW

**Review by hmusum — APPROVED** [review]

**Review by hmusum — CHANGES_REQUESTED** [review]
Build fails

**Comment by gjoranv** [comment]
Yes, and there is unfortunately no easy fix. I forgot to mark as do-not-merge. Done now.

**Comment by gjoranv** [comment]
@bjorncs, the best way forward is to have a simple VespaHttpClient that is not based on apache. This application does not have very strict requirements to flexibility or performance. If that is not feasible, you must make the httpclient version in vespa and hosted:tenant-base the same. Now they are different, and they shouldn't be in any case.

**Comment by gjoranv** [comment]
FYI: @oyving

**Comment by gjoranv** [comment]
We decided to upgrade `httpclient` and `httpcore` to the same versions as those used in Vespa. It is currently not feasible to create a VespaHttpClient based on the http client in the Java standard lib.

@olaaun Please review. Build should pass after the modified last commit that adds httpclient on the test classpath of application.

**Review by olaaun — APPROVED** [review]

**Comment by gjoranv** [comment]
@olaaun PTAL. Added a commit to rename 'serviceid' to 'serviceId'

**Review by olaaun — APPROVED** [review]

**Comment by gjoranv** [comment]
Awaiting merge until 7.167 release is tagged, which includes upgrade of apache httpcomponents in hosted Vespa's tenant:base.

**Pull request merged**
