### PR TITLE
Do not depend on on ClusterInfo config as it changes to often and cau…

### PR DESCRIPTION
**Pull request by baldersheim**
…ses a instant clusterwide hickup on any container cluster changes like node retirement.

The corner case it was used for is not worth the cost.

@bratseth PR

### CODE REVIEW

**Comment by baldersheim** [comment]
I will make a component out of the RpcResourcePool first

**Review by bratseth — APPROVED** [review]
Fine, but if something hurts you should generally try to do it more to make it stop.
We might consider warning about this kind of configuration on the config model side, but i agree it's not important.

**Comment by baldersheim** [comment]
Yes, the root cause need to be fixed independently.

**Comment by bjormel** [comment]
That was quick, thanks!

**Comment by baldersheim** [comment]
I always have a few branch lying around, just in case...... :)

**Pull request merged**
