### PR TITLE
Rename controller module Application to Instance

### PR DESCRIPTION
**Pull request by jonmv**
@mpolden please review so we get this out of the world, and avoid conflict overload :)

### CODE REVIEW

**Review by bratseth — APPROVED** [review]
👍 LGTM. Verified you remembered to exclude strings :-)
One of the classes are renamed with git rm/add instead of git mv, but not a big deal.

**Review by mpolden — APPROVED** [review]
A lot of the javadoc that references "application(s)" no longer make sense.

LGTM otherwise.

> One of the classes are renamed with git rm/add instead of git mv, but not a big deal.

I believe Git tracks renames based on similarity in content, not path names. Content is probably not similar enough to be counted as a rename in some of these cases.

**Comment by jonmv** [comment]
I know about the doc, but will take a pass once the new `Application` is in place, so I don't have to edit by hand 3x what I really need :) (Assuming roughly half has to be edited.)

**Comment by mpolden** [comment]
PR title? 🙂

**Pull request closed without merging**
