### PR TITLE
Jvenstad/config subscription

### PR DESCRIPTION
**Pull request by jonmv**
@hmusum please review and merge. Fixes a bug which could cause config to be reloaded too often, but probably nothing serious.

### CODE REVIEW

**Review by hmusum — COMMENTED** [review]
Could you explain the scenario in which it will return too early? I don't see the bug.

**Comment by jonmv** [comment]
Let original timeout be T. If the first sub returns after X, then the time left is set to T-X. If the second sub then returns immediately, the time left is set to (T-X)-X, which is wrong; it should still be just T-X. So the while method may return early. Probably has no or little impact, though.

**Comment by hmusum** [comment]
Ah, I see. Using an Instant for when it needs to be finished and just checking against that would probably be even nicer. I think the code is more readable now, so this is good 👍

**Review by hmusum — APPROVED** [review]

**Comment by jonmv** [comment]
Yes, in hindsight; that’s the usual way. I guess it’s done differently here because of the timeout argument to pass to the subs, but that could have been done that way too.

**Pull request merged**
