### PR TITLE
No need for restricting access to zookeeper in hosted vespa

### PR DESCRIPTION
**Pull request by hmusum**
Access restrictions handled by other means

### CODE REVIEW

**Comment by bratseth** [comment]
Yes, but why remove the double protection?

**Comment by hmusum** [comment]
This came up when discussing replacement of config servers. When changing config servers we cannot today use a CNAME for the config server, since this line in RestrictedServerCnxnFactory:
`            String remoteHost = ((InetSocketAddress)socket.getRemoteAddress()).getHostName();
`

will give the A record and thus not allow access from both the new and the old config server in a transition period.

**Review by bratseth — APPROVED** [review]
Ok then

**Comment by hmusum** [comment]
@freva FYI

**Pull request merged**
