### PR TITLE
Balder/no publicapi needed

### PR DESCRIPTION
**Pull request by baldersheim**
@hmusum or @jonmv PR

### CODE REVIEW

**Comment by jonmv** [comment]
@bratseth any objections?

**Comment by jonmv** [comment]
The only reason I can think of is to remind ourselves that these changes can break the configserver ... which is perhaps a good enough reason?

**Comment by baldersheim** [comment]
But then it should be the same on all packages there, not only 20%.
I agree that catching changes here is good, but won't we catch that in CD ?
And it is not a public api ........

**Comment by bratseth** [comment]
No objections.

**Review by hmusum — APPROVED** [review]

**Pull request merged**
