### PR TITLE
Setup tls for tester app MERGEOK

### PR DESCRIPTION
**Pull request by tokle**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by bjorncs — APPROVED** [review]

**Comment by jonmv** [comment]
This doesn't require the controller to present a client certificate? (It doesn't, but could probably.)

**Comment by tokle** [comment]
should be a drop in replacement for existing 4080

**Comment by bjorncs** [comment]
@jonmv A certificate will be required (unless status.html).

**Comment by jonmv** [comment]
Ok, then requests to `/tester/v1/*` will fail less than a second later :)

**Comment by jonmv** [comment]
The controller currently authenticates by passing an Athenz header. I guess this could be replaced by an Athenz client certificate?

**Comment by bjorncs** [comment]
Let's continue this discussion offline.

**Pull request merged**
