### PR TITLE
ensure we keep flushing peak_qps after a burst of queries

### PR DESCRIPTION
**Pull request by arnej27959**
@bratseth please review and merge
@yngveaasheim FYI

### CODE REVIEW

**Comment by bratseth** [comment]
I don't understand this. 

Each time the there has been any queries in the last period we schedule another writing of the PEAK_QPS_METRIC a second later . why?

Isn't the calculation wrong now because before re-scheduling prevMaxQpsTime is reset but queriesForQps is not?

It looks like the timer will keep scheduling new flushes indefinitely recursively but actually it will not as a side effect of resetting queriesForQps - why so hard?

(Out of scope of this PR, but those field names are terrible and why is queriesForQps a double?)

**Comment by yngveaasheim** [comment]
I believe this is to address VESPA-9900.

**Comment by arnej27959** [comment]
@bratseth please take another look now

**Comment by bratseth** [comment]
Much better! Merging.

**Pull request merged**
