### PR TITLE
Move to Python3 for test parallelization script

### PR DESCRIPTION
**Pull request by vekterli**
@aressem please review. Script was made for ye olde python 2.7
@baldersheim FYI
@toregge FYI, will likely have to add python3 dep for Fedora as well

Require python3 as build dep and during configure step.

### CODE REVIEW

**Review by aressem — APPROVED** [review]

**Comment by aressem** [comment]
Just make sure that we find Python 3 on ylinux6 with this cmake call.

**Review by aressem — APPROVED** [review]

**Comment by aressem** [comment]
@bjorncs also created a PR here to pull python 3 into the image https://github.com/vespa-engine/docker-image-dev/pull/20/files

**Comment by vekterli** [comment]
Have manually verified that Python 3.6 is found on RHEL6 during CMake configure step

**Comment by aressem** [comment]
cppunit-parallelize.py is deleted. Closing the PR.

**Pull request closed without merging**
