### PR TITLE
Put node ID in the ID field

### PR DESCRIPTION
**Pull request by mpolden**
I did not find any important usages of `id`, so let's use it for the node ID,
and eventually remove `openStackId`.

@freva

### CODE REVIEW

**Comment by mpolden** [comment]
Hold merge. Noticed that we should read `id` when adding nodes as well.

**Review by freva — APPROVED** [review]
:1st_place_medal:

**Comment by freva** [comment]
It would be nice if nodes had unique IDs across allocations, then we could get rid of this hack in node-admin: https://github.com/vespa-engine/vespa/blob/master/node-admin/src/main/java/com/yahoo/vespa/hosted/node/admin/nodeadmin/NodeAdminImpl.java#L227

**Comment by mpolden** [comment]
Agree, but that sounds independent of this change.

**Review by freva — APPROVED** [review]

**Pull request merged**
