### PR TITLE
Increase timeout for application lock when deploying

### PR DESCRIPTION
**Pull request by hmusum**

### CODE REVIEW

**Review by baldersheim — APPROVED** [review]
Merge at will.

**Comment by jonmv** [comment]
This also doubles the time other components in the controller may be blocked from doing anything. 

Any objections to separating the deployment locking from the other usages?

**Comment by mpolden** [comment]
Most of the maintainers shouldn't need to hold the lock this long, so separate timeout for deployment would be nice.

**Comment by hmusum** [comment]
@mpolden please take a look

**Review by mpolden — APPROVED** [review]
💯

**Pull request merged**
