### PR TITLE
Replace System and Staging tests with Functional and Upgrade

### PR DESCRIPTION
**Pull request by jonmv**
@freva please review and merge.

### CODE REVIEW

**Review by freva — APPROVED** [review]
The test file suffix should also be updated

What about the internal pipeline, will we at some point rename the `system-test` and `staging-test` JobTypes?

**Comment by jonmv** [comment]
They will hopefully be deleted, replaced by these.

**Comment by bratseth** [comment]
We should discuss this on an architecture meeting. The names of the environments should be consistent with this, otherwise it is just adding confusion instead of reducing. I think that makes it a very big change and probably not worth it.

The staging environment is also where applications should implement performance tests, which makes "upgrade" a bad choice.

**Comment by jonmv** [comment]
Yes, we should discuss this. Perhaps we could do without the test environment, and make do with only staging, though. So much to discus ...

**Comment by jonmv** [comment]
About environment names: `test` isn't called `system`, and, as you say, we could want to do performance tests in `staging`, but `perf` is a different environment. 

If we had a single `test` environment, that would be good. But that's some change ... so I'll revert this for now.

**Pull request merged**
