### PR TITLE
GC unused and deprecated code

### PR DESCRIPTION
**Pull request by baldersheim**
@bratseth or @gjoranv or @bjorncs PR
forgotten ?

### CODE REVIEW

**Comment by bratseth** [comment]
Not forgotten - this was deprecated very soon before 8.0. That said it's unlikely to be called by anyone so I may be too conservative here.

**Comment by baldersheim** [comment]
April 21st are ages ago - 7+ weeks => agree, a bit on the conservative side.

**Comment by gjoranv** [comment]
I couldn't find any occurrences of `new ExecutionFactory` in my (now rather outdated) snapshot of hosted apps. The problem now is that the first 8 has been release, as I see it.

**Comment by baldersheim** [comment]
Some pragmatism, especially as no  opensource release has been made yet.

**Comment by gjoranv** [comment]
👍

**Pull request merged**
