### PR TITLE
Remove duplicate validation messages

### PR DESCRIPTION
**Pull request by jonmv**
@bratseth or @bjorncs please review and merge. `? extends Collection<String>` should accommodate the existing `List<String>` used by current `config-model` code.

### CODE REVIEW

**Comment by bratseth** [comment]
Wont that require recompilation of the old model?

**Comment by jonmv** [comment]
Why? `Map<ValidationId, ? extends Collection<String>>` should be capable of accepting a `Map<ValidationId, List<String>>` ... ?

**Comment by jonmv** [comment]
The caller is old, and passes an argument which is a `... List<String>` — this is fine with the old signature, which matches this exactly, _and_ with the new one.

**Comment by bratseth** [comment]
Yes, but signature changes which are type-compatible may require recompiling the caller as the byte-code invoke is for the exact types of the signature it matches. I don't recall the exact rules so don't know if that is true in this case though.

**Comment by jonmv** [comment]
I doubt it, since this is a generic signature.

**Comment by jonmv** [comment]
Probably doesn't matter that the generic type matches, as it's erased at runtime anyway.

**Comment by jonmv** [comment]
If this was a change from accepting a `List` to `Collection`, it could matter, and perhaps it wouldn't work. But the signature here is a `Map` in both cases, so I'd be very surprised if this wasn't OK.

**Review by bjorncs — APPROVED** [review]
The generic type of `Map` is erased at runtime.

**Pull request merged**
