### PR TITLE
Hide symbols

### PR DESCRIPTION
**Pull request by baldersheim**
@geirst or @toregge PR

### CODE REVIEW

**Review by toregge — CHANGES_REQUESTED** [review]
These changes causes the travis build to fail.

**Comment by baldersheim** [comment]
hmm, Do you have any idea why ?
These methods are only used in the same .hpp file.
So if it generated lower_bound is should also be able to do the same with clearPath/setupEmpty. 

CMakeFiles/searchlib_enumstore_test_app.dir/enumstore_test.cpp.o: In function `search::btree::BTreeConstIterator<search::datastore::AlignedEntryRefT<31u, 4u>, search::datastore::EntryRef, search::btree::NoAggregated, search::EnumStoreComparatorWrapper const, search::btree::BTreeTraits<16ul, 16ul, 10ul, true> >::lower_bound(search::datastore::EntryRef, search::datastore::AlignedEntryRefT<31u, 4u> const&, search::EnumStoreComparatorWrapper)':
/source/vespalib/src/vespa/vespalib/btree/btreeiterator.hpp:635: undefined reference to `search::btree::BTreeIteratorBase<search::datastore::AlignedEntryRefT<31u, 4u>, search::datastore::EntryRef, search::btree::NoAggregated, 16u, 16u, 10u>::clearPath(unsigned int)'
/source/vespalib/src/vespa/vespalib/btree/btreeiterator.hpp:616: undefined reference to `search::btree::BTreeIteratorBase<search::datastore::AlignedEntryRefT<31u, 4u>, search::datastore::EntryRef, search::btree::NoAggregated, 16u, 16u, 10u>::clearPath(unsigned int)'
/source/vespalib/src/vespa/vespalib/btree/btreeiterator.hpp:612: undefined reference to `search::btree::BTreeIteratorBase<search::datastore::AlignedEntryRefT<31u, 4u>, search::datastore::EntryRef, search::btree::NoAggregated, 16u, 16u, 10u>::setupEmpty()'
CMakeFiles/searchlib_enumstore_test_app.dir/enumstore_test.cpp.o: In function `search::btree::BTreeConstIterator<search::datastore::AlignedEntryRefT<31u, 4u>, search::btree::BTreeNoLeafData, search::btree::NoAggregated, search::EnumStoreComparatorWrapper const, search::btree::BTreeTraits<16ul, 16ul, 10ul, true> >::lower_bound(search::datastore::EntryRef, search::datastore::AlignedEntryRefT<31u, 4u> const&, search::EnumStoreComparatorWrapper)':
/source/vespalib/src/vespa/vespalib/btree/btreeiterator.hpp:635: undefined reference to `search::btree::BTreeIteratorBase<search::datastore::AlignedEntryRefT<31u, 4u>, search::btree::BTreeNoLeafData, search::btree::NoAggregated, 16u, 16u, 10u>::clearPath(unsigned int)'
/source/vespalib/src/vespa/vespalib/btree/btreeiterator.hpp:616: undefined reference to `search::btree::BTreeIteratorBase<search::datastore::AlignedEntryRefT<31u, 4u>, search::btree::BTreeNoLeafData, search::btree::NoAggregated, 16u, 16u, 10u>::clearPath(unsigned int)'
/source/vespalib/src/vespa/vespalib/btree/btreeiterator.hpp:612: undefined reference to `search::btree::BTreeIteratorBase<search::datastore::AlignedEntryRefT<31u, 4u>, search::btree::BTreeNoLeafData, search::btree::NoAggregated, 16u, 16u, 10u>::setupEmpty()'
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: searchlib_enumstore_test_app: hidden symbol `_ZN6search5btree17BTreeIteratorBaseINS_9datastore16AlignedEntryRefTILj31ELj4EEENS2_8EntryRefENS0_12NoAggregatedELj16ELj16ELj10EE9clearPathEj' isn't defined
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [searchlib/src/tests/attribute/enumstore/searchlib_enumstore_test_app] Error 1

**Comment by toregge** [comment]
The code for clearPath and setupEmpty is not generated since the compiler has been told not to do it.
btreeiterator.h and enumstorebase.h contains variants of "extern template class BTreeIteratorBase'.

Removing those declarations will allow the code to compile and link, at the cost of some bloat (e.g. libsearchlib.so gets a larger text segment and more symbols) and the compiler spends more time generating code for the same functions in multiple compilation units.

**Review by toregge — APPROVED** [review]
Travis build should now work, linking issue has been resolved by https://github.com/vespa-engine/vespa/pull/9820

**Comment by baldersheim** [comment]
Thanks @toregge, works as expected now.

**Pull request merged**
