### PR TITLE
Do not export service monitor internals

### PR DESCRIPTION
**Pull request by hakonhall**

### CODE REVIEW

**Comment by bjorncs** [comment]
Afaik, `SlobrokMonitorManagerImpl` must be placed in an exported package if it is listed as a component in _services.xml_. @gjoranv: is that correct?

**Comment by hakonhall** [comment]
Please take another look @bjorncs

**Review by bjorncs — APPROVED** [review]
Nice 👍

**Comment by gjoranv** [comment]
@bjorncs, Jdisc does not require that components are part of an exported package. We look up the bundle based on the id given in services.xml and use reflection to create it. However, if the component exposes an api to be used from other bundles, it must be exported.

**Comment by hakonhall** [comment]
@gjoranv this PR broke the config server - it was not enough to depend on container-di (provided): It resulted in a noclassdeffound on componentgraph.Provider. What is the correct module to depend on?

**Pull request merged**
