### PR TITLE
Since the most important aspect our use of hash maps/sets is for spee…

### PR DESCRIPTION
**Pull request by baldersheim**
…d we change from

using prime numbers as table size and modulo to using 2^N and using simple AND.

@vekterli or @geirst PR

### CODE REVIEW

**Review by vekterli — APPROVED** [review]
:+1: One possible caveat is that both `vespalib::hash` and `std::hash` (under GCC) use the _identity_ function for hashing integers, so AND-based bucket distribution may be more susceptible to collisions for clustered inputs. But we'll quickly find out if this is a problem in practice. If it _is_ a problem, we should still use AND-based tables but improve our hashing functions to actually properly mix bits around.

**Comment by baldersheim** [comment]
Correct, however after the huge impact demonstrated on the sparse dotproduct indicates that it is worthwhile. Last time I tested, (a few years back), it was actually slower, but I later concluded that was due to https://github.com/vespa-engine/vespa/pull/12600. Which is exactly what you point out. Using mod prime will hide those kind of bad issues.

**Review by geirst — APPROVED** [review]
👍

**Comment by geirst** [comment]
But note we have failing unit tests:
```
document_features_store_test.cpp: info:  running test suite 'document_features_store_test.cpp'
document_features_store_test.cpp: info:  status_for_test 'require that DocumentFeaturesStore can store features.': PASS
document_features_store_test.cpp: info:  status_for_test 'require that DocumentFeaturesStore can store ranges.': PASS
document_features_store_test.cpp: info:  status_for_test 'require that DocumentFeaturesStore can store large ranges.': PASS
document_features_store_test.cpp: info:  status_for_test 'require that DocumentFeaturesStore can use very large ranges.': PASS
document_features_store_test.cpp: info:  status_for_test 'require that duplicate range features are removed.': PASS
document_features_store_test.cpp: info:  status_for_test 'require that only unique features are returned': PASS
document_features_store_test.cpp: info:  status_for_test 'require that both features and ranges are removed by 'remove'': PASS
document_features_store_test.cpp: info:  status_for_test 'require that both features and ranges counts towards memory usage': PASS
document_features_store_test.cpp: info:  status_for_test 'require that DocumentFeaturesStore can be serialized': PASS
document_features_store_test.cpp:211: error: check failure #1: '800u == features_store.getMemoryUsage().usedBytes()' in thread '0(1)' (document_features_store_test.cpp)
    STATE[0]: 'require that serialization cleans up wordstore' (document_features_store_test.cpp:203)
lhs: 800
rhs: 848
document_features_store_test.cpp:213: error: check failure #2: '752u == features_store.getMemoryUsage().usedBytes()' in thread '0(1)' (document_features_store_test.cpp)
    STATE[0]: 'require that serialization cleans up wordstore' (document_features_store_test.cpp:203)
lhs: 752
rhs: 800
document_features_store_test.cpp: ERROR: status_for_test 'require that serialization cleans up wordstore': FAIL
document_features_store_test.cpp: info:  test summary --- 9 test(s) passed --- 1 test(s) failed
document_features_store_test.cpp: info:  imported 60 passed check(s) from 1 thread(s)
document_features_store_test.cpp: info:  summary --- 60 check(s) passed --- 2 check(s) failed
document_features_store_test.cpp: info:  CONCLUSION: FAIL
```

**Comment by baldersheim** [comment]
@geirst and @vekterli Can you have a quick look at the tests I had to modify.
1 had assumptions on size of hashmap.
2 had assumptions on ordering when iterating a hash map.

**Review by vekterli — APPROVED** [review]
:+1: I think I had to change that very same docsummary test when I altered ordering semantics of weighted sets not too long ago.

**Pull request merged**
