### PR TITLE
Only the cluster name is ever a valid ID here anyway

### PR DESCRIPTION
**Pull request by jonmv**
@vekterli I would like to verify this assumption before I start the cleanup work :)

### CODE REVIEW

**Comment by jonmv** [comment]
Perhaps @baldersheim would like to review instead?

**Comment by jonmv** [comment]
There's something in C++ as well ...

**Comment by jonmv** [comment]
May need to update unit tests for the C++ part.

**Comment by jonmv** [comment]
Hmm... The C++ implementation already correctly handles this for `content`.

**Comment by baldersheim** [comment]
Yes, I will complete the c++ part and cleanup.

**Comment by jonmv** [comment]
Thanks.

**Comment by jonmv** [comment]
Will need to replace the use of :raw config subscription in unit tests in C++ for this to work. Far beyond the original scope >_< Closing for now. What I _really_ wanted was to fix the default in `StoragePolicy` so it actually works, so it doesn't have to be specified everywhere. But perhaps we can just use `ContentPolicy` instead, everywhere ...

**Pull request closed without merging**
