### PR TITLE
Yngveaasheim/define container metrics [skip-systemtest]

### PR DESCRIPTION
**Pull request by yngveaasheim**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by yngveaasheim** [comment]
@gjoranv or @olaaun Please review and merge.
@kkraune FYI

**Review by gjoranv — APPROVED** [review]
👍  Merge if green build.

**Comment by kkraune** [comment]
I suggest we also make the changes in the other files to use the definition, too, so easier to keep track of what needs to be done:
```
git grep httpapi_latency
config-model/src/main/java/com/yahoo/vespa/model/admin/monitoring/VespaMetricSet.java:        metrics.add(new Metric("httpapi_latency.max"));
config-model/src/main/java/com/yahoo/vespa/model/admin/monitoring/VespaMetricSet.java:        metrics.add(new Metric("httpapi_latency.sum"));
config-model/src/main/java/com/yahoo/vespa/model/admin/monitoring/VespaMetricSet.java:        metrics.add(new Metric("httpapi_latency.count"));
C02DR9A6MD6R:vespa kraune$ 
```
I.e. change VespaMetricSet.java

**Comment by gjoranv** [comment]
It seems that is done in this branch already, or am I missing something?

**Comment by kkraune** [comment]
> It seems that is done in this branch already, or am I missing something?

Yes you are right :-) my bad

**Pull request merged**
