### PR TITLE
Do not follow links when deleting recursively

### PR DESCRIPTION
**Pull request by mpolden**
...like the Javadoc already says. Discovered the hard way :sweat_smile:

### CODE REVIEW

**Review by hakonhall — APPROVED** [review]

**Review by hakonhall — COMMENTED** [review]
Wait, isDirectory() should still be true if it points to a directory. It should be transparent.

**Comment by hakonhall** [comment]
I think isDirectory() should be documented to be either a directory or a symlink pointing to a directory. If explicit testing is needed - as in recursiveDelete(), there should be a call to a new UnixPath.isSymbolicLink.

**Comment by mpolden** [comment]
> I think isDirectory() should be documented to be either a directory or a symlink pointing to a directory.

Sure, will make that change before merging.

**Comment by mpolden** [comment]
@hakonhall PTAL.

**Review by tokle — APPROVED** [review]

**Review by hakonhall — COMMENTED** [review]
👍

**Pull request merged**
