### PR TITLE
Add just 503 to the retry condition

### PR DESCRIPTION
**Pull request by jonmv**
@hakonhall please merge.

### CODE REVIEW

**Comment by jonmv** [comment]
Merging to avoid the other one going out.

**Comment by jonmv** [comment]
Please review :)

**Comment by hakonhall** [comment]
Probably fine

In general, it would be nice to let the owner of the strategy to make their own decision on which exceptions are retryable.

**Comment by jonmv** [comment]
I'm hoping all of this HTTP stuff gets a proper overhaul with 11!

**Pull request merged**
