### PR TITLE
Remove unused code.

### PR DESCRIPTION
**Pull request by baldersheim**
@hmusum PR

### CODE REVIEW

**Comment by hmusum** [comment]
Old config models will need the config, so I don't think we can remove it yet.

**Comment by baldersheim** [comment]
Don't each model have its own ?

**Comment by hmusum** [comment]
Config server looks up config definition before it asks model for config and will fail if it's unknown.

**Comment by baldersheim** [comment]
This must then wait till 203 is last version in hosted then ?

**Comment by hmusum** [comment]
Yes, wait until 6.205.22 is oldest version in use

**Comment by baldersheim** [comment]
Now 6.205.22 is the latest one. Shall we let it go then.

**Comment by hmusum** [comment]
Yes, that should be OK

**Review by hmusum — APPROVED** [review]

**Pull request merged**
