### PR TITLE
Add a grace period before upgrading new nodes

### PR DESCRIPTION
**Pull request by bratseth**
A suggestion to wait a month after provisioning before starting to OS upgrade nodes.

I think this would be helpful for dev/perf as most apps are only worked on for less than this [citation needed], so they would avoid running into (and paying for) OS upgrades. 

Arguably also for dev, if new nodes are added to solve some problem you don't want to immediately introduce new changes, and if the capacity is temporary due to e.g autoscaling why do it at all.

### CODE REVIEW

**Comment by bratseth** [comment]
Spread budget + staggered start would be best?

**Comment by mpolden** [comment]
Figured it was easier to just exclude nodes that are deferring their upgrade. PTAL

**Comment by mpolden** [comment]
And upgrades by DelegatingOsUpgrader/RebuildingOsUpgrader are less impactful, so I removed the grace period for those.

**Review by bratseth — COMMENTED** [review]
Fine ... making the grace depend on the type has higher entropy though.

**Comment by mpolden** [comment]
Yes, but the strategies of each implementation are already different so this is just another unique property of RetiringOsUpgrader.

**Pull request merged**
