### PR TITLE
Gjoranv/node info

### PR DESCRIPTION
**Pull request by gjoranv**
This makes the format from `/applicationmetrics/v1/values` equal to the future `/metrics/v2/values` api.

### CODE REVIEW

**Comment by bratseth** [comment]
I don't think you should rename a field as that will break any clients of this?

**Comment by gjoranv** [comment]
Probably true, because we still don't bundle def-files with the fat model. I will add it as a new field with a TODO to remove the old one when the oldest hosted version is past using it.

**Comment by hmusum** [comment]
You should not rename a field like this. See https://docs.vespa.ai/documentation/cloudconfig/configapi-dev.html#def-compatibility. Essentially, you can't remove a field without a default value. 

I guess you could add a default value for the field you want to remove, wait until all users have the config with default value and then remove it.

Another caveat: You cannot remove a field if there are config overrides referring to the field you want to remove.

**Comment by bratseth** [comment]
I commented on changing the web service API:
"Expose hostname, and rename nodeId -> role."

But yes, you also cannot rename (that is, remove) a config value.

**Comment by gjoranv** [comment]
I thought more about this, and it is ok because there are no user configs to this config def. The config model always produces the value for the correct version. I have done this before without issues. But I will play it safe and add a temporary default before renaming.

Regarding the web API, this is only an internal API, not public.

**Comment by bratseth** [comment]
It's not an internal API: https://docs.vespa.ai/documentation/reference/metrics.html

**Comment by gjoranv** [comment]
That's the old API, where this field does not exist.

**Review by olaaun — APPROVED** [review]

**Pull request merged**
