### PR TITLE
Balder/refactor query building 1

### PR DESCRIPTION
**Pull request by baldersheim**
@toregge PR
The last commit here prevents incorrectly assuming that a string term can not be a range term.
This is the reason why #27645 had to reverted. Even with the revert it is incorrect for ws<long>.
This should fix the root cause.

### CODE REVIEW

**Review by toregge — APPROVED** [review]
👍

**Comment by baldersheim** [comment]
The issue with + and whitespace must be fixed before adding #27645 back.
The latter was the main intention, and should be fine.

**Comment by baldersheim** [comment]
@toregge Any reason for the no merge label still ?

**Comment by toregge** [comment]
No. @vekterli: FYI

**Pull request merged**
