### PR TITLE
Synchronise access to session status of an application, and eliminate…

### PR DESCRIPTION
**Pull request by hmusum**
… some races

### CODE REVIEW

**Comment by bratseth** [comment]
I may be missing it, but how does #9159 help to ensure that the latest deployment on the config server is the latest deployment saved in the controller?

I think we either need to serialize deployments (as now), or use optimistic locking where the assumed currently active session id is passed to the config server in the deploy command and validated inside the locked section in the config server.

**Comment by jonmv** [comment]
It doesn't help towards that, but there is a check for these conflicts in`Deployment.activate()`, which would cause the conflicting deployment to fail. 
This work was done to fix the concurrent deactivation/redeployment bug that leads to inconsistent super models across config servers. 

I thought about allowing controller-deployments to sneak ahead of redeployments, but I forgot to add that part. I think the idea was to store some extra state for each application indicating what deployment we intent to activate next, and let external deployments override the state set by internal deployments, and then to verify the deployment we're about to activate is still intended, when we get that far (and inside the lock, obviously).

**Review by jonmv — COMMENTED** [review]
Guessing this will break the tests :p

**Review by jonmv — APPROVED** [review]

**Comment by bratseth** [comment]
The check in Deployment.activate() validates that there is no race between prepare and activate (i.e optimistic locking), but deploy is a 1-phase operation as seen from the controller - I don't see how this ensures that we cannot have a race between two threads doing 1) reading application state, 2) deploy,  3) write resulting state.

**Comment by jonmv** [comment]
The currently active session is read and updated while the tenant application lock (not the node repo application lock) is held.  
When a session wants to activate, it checks whether the session that was active when it started its deployment is still the active session: if it is, it proceeds, and updates the currently active session; otherwise, it bails out.  
So, if two threads deploy concurrently, only the first to grab the application will be able to activate — the other throws an exception, and ends up doing nothing, as only session state is manipulated before activation.

**Comment by bratseth** [comment]
I think you are talking about self-consistency inside the config server here - yes that is taken care of, I agree (and double reservation can happen as you say but that is ok).

What I'm asking about is consistency between the state in the config server and the controller. Not an issue with periodic redeploys, but it doesn't seem safe to rely on that we happen to not schedule concurrent deploys in the controller. At least if there are manual operator deployments, we might.

**Comment by jonmv** [comment]
I don't see the difference. If the controller's deployment fails (due to a conflict) it doesn't record the deployment (as successful).

**Comment by bratseth** [comment]
From the controller side, can't this happen (where A and B is some combination of application version and deployment parameters for the same app)?:

```
Thread 1 deploys A
Thread 2 deploys B
Thread 2 stores the resulting application state
Thread 1 stores the resulting application state
```

The config server now have deployed B and the controller has the result of deployment A stored (where both states are internally consistent).

**Comment by jonmv** [comment]
Ignoring that deployment is pretty slow, and assuming that A was completely deployed before deployment of B was initiated (in the config server), yes. 
However, deployment is also guarded by a lock in the controller, so it's not a problem.

**Comment by bratseth** [comment]
Indeed, but the PR that started this discussion #9150 was to remove that lock in the controller and the claim was that this one would make that possible.

**Comment by jonmv** [comment]
I'm sorry, my comment there was not meant as a reply to your question. 

Anyway, that PR was to remove the node repository application lock for periodic redeployments. They've been kept out of the discussion here. 
However, as you made me realise, that change won't do much good on its own, since we'll only trade timeouts for conflicts. I'll remedy that when we get as far as to merge it. We expect some trouble along the way :)

**Pull request merged**
