### PR TITLE
Complete upgrades which already started

### PR DESCRIPTION
**Pull request by bratseth**
This avoids starvation when an upgrade takes so long that it doesn't
complete until the next version is released.

This also removes rescheduling of upgrades which has not commpleted after 12 hours;
retrying should be on the job level only.

@mpolden please review

@kraune fyi

### CODE REVIEW

**Comment by kkraune** [comment]
Thanks!

**Comment by mpolden** [comment]
I suggested this weeks ago, but was shot down.. :-)

LGTM

**Comment by bratseth** [comment]
Yes, not sure this is better overall ... it means it will take longer to get applications to the latest version, and we'll have more of a problem if a new version is pushed because some problem is detected in the previous one which is not caught in test. But it might *) help stream since they mostly block so they never complete.

*) Otoh, when doing this I saw that we are starting all upgrades from the top again after they have spent 12 hours. That doesn't make any sense to me, and it could be just changing that would solve the problem.

Otoh-otoh, this approach is definitely better if we ever decide to up our release frequency to more than 2-3x what we have today.

**Comment by mpolden** [comment]
Another approach I thought about was not to cancel upgrades for applications that have started upgrading and then entered a block change window. That's what happens for stream, right?

**Pull request merged**
