### PR TITLE
Fall back to default cloud account in node spec

### PR DESCRIPTION
**Pull request by mpolden**
This ensures that node spec always contains the cloud account being used (either
custom or default).

### CODE REVIEW

**Comment by mpolden** [comment]
Merge with internal PR.

**Review by bratseth — COMMENTED** [review]
I suggest making CloudAccount non-optional in Cloud and NodeSpec, and adding a CloudAccount.empty() instead. All these optionals are hard to deal with, and we will eventually have explicit accounts most places or maybe everywhere.

Otherwise LGTM!

**Comment by mpolden** [comment]
PTAL

**Comment by bratseth** [comment]
👍

**Pull request merged**
