### PR TITLE
Bratseth/remove deprecated api usage

### PR DESCRIPTION
**Pull request by bratseth**
@arnej27959 please review

### CODE REVIEW

**Comment by arnej27959** [comment]
@lesters another pair of eyes on this would be good

**Comment by bratseth** [comment]
Now would be a good time to merge this.

**Comment by bratseth** [comment]
Working on it again.

**Comment by bratseth** [comment]
Done, please merge

**Review by lesters — APPROVED** [review]

**Comment by lesters** [comment]
There are test errors:

```
[ERROR] Failures: 
[ERROR]   JsonRendererTestCase.test:579->assertEqualJson:1209 expected:<{root={children=[{children=[{fields={c=d, uri=http://localhost/1}, id=http://localhost/1, relevance=0.9, types=[summary]}], id=usual, relevance=1.0}, {fields={e=f}, id=type grouphit, relevance=1.0, types=[grouphit]}, {fields={b=foo, uri=http://localhost/}, id=http://localhost/, relevance=0.95, types=[summary]}], coverage={coverage=100, documents=500, full=true, nodes=1, results=1, resultsFull=1}, errors=[{code=18, message=boom, summary=Internal server error.}], fields={totalCount=0}, id=toplevel, relevance=1.0}}> but was:<{root={id=toplevel, relevance=1.0, fields={totalCount=0}, coverage={coverage=0, documents=500, degraded={match-phase=false, timeout=false, adaptive-timeout=false, non-ideal-state=true}, full=false, nodes=0, results=1, resultsFull=0}, errors=[{code=18, summary=Internal server error., message=boom}], children=[{id=usual, relevance=1.0, children=[{id=http://localhost/1, relevance=0.9, types=[summary], fields={uri=http://localhost/1, c=d}}]}, {id=type grouphit, relevance=1.0, types=[grouphit], fields={e=f}}, {id=http://localhost/, relevance=0.95, types=[summary], fields={uri=http://localhost/, b=foo}}]}}>
[ERROR]   CoverageTestCase.testDefaultCoverage:41 expected:<0> but was:<1>
[ERROR]   CoverageTestCase.testDefaultSearchScenario:56 expected:<0> but was:<1>
[ERROR]   CoverageTestCase.testRequestingCoverageSearchScenario:67 expected:<1> but was:<2>
[ERROR]   CoverageTestCase.testZeroCoverage:20 expected:<0> but was:<100>
```

**Pull request merged**
