### PR TITLE
Reapply "Upgrade ZooKeeper client library to 3.5.8"

### PR DESCRIPTION
**Pull request by hmusum**
Reverts vespa-engine/vespa#13258

Depends on https://github.com/vespa-engine/vespa/pull/13259, please review only

### CODE REVIEW

**Review by hakonhall — APPROVED** [review]

**Comment by hakonhall** [comment]
Why is the server only upgraded to 3.5.7?

**Comment by hmusum** [comment]
Server will be upgraded to 3.5.8 in https://github.com/vespa-engine/vespa/pull/13254, I just want to do client first.

**Comment by hakonhall** [comment]
But the server *is* upgraded, only to 3.5.7.

**Comment by hmusum** [comment]
Sorry, you are right, not intentional, will fix

**Comment by hmusum** [comment]
That explains why this failed originally, I wasn't planning to upgrade server. Oh, well.

**Review by hakonhall — APPROVED** [review]

**Comment by hakonhall** [comment]
👍

**Review by bjorncs — COMMENTED** [review]
👍 🤞

**Pull request merged**
