### PR TITLE
Avoid ExitOnOutOfMemoryError

### PR DESCRIPTION
**Pull request by hakonhall**
The -XX:+ExitOnOutOfMemoryError flag was introduced in Java 8 update 92, thus
not compatible with all Java 8 installations.

http://www.oracle.com/technetwork/java/javase/8u92-relnotes-2949471.html

### CODE REVIEW

**Review by baldersheim — CHANGES_REQUESTED** [review]
Where do we not have at least 8.92 ?
The latest on stable is 8.131.
If we do not require at least that we should.

**Review by freva — COMMENTED** [review]
This was deliberately changed in #6427 knowing this limitation. Where is this a problem?

**Comment by hakonhall** [comment]
Our RHEL7  hosts have u60.

**Comment by baldersheim** [comment]
Then they must be upgraded, there are a lot of fixes that has gone in since u60.

**Comment by baldersheim** [comment]
All of these little hacks have a tendency to complicate code and be left in there. So unless it is really, really hard to upgrade the java package I oppose.

Using latest 7.5 repo will give you .181.

**Comment by baldersheim** [comment]
BTW, why is this a problem now. It is some time ago since this option was changed.

**Comment by hakonhall** [comment]
We have never run Java on our RHEL 7 before, which we will with host-admin.

I'll let @andreer comment on the upgrade plan.

**Comment by andreer** [comment]
As it is, we rarely update the base software (yum) on our infrastructure (config server / proxy) hosts unless we have a reason to (dirtycow etc), and I do not think there is any automation for it. I guess we're hoping it'll be solved once we're on docker.

I will be continuing to upgrade the config servers, but my focus has been on replacing them with higher memory ones, not newer base software (although this probably does happen as a side effect). 

If we need a certain java version for host admin, I suggest we put this in a chef recipe for now. As that java is not being used as of now, it should be safe to upgrade without any need for suspend/restart.

**Comment by baldersheim** [comment]
No restart or anything required.
@smorgrav When will RHEL7 hosts be on 7.4 or 7.5 the manual way ?

**Comment by smorgrav** [comment]
We have no plans to do anything before we have it automated but that should be ready within a sprint or so? But if this depends on host-admin on infra nodes we might need to do this manually for those hosts.

As for java versions we might want to control that separately - so we are not tied down to the version that comes with ylinux

**Review by freva — APPROVED** [review]

**Comment by hakonhall** [comment]
Created VESPA-13167 to track the revert too.

**Review by baldersheim — APPROVED** [review]
OK, this should time out at EOQ Q3 then

**Pull request merged**
