### PR TITLE
Bratseth/tensorflow models

### PR DESCRIPTION
**Pull request by bratseth**
@lesters please review

First stab at TF translation, verified with the first TF tutorial example.
Not wired in yet.

### CODE REVIEW

**Review by lesters — APPROVED** [review]
Nice, this is very cool. I have only currently taken a dive into Mnist_SoftmaxTestCase.java, and I will play around with other models as well. 

In general though, it should be possible to do some analysis of the graph to avoid all the renaming of dimensions?

All the new files lack copyright headers:
- ImportResult.java
- OperationMapper.java
- TensorConverter.java
- TensorFlowImporter.java
- TypeTensorFunction.java
- MatmulTestcase.java

I guess some discussions should be had on how this should be wired in.

Otherwise, looks great. Merge at will.

**Comment by bratseth** [comment]
Thanks. 

**Renaming**: Yes, we could keep the renaming and make it fast, but to make it super-fast (optimize layout) we need to resolve dimension constraints globally and avoid renaming anyway so we should do that instead. It seems a bit tricky, so I want to have a simple implementation end-to-end passing tests first though. It's also not possible in general, but probably not a problem in practice.

**Wiring in**: Repeating my suggestion here in case someone outside our mailing list reads it and have comments:

We want to support TensorFlow models for ranking in Vespa by converting TensorFlow graphs to ranking expressions, and TensorFlow tensor variables to constant tensors, as config time.

For this we need to define
1. A way to add the TensorFlow serialized model to Vespa.
2. A way to supply inputs to a TensorFlow computation from Vespa.
3. A way to refer to a specific computation (output) from that TensorFlow model in Vespa.

Suggested solution for these:
1: TensorFlow SavedModels are added under the models/ subdirectory in the application package. Each specific model is expected to be placed in a separate subdirectory, but no further structure is imposed.

2: Inputs to model computations are  represented as named "Placeholders" in TensorFlow. These must be supplied by Vespa from documents, queries or constants at ranking time. We keep these literally in the generated ranking expression, such that each placeholder must be represented by a macro in the ranking expression, where the macro defines how that input tensor is fetched (or computed).

3: To refer to a specific TensorFlow computation, we must specify the TensorFlow model, signature and output. This is done by embedding the reference in a macro, where the expression string is a triple consisting of model subdirectory, tensorflow signature def and tensorflow output (where the two latter can be skipped when unique). E.g

macro myTensorFlowFeature {
  expression: models/myTensorFlowModel/:my_signature:my_output
}

**Comment by kkraune** [comment]
breaks factory:

testImporting(com.yahoo.searchlib.rankingexpression.integration.tensorflow.Mnist_SoftmaxTestCase)  Time elapsed: 0.425 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: /var/builds/workspace/115429-v3-component/BUILD_CONTAINER/build/label/DOCKER-HIGHCPU/app_root/repositories/vespa/searchlib/target/tensorflow_native_libraries-1513504911607-0/libtensorflow_jni.so: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /var/builds/workspace/115429-v3-component/BUILD_CONTAINER/build/label/DOCKER-HIGHCPU/app_root/repositories/vespa/searchlib/target/tensorflow_native_libraries-1513504911607-0/libtensorflow_jni.so)
	at com.yahoo.searchlib.rankingexpression.integration.tensorflow.Mnist_SoftmaxTestCase.testImporting(Mnist_SoftmaxTestCase.java:28)

**Comment by kkraune** [comment]
as this is a big one, maybe just disable the failing test instead of full revert?

**Comment by bratseth** [comment]
Yes, it's not doing any damage ... I'll disable it and see if we can get this working on factory.

**Pull request merged**
