### PR TITLE
Add supporter role

### PR DESCRIPTION
**Pull request by smorgrav**
A supporter is granted read on everything - all systems and paths.

### CODE REVIEW

**Comment by smorgrav** [comment]
I've added tests to all places we test role privileges for hostedOperators. 

For Athenz it is modelled to be a new hostedSupporter role with a new rule in the hostedOperator policy for that role with the action "read".

Auth0 will use the role hostedSupporter

**Comment by smorgrav** [comment]
@bjorncs Since you have a lot of domain knowledge 
@freva Since you know this particular use case

**Review by bjorncs — APPROVED** [review]
LGTM

**Review by freva — APPROVED** [review]
Might as well add it to https://github.com/vespa-engine/vespa/blob/5d657d4537d753b09f9cedce19f785c35eba2d80/controller-server/src/main/java/com/yahoo/vespa/hosted/controller/restapi/user/UserApiHandler.java#L137 now as well to expose this to the console

**Comment by freva** [comment]
```
[ERROR] Failures: 
[ERROR]   UserApiOnPremTest.userMetadataOnPremTest:55 user-without-applications.json (with ignored fields) expected:<[\Q{"isPublic":\E[^,:\[\]{}]*\Q,"user":{"name":"Joe Developer","email":"dev@domail","nickname":"dev"},"tenants":{},"operator":["hostedOperator"]}\E]> but was:<[{"isPublic":false,"user":{"name":"Joe Developer","email":"dev@domail","nickname":"dev"},"tenants":{},"operator":["hostedSupporter","hostedOperator"]}]>
```

**Review by freva — APPROVED** [review]

**Pull request merged**
