### PR TITLE
Jvenstad/more general roles

### PR DESCRIPTION
**Pull request by jonmv**
@mpolden or @tokle please review. Changes since this morning is a more fine-grained path group and policy setup, to allow for more versatile role definitions.

### CODE REVIEW

**Comment by jonmv** [comment]
Oh, and allowing node restarts for tenant admins.

**Comment by jonmv** [comment]
Uh, no, those commits aren't pushed yet. Hang on :)

**Comment by jonmv** [comment]
Here we go. PTAL.

**Comment by jonmv** [comment]
I think there's something missing: each role has an intended context. I suggest storing this when defining the role, and requiring a value for each of its context limittaions when assigning a role to a role membership. Something like

```java
tenant(TenanName.class,
       inheritedRole,
       Policy.somePolicy...)
```

and

```java
membership = Role.tenant.in(system).limitedTo(tenantName);
```

**Review by tokle — APPROVED** [review]

**Comment by jonmv** [comment]
https://github.com/vespa-engine/vespa/pull/8969 has a suggestion for how to require the correct context for each role, when attempting to use it.

**Pull request merged**
