### PR TITLE
Allow Object, not just String, to Velocity

### PR DESCRIPTION
**Pull request by jonmv**
@hakonhall please merge.

### CODE REVIEW

**Review by hakonhall — APPROVED** [review]
FYI: I actually prefer forcing the caller to make an explicit call to toString()

**Comment by jonmv** [comment]
Ah, but the point is that velocity accepts objects -- not just strings. Unless I misunderstood the whole language, that is ... :)

**Comment by hakonhall** [comment]
I don't think we should utilize the full spectrum Velocity offers, but limit ourselves to a simpler API.

**Comment by jonmv** [comment]
Ok. 

I'm writing the template for MOTD now, and I find it useful to have full access to the Java object inside the template. This allows for a single MOTD template, rather than one for each type of host, etc.. 

I promise I won't go complete overboard with my newfound powers ... ! 🙏

**Comment by hakonhall** [comment]
I see, I didn't realize this is how one gains access to the object. Nice.

**Pull request merged**
