### PR TITLE
Jvenstad/optimistic preparations take 3

### PR DESCRIPTION
**Pull request by jonmv**
@hmusum please review.

### CODE REVIEW

**Comment by jonmv** [comment]
Perhaps there should be some periodic cleansing as well?

**Review by hmusum — APPROVED** [review]

**Comment by hmusum** [comment]
Probably a maintainer would make sense (but when can it be removed, some time after it was created?). And what happens with this when it is rolled out and there is a zookeeper node /preparing left over from an earlier release?

**Comment by jonmv** [comment]
Yes, it's too brittle. It's only the periodic redeployments that should be blocked off, but there's nothing to identify these now.

**Comment by jonmv** [comment]
Need to think about this a bit more.

**Comment by jonmv** [comment]
Won't do this unless we see a need for it.

**Pull request closed without merging**
