### PR TITLE
Balder/short circuit and or

### PR DESCRIPTION
**Pull request by baldersheim**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.
@bratseth or @vekterli or @bjorncs or @hmusum PR
Probably best to review in commit order. Only the last commit implements the fix.
This is a rather vital part, so we'd better get it right....

### CODE REVIEW

**Comment by baldersheim** [comment]
@jobergum FYI

**Comment by bratseth** [comment]
Unfortunately com.yahoo.document.select.rule is a public API so I don't think you should remove and privatize methods in the first commit.

Other than that, this LGTM but I don't know this code well and it is critical as you say, so one more reviewer would be good.

**Review by hmusum — APPROVED** [review]

**Comment by baldersheim** [comment]
I concluded that both the select and rule package are so obscure and has no external usage that the risk is closer to zero than you can represent with the smallest double you can make.
It was when I had cleaned up all the intellij warnings, that the one significant warning of possible bad cast identified the bug fixed in commit 2.
I felt that gave the cleanup individual value earning them eternal life :)

**Comment by bratseth** [comment]
Ok then  :-)

**Review by bjorncs — APPROVED** [review]

**Comment by baldersheim** [comment]
.select was removed from public in f565ed8391ab0fecc81601ade64bd4884ce80b36
I will complete it recursively

**Review by vekterli — COMMENTED** [review]
:+1:

**Pull request merged**
