### PR TITLE
Set Java system property java.io.tmpdir to $VESPA_HOME/tmp

### PR DESCRIPTION
**Pull request by hmusum**
There could be more places that this should be set ...

### CODE REVIEW

**Review by baldersheim — APPROVED** [review]
If not all, it is a step in the right direction.

**Comment by freva** [comment]
We need some cleanup policy merged with/before this.

**Comment by hmusum** [comment]
For ylinux 6 images this is done by the nodectl script when starting vespa (via yinst, see https://git.ouroath.com/vespa/vespa-yahoo/blob/master/vespascripts/src/nodectl-instance.sh#L172-L175). For ylinux 6 and centos images we need to do something, agreed.

**Comment by hmusum** [comment]
Cleanup now done, see https://git.ouroath.com/vespa/vespa-yahoo/pull/3893 and https://git.ouroath.com/vespa/centos-build/pull/96

**Pull request merged**
