### PR TITLE
A single element under sameElement operator can be pulled out to avoi…

### PR DESCRIPTION
**Pull request by baldersheim**
…d the sameElement operator.

@geirst or @toregge or @bratseth PR
@havardpe and @arnej27959 FYI

### CODE REVIEW

**Comment by bratseth** [comment]
Instead of this, I suggest you 
- change SameElementItem to extend CompositeItem instead of NonReducibleCompositeItem.
- Set the index to the compound name when it is added to SameElementItem (in the adding(..) hook).
NonReducibleCompositeItem is a marker item to prevent precisely this type of change, so doing it this way is just really messy. 

SameElementItem has sagely been marked @Beta so this is non-breaking, and in any case nobody is casting to a marker interface (I'd hope).

**Comment by baldersheim** [comment]
I will have to check how the backend reacts to getting the full name first.

**Comment by bratseth** [comment]
Or we could skip sending it if we're encoding the children of a SameElement.

**Comment by baldersheim** [comment]
Injecting the full name on the children will make it very ugly as it has to stripped away multiple places.
Instead I suggest that we add an Item extractSingleChild() on NonReducibleItem that you can implement if you can be reducible with some conversion. Return null if not.

Only SameElement and WeakAnd are NonReducible.
And NonReducibleCompositeItem is only checked in QueryCanonicalizer and QueryRewrite.

Or we could make a ReducibleWithConversion with that interface.

**Comment by bratseth** [comment]
> Instead I suggest that we add an Item extractSingleChild() on NonReducibleItem

Good idea! It can return an Optional then so implementations can opt out?

**Comment by baldersheim** [comment]
@bratseth Now you can have a look. It looks much better and cleaner now.

**Comment by baldersheim** [comment]
@bratseth ABI updated, should be good to go if you agree on the details. I made extractSingleChild part of CompositeItem as default permitted and let it be overridden by NonReducibleCompositeItem to disallow and then again explicit allowed by SameElement.

**Comment by bratseth** [comment]
Great With this we can also move the existing item-specific logic to the owning items, so I did that. Feel free to merge if you agree.

**Review by bratseth — APPROVED** [review]

**Comment by baldersheim** [comment]
Superb :)

**Pull request merged**
