### PR TITLE
Balder/targethits equal max targethits and hits

### PR DESCRIPTION
**Pull request by baldersheim**
@geirst and @bratseth PR
This relates to #31433

### CODE REVIEW

**Review by bratseth — DISMISSED** [review]
👍 👍

**Comment by bratseth** [comment]
Need ABI spec update due to `isNExplicit`.
Btw, I would suggest calling it `nIsExplicit`

**Comment by baldersheim** [comment]
Fixed

**Review by geirst — COMMENTED** [review]
👍

**Pull request merged**
