### PR TITLE
Allow user specified timeout for SyncSession

### PR DESCRIPTION
**Pull request by bjorncs**
FYI @baldersheim

### CODE REVIEW

**Review by vekterli — APPROVED** [review]
:+1:

**Comment by jobergum** [comment]
I think that a mb timeout is treated as an error so code that sets explicit timeout will see a DocumentAccessException with a error message containing something about 'timeout'.

**Comment by vekterli** [comment]
With the current `SyncSession` API design, I think that's pretty much required (since you return Documents, not response objects). Note that this PR doesn't change any error handling behavior; existing code using `SyncSession` must already be prepared to deal with exceptions.

It could be argued that the interface javadoc for the new timeout-accepting `get()` methods should state that `DocumentAccessException` is thrown on timeout rather than `RuntimeException`, but the former inherits the latter anyway.

**Comment by bjorncs** [comment]
Ok, I'll update the Javadoc to reflect that `DocumentAccessException` is thrown on timeout.

**Comment by jobergum** [comment]
Great, that's all.

**Pull request merged**
