### PR TITLE
Bratseth/job run reason tweaks

### PR DESCRIPTION
**Pull request by bratseth**
@mpolden please review

### CODE REVIEW

**Comment by mpolden** [comment]
Can we keep the build number? It was added to enable mapping SD jobs to events when debugging.

**Comment by bratseth** [comment]
We have the build jobs in the API and dashboard now (as direct links to the jobs). Will that do?

I'm trying to make these short enough to fit on one line ...

**Comment by mpolden** [comment]
My experience with deploying deployment orchestration proved that any sort of extensive debugging is very hard (if not impossible) without the build number. This may no longer be the case though.

> I'm trying to make these short enough to fit on one line

I understood that, but this seems like a futile way of controlling word wrapping. Your call :-)

**Comment by bratseth** [comment]
s/futile/pragmatic/  :-P

I'll merge, with the assumption that we can get what we need from the dashboard next time. If that is wrong you'll be able to blame me  :-)

**Pull request merged**
