### PR TITLE
Print message, avoid stack trace in log

### PR DESCRIPTION
**Pull request by hmusum**

### CODE REVIEW

**Comment by mpolden** [comment]
Another issue is that it seems to log way more often than the mentioned 10 minutes.

**Comment by hmusum** [comment]
It seems to log per deployment

**Comment by jonmv** [comment]
Yes, it may fail per deployment. Perhaps we should reduce the log level? 

Any ideas on how to fix the problem?

**Comment by bratseth** [comment]
> Any ideas on how to fix the problem?

Log once per iteration by setting a boolean if we already logged and resetting it at the start of the method.

Ideally we should also only remove the stack trace when we know it is a timeout.

**Comment by jonmv** [comment]
Ah, I meant the problem of connections timing out :) I'll try to dig down and see what the problem is.

**Pull request merged**
