### PR TITLE
Require all up when going up, but require all down to go down.

### PR DESCRIPTION
**Pull request by baldersheim**
@bratseth PR
@hmusum @yngveaasheim FYI

### CODE REVIEW

**Comment by baldersheim** [comment]
Let us hold this one until #12030 and #12031 has been rolled out.

**Review by bratseth — APPROVED** [review]
👍 this is still very easy to understand

**Comment by baldersheim** [comment]
Do I sense some irony ? :)

**Comment by bratseth** [comment]
No :-) I think this part really is very explicit and nice to understand, and it's an area where it really should be.

**Pull request merged**
