### PR TITLE
Temporary set owner of splunkforwarder log

### PR DESCRIPTION
**Pull request by freva**
We do this in `start-services.sh`, but unfortunately that change only exists in images after 7.4x, so we need to also do this in `node-admin` just before we start the container. Docker creates the directories on host that are to be mounted in the container (if missing) as part of start. So at this point, if this is the first this time container is started, the directory will not exist.

### CODE REVIEW

**Review by hakonhall — APPROVED** [review]

**Comment by freva** [comment]
I think we need to use `vespaUseOnHost` for this...

**Comment by hakonhall** [comment]
Sounds right

**Review by bjormel — CHANGES_REQUESTED** [review]
Can we do this on `/opt/splunkforwarder/var` instead?
I checked on a vespa-6.330.51 docker instance using `/opt/splunkforwarder/var/log` And we still get problems as the splunkforwarder is generating several directories inside `/opt/splunkforwarder/var`

**Comment by hakonhall** [comment]
Perhaps we should set the sticky bit?

**Comment by freva** [comment]
`/opt/splunkforwarder/var` wont work with this approach, since the directly that is mounted is `/opt/splunkforwarder/var/log`.

We would either have to mount `/opt/splunkforwarder/var` or execute `chown` inside the container.

**Comment by bjormel** [comment]
So then we will have to use a Task to address this.

**Pull request closed without merging**
