### PR TITLE
Remove BatchDocumentUpdateMessage and BatchDocumentUpdateReply

### PR DESCRIPTION
**Pull request by toregge**
from C++ portion of documentapi.
Remove corresponding document api cross language files.
Remove corresponding storageapi messages.

@vekterli: please review
@geirst, @gjoranv, @baldersheim: FYI

### CODE REVIEW

**Review by vekterli — APPROVED** [review]
:+1:

**Comment by toregge** [comment]
@vekterli: PTAL

**Review by vekterli — APPROVED** [review]
:+1:

**Review by vekterli — APPROVED** [review]
👌

**Pull request merged**
