### PR TITLE
Upgrade questdb

### PR DESCRIPTION
**Pull request by hmusum**
Upgrade to a version that supports JDK 17

One unit test fails (`QuestMetricsDbTest.testGc()`), looks like a regression in 6.2 release, but haven't looked into it. @bratseth could you have a look?

### CODE REVIEW

**Comment by bratseth** [comment]
Yes, I'll look at it.

**Comment by bratseth** [comment]
Confirmed, I raised this with QuestDb: https://github.com/questdb/questdb/issues/1846

**Comment by hmusum** [comment]
@bratseth please take a look, unit tests should work now

**Comment by bratseth** [comment]
👍  I just did this too :-)

**Pull request merged**
