### PR TITLE
Give the libvespamallocXXX back their old names.

### PR DESCRIPTION
**Pull request by baldersheim**
@aressem PR

### CODE REVIEW

**Comment by baldersheim** [comment]
This also reapplies the 2 earlier reverted pull requests

**Comment by baldersheim** [comment]
Hold while I update some more places.

**Comment by baldersheim** [comment]
Now, it should be ready to go.

**Comment by baldersheim** [comment]
I will let factory have a go.

**Comment by aressem** [comment]
👍

**Pull request merged**
