### PR TITLE
Bjorncs/use ssl socket factory node admin

### PR DESCRIPTION
**Pull request by bjorncs**
We'll have to wait with the merge until next prod release.

### CODE REVIEW

**Comment by hakonhall** [comment]
What has changed since last PR?

**Comment by bjorncs** [comment]
@hakonhall Nothing. It contains the changes from the 3 commits reverted in #6589.

**Comment by hakonhall** [comment]
So why would merging the same changes not cause the same problem? What was the problem?

**Comment by bjorncs** [comment]
Because of mismatch between the version of vespa-athenz bundle and node-admin in CD. New version of node-admin tried to use a class that did not exist in the old version of vespa-athenz.

**Review by hakonhall — APPROVED** [review]

**Pull request merged**
