### PR TITLE
Use top-sort and a DAG to express deps and parallelism

### PR DESCRIPTION
**Pull request by jonmv**
@mpolden what do you think?

### CODE REVIEW

**Comment by jonmv** [comment]
Well, this isn't quite right, as the `deploy` used in the `allMatch` may deploy things it shouldn't, yet. Convergence and deployment would need to be split. That wouldn't be a bad thing, anyway, though.

**Comment by freva** [comment]
`SystemApplications .all()` should just return the list sorted, then we also wont have to check if application has converged multiple times (once for itself, and once for any application that "depends" on it).

**Comment by jonmv** [comment]
Depends on whether you view the applications as batched (a list of lists is fine) or as a more general dependency graph (a DAG is required). 

If you want to avoid redundant HTTP traffic, a proper top-sort would do that :)

I think I should write some util-code :p

**Comment by mpolden** [comment]
LGTM. Will this merge into the other PR? Exciting. 🙂

**Pull request merged**
