### PR TITLE
add oath CNAMES for global rotations

### PR DESCRIPTION
**Pull request by andreer**
@jonmv, can you think of any additional changes required in this repo?

Labeled "DO NOT MERGE" because it should probably be merged at the same time as PR in other repo

### CODE REVIEW

**Comment by jonmv** [comment]
LGTM!

**Comment by jonmv** [comment]
Failing test, though.

**Comment by andreer** [comment]
Ah, missed updating a test there.

**Comment by andreer** [comment]
Added to Vespa >= 6.240.3

**Pull request merged**
