### PR TITLE
Reapply "Remove unnecessary component" [run-systemtest]"

### PR DESCRIPTION
**Pull request by hmusum**
Reverts vespa-engine/vespa#16003

Please review only

### CODE REVIEW

**Comment by hakonhall** [comment]
#16003 was merged because it fixed CD, so why do you want to revert that?

**Review by jonmv — APPROVED** [review]

**Comment by hmusum** [comment]
I thought the issue in CD was caused by https://github.com/vespa-engine/vespa/pull/15979, which was merged yesterday, but I think you are right in that this change does not work. Need to look more into it

**Comment by hakonhall** [comment]
CD passed before #15987 was merged today, but broke with it.  I observed some of the same errors in the log from yesterday, perhaps due to #15924, and which may have failed some proxy nodes.

**Comment by hmusum** [comment]
Found an issue where a component was using another host registry than elsewhere

**Comment by jonmv** [comment]
Heh. Sneaky.

**Review by hakonhall — APPROVED** [review]

**Review by hakonhall — APPROVED** [review]
Interesting - I have been waiting for this kind of issue with the global component.

**Pull request merged**
