### PR TITLE
Clear Slobrok entries after shutdown

### PR DESCRIPTION
**Pull request by hakonhall**

### CODE REVIEW

**Comment by arnej27959** [comment]
i think you should also set updates=0
@havardpe this is your code i guess, can you take a look?

**Comment by havardpe** [comment]
according to the javadoc, 'updates' does not need to be reset, but maybe we should update the shutdown method doc, indicating that all entries will be discarded (Using the Mirror after shutdown will have worse side-effects now than before)

**Comment by havardpe** [comment]
about the lookup method:

for (Entry specEntry : specs) {

Are we guaranteed that this loop construct will touch specs exactly once, even when it is a native array?

**Comment by hakonhall** [comment]
I'm thinking that's implicit in a 'shutdown' method? It's shut-down, so how can there be entries? If ppl MAY think entries should survive shutdown, I should probably not make this change.

**Comment by havardpe** [comment]
I think it should be ok to discard the entries during shutdown, probably even better in some cases where the Mirror is used after shutdown.

However, I also think someone MAY expect them to still be there, hence the (github) comment about being explicit in the (javadoc) comment.

**Comment by hakonhall** [comment]
OK, javadoc updated.

**Comment by havardpe** [comment]
👍

**Pull request merged**
