### PR TITLE
Warn instead of failing on validation errors in manual zones

### PR DESCRIPTION
**Pull request by bratseth**
The purpose of validation overrides is to protect production from
destructive changes by requiring a confirmation for such changes.
This is unnecessary in manuall deployed environments.

### CODE REVIEW

**Comment by hmusum** [comment]
Seems like we can remove `ValidationOverrides.AllowAllValidationOverrides` and the code in `DeployState` which uses `AllowAllValidationOverrides` for manually deployed zones with this?

**Comment by bratseth** [comment]
Aha! I vaguely recalled we were supposed to have this but couldn't find it where I expected. This one is fine, so just closing then.

**Comment by hmusum** [comment]
I like this way of doing it much better, though, exactly because it's impossible to find the code that does this (or understand that something like this is actually happening) with the way it is done today.

**Comment by bratseth** [comment]
Fair point. Let me look at it once more ...

**Comment by bratseth** [comment]
Now I've removed (step 1 of 2) the old way of doing it.

**Review by hmusum — APPROVED** [review]
💯

**Review by hmusum — APPROVED** [review]

**Pull request merged**
