### PR TITLE
Bratseth/mixed tensor json format

### PR DESCRIPTION
**Pull request by bratseth**

### CODE REVIEW

**Comment by bratseth** [comment]
@geirst fyi

**Comment by bratseth** [comment]
And @jobergum

**Comment by bratseth** [comment]
This adds support for a short form for mixed tensors:

`{"blocks":[{"address":{"x":"0"},"values":[2.0,3.0,4.0]},{"address":{"x":"1"},"values":[5.0,6.0,7.0]}]}
`

and using an object short form when there is a single sparse dimension:

`{"blocks":{"0":[2.0,3.0,4.0],"1":[5.0,6.0,7.0]}}
`

The latter also works with sparse tensors, i.e "cells".

**Review by lesters — APPROVED** [review]
LGTM

**Pull request merged**
