### PR TITLE
Interns/magnus/documentation java

### PR DESCRIPTION
**Pull request by Mangern**
Move documentation fetching (for hover) from Python to Java. It now runs on the client in the background when the language server starts.
Documentation fetching is still tested during build

### CODE REVIEW

**Comment by Mangern** [comment]
We had to add some dependencies to the vespa-dependencies-enforcer, not sure if it is the correct way.

**Review by theodorklauritzen — DISMISSED** [review]
This should cover the whole python script 👍

**Review by tokle — DISMISSED** [review]
👍

**Review by theodorklauritzen — APPROVED** [review]
LGTM

**Pull request merged**
