### PR TITLE
Build for 17

### PR DESCRIPTION
**Pull request by gjoranv**
NOTE: this is for 8 only

Build, unit test and javadoc should work for 17 now, verified in docker centos-stream8. However, a couple of unit tests fail consistently both on master+jdk11 and 8+17.

 Build command:
```
mvn clean install -T 1C -Dtest='!ConfigServerRestExecutorImplTest,!CertificateAuthorityApiTest' -DfailIfNoTests=false -Dsurefire.failIfNoSpecifiedTests=false
```

### CODE REVIEW

**Review by hmusum — APPROVED** [review]

**Comment by gjoranv** [comment]
This had to be forcefully removed, as I forgot to "rebase and merge". It's been too long since 6->7.

**Comment by hakonhall** [comment]
Out of curiosity - why do you specify `-DfailIfNoTests=false -Dsurefire.failIfNoSpecifiedTests=false` ?

**Review by bjorncs — COMMENTED** [review]
👍

**Comment by gjoranv** [comment]
@hakonhall, because the build fails otherwise. When excluding test classes, I have previously only used `-DfailIfNoTests=false`, but using maven 3.8 and release 17, maven told me to add the latter option. Perhaps the first one isn't necessary anymore. I haven't tried without it.

**Pull request merged**
