### PR TITLE
wire in spec-based tensor conformance testing

### PR DESCRIPTION
**Pull request by havardpe**
verify conformance spec generation
verify C++ default expression evaluation
bonus: verify binary format test spec generation

@lesters please review

### CODE REVIEW

**Comment by lesters** [comment]
PR build failed on this:

```
The following tests FAILED:
	 87 - eval_tensor_tensor_conformance_test_app (Failed)
Errors while running CTest
```

**Comment by havardpe** [comment]
it passes for me. seems to be problematic saving stuff to disk in the current directory inside the build container when running the test. need to discuss with @bjorncs

**Comment by havardpe** [comment]
turns out I made a bad since I tried to reference the binary from within the source tree and not the build tree... fix coming soon

**Comment by havardpe** [comment]
build passes now. please have another look

**Comment by lesters** [comment]
LGTM. 👍

**Pull request merged**
