### PR TITLE
No need to create a temporary execution, that is discarded right afte…

### PR DESCRIPTION
**Pull request by baldersheim**
…rwards.

The execution creates and empty context with a single threaded executor. That is not free.

@bratseth or @bjorncs

### CODE REVIEW

**Review by bratseth — COMMENTED** [review]
Yes, but now the API this can't guarantee it is not returning a null execution. I'll try to fix it without the cost somehow ...

**Comment by baldersheim** [comment]
What about using the InThreadExecutorService ? That has no other cost than the object.

**Comment by bratseth** [comment]
Yes, I did that first (or really just Runnable::run), but some tests hung. I'll look into it more.

**Review by bjorncs — COMMENTED** [review]
👍

**Pull request merged**
