### PR TITLE
Make it possible to configure dotproduct distance metric.

### PR DESCRIPTION
**Pull request by geirst**
@toregge please review
@arnej27959 FYI

### CODE REVIEW

**Review by arnej27959 — APPROVED** [review]
👍

**Review by toregge — APPROVED** [review]
👍

**Comment by toregge** [comment]
Note that `tests/search/config_definitions_not_changing/configdefs-md5.txt` in system test repo needs to be updated
when this PR is merged.

**Comment by geirst** [comment]
System test updated in https://github.com/vespa-engine/system-test/pull/2837

**Pull request merged**
