### PR TITLE
Support node admin modes

### PR DESCRIPTION
**Pull request by hakonhall**

### CODE REVIEW

**Comment by hakonhall** [comment]
This is mostly PR 4489 (3rd try), but I avoid renaming the component to avoid touching hosted.  This PR has been verified on a tenant Docker host and on a config server Docker host.

**Comment by hakonhall** [comment]
Harald is OOO

**Comment by hakonhall** [comment]
Note that this PR is based on the already reviewed PR 4489, which had to be reverted.

**Comment by smorgrav** [comment]
👍

**Pull request merged**
