### PR TITLE
Reduce maximum idleTimeout for a connection to 30 sec

### PR DESCRIPTION
**Pull request by bjormel**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by baldersheim — APPROVED** [review]

**Comment by bjorncs** [comment]
This changes idle timeout globally for everyone. Perhaps we should only do this for 4443 connector on hosted.

**Comment by bjormel** [comment]
@bjorncs can you make a suggestion on how to do this, and revert this PR?

**Comment by bjorncs** [comment]
@bjormel https://github.com/vespa-engine/vespa/blob/master/config-model/src/main/java/com/yahoo/vespa/model/container/http/ssl/HostedSslConnectorFactory.java#L91

**Comment by bjormel** [comment]
You are my hero  @bjorncs 🥇

**Pull request merged**
