### PR TITLE
Add vespa-maven-plugin to the aggregator maven-plugins 

### PR DESCRIPTION
**Pull request by jonmv**
@hakonhall please review.

### CODE REVIEW

**Review by hakonhall — APPROVED** [review]

**Comment by jonmv** [comment]
Does it work to comment?

**Comment by jonmv** [comment]
Mergestop enforcer hello?

**Comment by jonmv** [comment]
Didn't think so :)

**Comment by jonmv** [comment]
Ah, so the branch still existed.

**Pull request merged**
