### PR TITLE
Clear any existing empty latestVersions

### PR DESCRIPTION
**Pull request by jonmv**
@mpolden please review and merge.

### CODE REVIEW

**Comment by jonmv** [comment]
First part of commit message was already covered by someone else, presumably you :)

**Comment by jonmv** [comment]
Or ... do the changes in #12024 work?

**Comment by mpolden** [comment]
#12024 doesn't do this, no. In the affected system we fixed this manually in ZooKeeper (only one application).

**Comment by jonmv** [comment]
Then this is not needed.

**Pull request closed without merging**
