### PR TITLE
Fix storage maintainer

### PR DESCRIPTION
**Pull request by freva**
A few changes to simplify/fix `StorageMaintainer`.
I removed the exception throw if `stderr` is present from `du`, I've only see it crash when a file was suddenly deleted while it was traversing, which shouldn't matter for total directory size.

---
Note the `BYTES_IN_GB` which is used to convert the flavor spec disk size to bytes which we get from `du` command both for metrics and when to clean disk (80% full), @bjormel sent me an interesting note today:
```
In software, the kilobyte equals 1024 bytes, which is 2 to the power of 10. The megabyte (1024 KB) is then equal to 1,048,576 bytes, and the gigabyte is 1,073,741,824 bytes.

On the other hand, hardware vendors (specifically a hard drive vendors) use decimal scale, in which 1 gigabyte equals 1,000,000,000 bytes.
```
So maybe we should redefine it from 2^30 to 10^3? I'm not even sure we have enough disk to assume two-powers. Thoughts? @yngveaasheim / @hmusum

### CODE REVIEW

**Review by hmusum — APPROVED** [review]

**Comment by hmusum** [comment]
I think we should use 10^3 if the disk sizes we have in VespaFlavor are defined such that 1 Gb is 1,000,000,000 bytes (which I guess they are, but we should verify)

**Comment by yngveaasheim** [comment]
I don't completely follow the math; I guess you want 10^9 rather than 10^3 ?

**Comment by freva** [comment]
@yngveaasheim Yes, mixed up between the incremental change for each prefix (10^3) and total in giga (10^9).

**Comment by hmusum** [comment]
Change to use ten powers for size LGTM

**Pull request merged**
