### PR TITLE
Separate the processing.Processors into a minimal set and the rest. O…

### PR DESCRIPTION
**Pull request by baldersheim**
…nly use the minimal set when generating the concrete document types.
@bratseth PR

### CODE REVIEW

**Comment by baldersheim** [comment]
@gv PR

**Comment by baldersheim** [comment]
@hmusum PR

**Review by hmusum — APPROVED** [review]
LGTM

**Comment by hmusum** [comment]
@aressem FYI this fixes a regression in 6.286, we should make sure this is included in the 6.287 release.

**Comment by aressem** [comment]
👍

**Pull request merged**
