### PR TITLE
Avoid parsing proxied content

### PR DESCRIPTION
**Pull request by mpolden**
Slime apparently barfs on some strange JSON coming from StatusPage. Fails
integration test.

or @jonmv

### CODE REVIEW

**Comment by bratseth** [comment]
It will have to be parsed eventually - won't this just move the problem to the client side?

**Comment by bratseth** [comment]
I think we should know why ...

**Comment by mpolden** [comment]
Sure.

The JSON from StatusPage contains e.g. `\u0026`, Unicode for ampersand. It seems Slime doesn't like escaped Unicode:
```
String json = "{\"body\":\"some text\\u0026more text\"}";
System.out.println(new String(SlimeUtils.toJsonBytes(SlimeUtils.jsonToSlime(json.getBytes()))));

{"partial_result":{"body":"some text\u0000u"},"offending_input":"0x7B22626F6479223A22736F6D6520746578745C75","error_message":"invalid hex character"}
```

However, jq, Python, Jackson and browsers handles this fine:
```
$ echo '{"body":"some text\u0026more text"}' | jq .
{
  "body": "some text&more text"
}

$ python3
>>> import json
>>> json.loads('{"body":"some text\u0026more text"}')
{'body': 'some text&more text'}
```

So I think this can be merged, at least until Slime can be fixed.

**Comment by bratseth** [comment]
Thanks! Could you make a ticket on this and also point to this PR ... I think it would be preferable to not pass this as bytes.

**Comment by mpolden** [comment]
Of course. This wasn't meant as a permanent thing.

**Comment by bratseth** [comment]
I did't get that.

**Pull request merged**
