### PR TITLE
Prefer 'Host' header when constructing uri builder

### PR DESCRIPTION
**Pull request by bjorncs**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by jonmv** [comment]
This feels iffy. It indicates we've somehow set the wrong URI when creating the request, after receiving it from Jetty. I suspect that's not the case, but that this rather has to do with test code? Can't we fix that code instead, if this is the case?

**Comment by jonmv** [comment]
I mean, the URI we have set for the request should be based on the Host header. The URI we've created has been validated, and we ignore that by jumping back to the Host header here. This is possibly OK right now, but ...

**Comment by bjorncs** [comment]
The URI contains the local listen port (for uri matching purposes), while the uri builder is intended for constructing URIs that are part of the response (like interactive rest APIs). The uri builder is not used for routing, in that case I would agree with you.

**Comment by jonmv** [comment]
Hmm ... so the host header will still be wrong when the request is served from behind a proxy? We have several of these responses where we rewrite the response across each proxy. This is horrible. Perhaps a dedicated header with a response-host-port-override could solve this in a much better way? That would also be suitable for this ...

**Review by jonmv — APPROVED** [review]
Approved, but let's consider a more thorough solution?

**Comment by jonmv** [comment]
Perhaps make it more clear that this is the intended use, btw..

**Comment by bjorncs** [comment]
We have multiple layer 4 load balancers where port exposed from load balancer and local listen port differs. E.g controllers in public.

**Comment by jonmv** [comment]
> We have multiple layer 4 load balancers where port exposed from load balancer and local listen port differs. E.g controllers in public.

Yes, which warrants a dedicated override for creating responses, something like:
1. if `X-Original-Host-Port` header is set, use its value; or
2. if `Host` header is set, use its value; or
3. use value from request. 

If used throughout, this would let us kill all response rewriting.

**Comment by jonmv** [comment]
(Then we could set the `X`-header when proxying.

**Comment by bjorncs** [comment]
We can add support for https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host.

**Comment by jonmv** [comment]
That's a perfect fit!

**Review by jonmv — APPROVED** [review]
Nicee

**Pull request merged**
