### PR TITLE
Revert "Retry WebApplicationExceptions as well"

### PR DESCRIPTION
**Pull request by hakonhall**
Reverts vespa-engine/vespa#8116

409 Conflicts should not be retried, in general. I will have to double-check whether this is in fact a problem - I suspect it is for the Orchestrator --> Cluster Controller

### CODE REVIEW

**Comment by hakonhall** [comment]
FYI @jonmv @freva

**Comment by jonmv** [comment]
Think that was already retried. Hang on.

**Comment by jonmv** [comment]
No, you're right. That is a WebApplicationException. Could add just the ServiceUnavailableException to the catch clause, I guess.

**Comment by jonmv** [comment]
https://github.com/vespa-engine/vespa/pull/8118 instead

**Comment by hakonhall** [comment]
A timeout in the cluster controller returns 500 which should not cause a retry.

Off he top of my head I think it may make sense to retry under certain other circumstances, or not since it will anyway be retried in next tick.

WebApplicationException is caught higher in the stack in StorageNodeImpl,
https://github.com/vespa-engine/vespa/blob/master/orchestrator/src/main/java/com/yahoo/vespa/orchestrator/model/StorageNodeImpl.java#L81

Please revert.

**Comment by hakonhall** [comment]
Ah, you already did

**Pull request closed without merging**
