### PR TITLE
use greatCircleDistance to compute distance(foo).km

### PR DESCRIPTION
**Pull request by arnej27959**
@geirst please review
@andreer FYI

### CODE REVIEW

**Review by geirst — APPROVED** [review]
👍

**Comment by andreer** [comment]
Improvement for new use cases, but a change in behaviour - something we should bring up for arch review on Thursday?

**Comment by bratseth** [comment]
Isn't this just that it used to give wrong numbers at long ranges and with this it doesn't?

**Comment by andreer** [comment]
Yes, we could consider this a bugfix. In theory someone could have a ranking calculation or something that depends on it but seems pretty unlikely.

**Pull request merged**
