### PR TITLE
GC unused ancient api

### PR DESCRIPTION
**Pull request by baldersheim**
@havardpe @arnej27959 PR

### CODE REVIEW

**Review by havardpe — COMMENTED** [review]
was the old code inside the test?

**Comment by baldersheim** [comment]
Yes.

**Comment by arnej27959** [comment]
if we remove the test we should also remove the implementation afterwards.  i can do that in a separate PR.

**Comment by baldersheim** [comment]
The MirrorOld class was in the test directory. Is there something more to be removed ?
Server side implementation ?

**Pull request merged**
