### PR TITLE
Do not start cluster monitor thread in test as it will race with expl…

### PR DESCRIPTION
**Pull request by baldersheim**
…icit ping in test.

@mpolden or @bratseth PR

### CODE REVIEW

**Review by bratseth — COMMENTED** [review]
There's a lot of possible states with all these fields that may be initialized or not. I think we may simplify a bit by not creating the ClusterMonitor before the startClusterMonitoring method is called (it's initialized there anyway so not usable before).

Then we can also move the pingfactory into the clustermonitor and pass it in the constructor. Perhaps also the nodes?

Then we could perhaps also let the clustermonitor be passed in instead of the pingfactory and the boolean, such that it would be up to the caller to start it or not etc. (Not quite sure about this one).

**Comment by baldersheim** [comment]
@bratseth Now you can have another look.

**Review by bratseth — APPROVED** [review]
Great

**Comment by mpolden** [comment]
👍

**Pull request merged**
