### PR TITLE
Revert "Revert "Bratseth/select 1 host by index""

### PR DESCRIPTION
**Pull request by bratseth**
Reverts vespa-engine/vespa#4265 @hmusum 

Merge after the missing double config update bug is fixed.

### CODE REVIEW

**Review by hmusum — DISMISSED** [review]
Some system tests failed when the original PR was merged, needs to be looked into first

**Comment by bratseth** [comment]
Thanks, these failed: 
resize.rb: shrink, grow, hd_shrink
uselocalnode.rb: uselocalnode

**Comment by bratseth** [comment]
@hmusum  or @baldersheim is the double config update bug completely fixed by https://github.com/vespa-engine/vespa/pull/4257 ?

**Comment by hmusum** [comment]
Looks like we need to revert https://github.com/vespa-engine/vespa/pull/4257, many system tests are failing

**Pull request merged**
