### PR TITLE
Revert "Revert "Revert "Revert "Unify on hc5"""" [run-systemtest]

### PR DESCRIPTION
**Pull request by baldersheim**
Reverts vespa-engine/vespa#17327

### CODE REVIEW

**Comment by baldersheim** [comment]
@jonmv or @bjorncs PR

**Comment by jonmv** [comment]
Isn't the problem this: ```
[21:34:36.193] Exception in thread "main" java.lang.IllegalArgumentException: Scheme must be 'http' when using HttpToHttpsRoutePlanner
[21:34:36.193] 	at ai.vespa.util.http.hc5.HttpToHttpsRoutePlanner.determineRoute(HttpToHttpsRoutePlanner.java:24)
[21:34:36.193] 	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
[21:34:36.193] 	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:169)
[21:34:36.193] 	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
[21:34:36.193] 	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:200)
[21:34:36.193] 	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:143)
[21:34:36.193] 	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:117)
[21:34:36.193] 	at com.yahoo.vespa.config.ConfigVerification.performRequest(ConfigVerification.java:95)
[21:34:36.193] 	at com.yahoo.vespa.config.ConfigVerification.performRequests(ConfigVerification.java:65)
[21:34:36.193] 	at com.yahoo.vespa.config.ConfigVerification.compareConfigs(ConfigVerification.java:76)
[21:34:36.193] 	at com.yahoo.vespa.config.ConfigVerification.main(ConfigVerification.java:42)```

**Comment by baldersheim** [comment]
Yes, but at least it works running locally.

**Comment by jonmv** [comment]
Hmm, is that method called multiple times, by the client implementation? Seems like it's always `http` from the user.

**Comment by jonmv** [comment]
Can probably just remove that check from the route rewriter.

**Review by bjorncs — APPROVED** [review]

**Pull request merged**
