### PR TITLE
Add XGBoost converter

### PR DESCRIPTION
**Pull request by grace-lam**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Review by bratseth — APPROVED** [review]
Great work

**Comment by bjorncs** [comment]
FYI @gjoranv

**Comment by baldersheim** [comment]
@bjorncs or @bratseth PR
@gv FYI
The scope change in the pom.xml causes incorrect versions to be pulled in. With runtime linkage errors.

Caught fatal error during rendering.
                                                                                                                                                                                                                                                    exception=
                                                                                                                                                                                                                                                    java.lang.LinkageError: loader constraint violation: when resolving method "com.yahoo.document.json.JsonWriter.<init>(Lcom/fasterxml/jackson/core/JsonGenerator;)V" the class loader (instance of org/apache/felix/framework/BundleWiringImpl$BundleClassLoader) of the current class, com/yahoo/search/rendering/JsonRenderer$FieldConsumer, and the class loader (instance of org/apache/felix/framework/BundleWiringImpl$BundleClassLoader) for the method's defining class, com/yahoo/document/json/JsonWriter, have different Class objects for the type com/fasterxml/jackson/core/JsonGenerator used in the signature
                                                                                                                                                                                                                                                    \tat com.yahoo.search.rendering.JsonRenderer$FieldConsumer.renderFieldContents(JsonRenderer.java:794)
                                                                                                                                                                                                                                                    \tat com.yahoo.search.rendering.JsonRenderer$FieldConsumer.accept(JsonRenderer.java:708)
                                                                                                                                                                                                                                                    \tat com.yahoo.search.rendering.JsonRenderer$FieldConsumer.accept(JsonRenderer.java:668)
                                                                                                                                                                                                                                                    \tat java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
                                                                                                                                                                                                                                                    \tat com.yahoo.search.result.Hit.forEachFieldAsRaw(Hit.java:423)
                                                                                                                                                                                                                                                    \tat com.yahoo.search.rendering.JsonRenderer.renderStandardFields(JsonRenderer.java:501)
                                                                                                                                                                                                                                                    \tat com.yahoo.search.rendering.JsonRenderer.renderAllFields(JsonRenderer.java:496)
                                                                                                                                                                                                                                                    \tat com.yahoo.search.rendering.JsonRenderer.renderHitContents(JsonRenderer.java:490)
                                                                                                                                                                                                                                                    \tat com.yahoo.search.rendering.JsonRenderer.renderHit(JsonRenderer.java:461)
                                                                                                                                                                                                                                                    \tat com.yahoo.search.rendering.JsonRenderer.data(JsonRenderer.java:580)
                                                                                                                                                                                                                                                    \tat com.yahoo.processing.rendering.AsynchronousSectionedRenderer$DataListListener.renderDataList(AsynchronousSectionedRenderer.java:423)
                                                                                                                                                                                                                                                    \tat com.yahoo.processing.rendering.AsynchronousSectionedRenderer$DataListListener.renderData(AsynchronousSectionedRenderer.java:395)
                                                                                                                                                                                                                                                    \tat com.yahoo.processing.rendering.AsynchronousSectionedRenderer$DataListListener.render(AsynchronousSectionedRenderer.java:354)
                                                                                                                                                                                                                                                    \tat com.yahoo.processing.rendering.AsynchronousSectionedRenderer$RendererListener.run(AsynchronousSectionedRenderer.java:525)
                                                                                                                                                                                                                                                    \tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                                                                                                                                                                                                                                                    \tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                                                                                                                                                                                                                                    \tat java.lang.Thread.run(Thread.java:748)

**Comment by baldersheim** [comment]
@bratseth and @bjorncs This was not possible to revert as there has been changes building on this one. Please unchain or fix root cause.

**Comment by bratseth** [comment]
https://github.com/vespa-engine/vespa/pull/6594

**Comment by MJPIPER99** [comment]
I request a READER 4 the new Android.

**Pull request merged**
