### PR TITLE
Revert "Change default value of zookeeperLocalhostAffinity to true"

### PR DESCRIPTION
**Pull request by hmusum**
Reverts vespa-engine/vespa#4755

### CODE REVIEW

**Comment by hakonhall** [comment]
why?

**Comment by hmusum** [comment]
`[2018-01-23 20:50:14.786] ERROR   : container        Container.com.yahoo.container.jdisc.ConfiguredApplication
	Reconfiguration failed, your application package must be fixed, unless this is a JNI reload issue: key not found: name=config-server,namespace=vespa.hosted.node.admin.config,configId=node-admin/component/node-admin
	exception=
	java.util.NoSuchElementException: key not found: name=config-server,namespace=vespa.hosted.node.admin.config,configId=node-admin/component/node-admin`

**Comment by hakonhall** [comment]
You're discussing the reason node-admin stuff was reverted. I think we're just setting the config at the wrong level, I'll take a look.

But why "Change default value of zookeeperLocalhostAffinity to true" reverted? (this PR)

**Comment by hmusum** [comment]
Yes, sorry, this PR broke unit tests in zkfacade. See https://github.com/vespa-engine/vespa/pull/4759

**Pull request merged**
