### PR TITLE
Revert "Invalidate node object cache based on znode version"

### PR DESCRIPTION
**Pull request by jonmv**
Reverts vespa-engine/vespa#20840

I remember now why this doesn't work, and why I didn't to this for the node repo: state for one node is kept across multiple paths.

### CODE REVIEW

**Comment by jonmv** [comment]
@mpolden

**Comment by jonmv** [comment]
Or perhaps that's not exactly it ... but it's more complicated here, anyway.

**Comment by jonmv** [comment]
I believe the problem is the interaction between reading live stats, and cached objects? 

Say a snapshot is taken, where node `a` is `reserved`. Then `a` is moved to `active`. Any users of the old snapshot may then be unable to find `a`, as failure to find it could be cached in `active`, and when they try to read it from `reserved`, the stat is gone?

**Review by freva — APPROVED** [review]

**Comment by bratseth** [comment]
Another good reason to stop storing nodes in different paths depending on their state.

**Pull request merged**
