### PR TITLE
Balder/move sequenced task executors to staging vespalib

### PR DESCRIPTION
**Pull request by baldersheim**
@havardpe PR

### CODE REVIEW

**Review by havardpe — APPROVED** [review]
We might need to replace the optimize_for config abstraction with something that chooses implementation rather than goal and also lets us specify additional parameters.

**Comment by havardpe** [comment]
@geirst should also have a say. Are we moving too much to vespalib/util?

**Comment by baldersheim** [comment]
Better granularity is coming soon.
I would suggest that we move executor related stuff from util till a separate vespalib/execute or similar module. That is a separate step.

**Comment by geirst** [comment]
Moving executor related code to a separate sub-library sounds good.

**Pull request merged**
