### PR TITLE
Make providers lazy

### PR DESCRIPTION
**Pull request by bratseth**
@gjoranv how about this? I don't think we need to eagerly make the providers construct their component.

Cc @hmusum

### CODE REVIEW

**Comment by gjoranv** [comment]
It's neatly done, and it resolves the linguistics issue. But it breaks the use-case of setting up a provider for a component that does not have any dependents. I'm sure we and/or tenants have such components for various purposes, that may or may not be set up via a provider. It could e.g. update some external entity (file or via http). As long as it's allowed to set up an ordinary component of that sort, I think it must also be possible to do that via a provider. The most common difference between them is that the provider based component uses a system resource, e.g. a thread. If you have a component that updates something outside the component graph, it's quite likely that it does so periodically.

I think the underlying problem is that we always and implicitly set up components that are not needed by the application from the config-model. In the linguistics case, we can easily prevent setting it up for apps that don't have search or docproc. This will not solve the case of search apps that set up another linguistics implementation in addition to the provided one. One possible solution is to add custom services.xml syntax for linguistics, instead of using a generic `component`.

**Comment by bratseth** [comment]
Components need to be constructed even if nothing depends on them. What you are saying is that therefore, providers also need to construct their component even if nothing depends on it.

That doesn't sound right to me. Providers provide default implementations in case no component is explicitly declared. Therefore, I think it is wrong for them to construct the component when nothing needs it. Are there other use cases for providers?

**Comment by gjoranv** [comment]
"Providers provide default implementations"
That was something we quite recently invented for linguistics. The _main cases_ for using a provider are
1. need for releasing system resources or other teardown
2. need for custom rules for creation, e.g. a new instance for each get()

As I said in my previous comment, there shouldn't be a completely different semantics just because your component needs to release some system resource.

Don't you agree that the problem you are trying to solve here is really a model problem?

Anyway, if we really want to change the semantics for providers, we can't do that until the next major release.

**Comment by bratseth** [comment]
I agree this is (also) a model problem.

1: Components support teardown though, but I agree somebody could in theory do this.
2: I can't imagine a scenario where it is desirable to modify the di construction rules like this, since it only gives partial control. Perhaps not something we should encourage, but in any case not a problem here I think.

The doc of Provider does not specify that get is always called, and the third use case described (the default fallback) seems to imply that it will not. And doesn't this also?: "If (and only if) dependency injection does not have a component of type T, it will request one from the Provider providing type T"?
So, arguably we could change this, but I'd want to review what's out there first.

**Comment by gjoranv** [comment]
True, you could just as well use AbstractComponent instead of Provider if you just need teardown. So, in practice it's only the more obscure cases that will no longer be supported. Still, I think it's risky to change the provider semantics in a minor release.

**Comment by bratseth** [comment]
I sampled usages of this and couldn't find any which would be troubled by this. I also realized it would be quite unlikely: It would only cause problems for Providers which go through the trouble of lazily (but thread safely) instantiating in get, but relying on *not* being called lazily.

**Comment by gjoranv** [comment]
As mentioned earlier, one of the main cases for providers is where you can't use the constructor. It could for example be a 3rd party class that has a factory method instead of a public constructor.  It's possible to overcome this as well, by wrapping it in your own AbstractComponent, so there should be a fix in all cases I can think of in case anyone gets hit. 

I suggest to add a test to verify and demonstrate the behaviour in ComponentGraphTest.

**Comment by bratseth** [comment]
Yes, I'll try to add a test. This change in behavior didn't break any tests unfortunately ...

**Pull request merged**
