### PR TITLE
Java 9: Truncate Instants from Instant.now() to MILLIS

### PR DESCRIPTION
**Pull request by gjoranv**
- JDK 9 has higher resolution for Instant.now() than JDK 1.8, while
  instants deserialized from slime only has ms resolution.

### CODE REVIEW

**Comment by jonmv** [comment]
Cleaner to just truncate the now() at line 100, though?

**Comment by gjoranv** [comment]
Agreed, done. I did both sides because I thought it was safer, but probably not an issue. PTAL and merge if green.

**Review by jonmv — APPROVED** [review]
Perfect :)

**Comment by jonmv** [comment]
Will merge after stop.

**Pull request merged**
