### PR TITLE
Bundle-plugin: Scala code converted to Java

### PR DESCRIPTION
**Pull request by ollivir**

### CODE REVIEW

**Review by bjorncs — APPROVED** [review]

**Comment by bjorncs** [comment]
FYI @gjoranv

**Comment by bjorncs** [comment]
@ollivir: Add yourself to OWNERS file. You know this module better than anyone else now :)

**Comment by gjoranv** [comment]
I think we should discuss the use of `if (predicate == false)` compared to `if (! predicate)` before merging.

**Comment by ollivir** [comment]
Personally I find `(condition == false)` more visible than `(! condition)` and as such less likely to miss. You could argue that `(false == condition)` would be safer, but somehow that feels wrong(?). I'm not fanatic about that issue, so there's a consensus that it's just overkill and annoying in IDEA, I'm open to using negation.

**Pull request merged**
