### PR TITLE
GC no longer used useReconfigurableDispatcher and adminClusterArchite…

### PR DESCRIPTION
**Pull request by baldersheim**
…cture

@jonmv and @hmusum PR

### CODE REVIEW

**Review by hmusum — CHANGES_REQUESTED** [review]
adminClusterArchitecture is still in use and cannot be removed (the "removeAfter" annotation should be removed as well).

**Comment by jonmv** [comment]
The admin architecture _flag_ is in use, but just directly—not through model.

**Review by jonmv — DISMISSED** [review]

**Comment by baldersheim** [comment]
@hmusum PTAL

**Comment by jonmv** [comment]
Either that, or wire it through the model so it follows Vespa version ... if that was the intention?

**Comment by baldersheim** [comment]
Then we wait with admin architecture flag and take that separately.
PTAL

**Review by hmusum — APPROVED** [review]
@jonmv you are right, `adminClusterArchitecture` is not used through the model, I was fooled by IntelliJ not showing the method in ModelContextImpl as unused. I'll take care of removing it in another PR

**Pull request merged**
