### PR TITLE
Use NodeAdminBaseConfig

### PR DESCRIPTION
**Pull request by freva**
Logstash nodes will still come from environment, but from what I understand, this is going away soon anyway?
Other than that, Environment only used to store some resolvers, so maybe it can be removed entirely

### CODE REVIEW

**Comment by hakonhall** [comment]
How about making NodeAdminBaseConfig a private field of Environment, or copy values from NABC to the fields of Environment? This way Node Admin still operates on Environment which is more flexible that passing around various parts of a config.

**Comment by freva** [comment]
@hakonhall Updated, PTAL.

This makes a pretty small PR, but it I think it would be nicer long-term if we had smaller configs that could be passed to the different components, and those configs only had fields that the component required.

**Comment by hakonhall** [comment]
Discussed offline. Will remove zone and coredump url from config.

**Comment by freva** [comment]
@hakonhall PTAL.

**Review by hakonhall — APPROVED** [review]

**Pull request merged**
