### PR TITLE
Use ZTS getAccess instead of ZMS

### PR DESCRIPTION
**Pull request by tokle**

### CODE REVIEW

**Review by bjorncs — APPROVED** [review]

**Review by hmusum — CHANGES_REQUESTED** [review]
Great! But there are some unit tests failing that need to be fixed

**Comment by tokle** [comment]
@hmusum / @bjorncs ptal

**Review by hmusum — APPROVED** [review]
Great!

**Review by jonmv — COMMENTED** [review]
👍

**Pull request merged**
