### PR TITLE
Keep files and directories in vespa home when installing Vespa

### PR DESCRIPTION
**Pull request by hakonhall**
In %pre of vespa.spec (pre-installation), the vespa home directory is installed
with .bashrc, necessary for e.g. 'docker exec -it NAME bash' to pick up
/etc/profile.d/*.sh environment settings.

It is therefore important to avoid deletion of vespa home, as was done in %install
before installing Vespa to vespa home.

### CODE REVIEW

**Review by jonmv — APPROVED** [review]
Why was this done previously?

**Review by freva — COMMENTED** [review]
As long as it doesn't cause conflict with the `cp` 2 lines under, LGTM.

**Comment by hakonhall** [comment]
I discussed this with @aressem: it was not done for any specific reason - presumably to be sure the installation directory was not polluted with an earlier installation. But builds on copr are clean (no earlier installation), and our centos build is also clean.

**Comment by hakonhall** [comment]
@freva good point on that - it will be wrong for `cp`, let me fix.

**Review by jonmv — APPROVED** [review]
Hehe, even better! Who would have though it possible?!

**Comment by hakonhall** [comment]
Replaced by https://github.com/vespa-engine/vespa/pull/10377

**Pull request closed without merging**
