### PR TITLE
Remove support for vespa http client protocol v2.  Always use protocol v3.

### PR DESCRIPTION
**Pull request by toregge**
@geirst: please review

### CODE REVIEW

**Review by geirst — APPROVED** [review]
👍

**Comment by geirst** [comment]
@bratseth FYI

**Review by vekterli — APPROVED** [review]
:+1:

**Review by bratseth — APPROVED** [review]

**Comment by bratseth** [comment]
Why u no merge?

**Comment by geirst** [comment]
@bjorncs FYI

**Pull request merged**
