### PR TITLE
Extend flag lifetime.

### PR DESCRIPTION
**Pull request by baldersheim**
@hmusum or @vekterli PR

### CODE REVIEW

**Review by hmusum — APPROVED** [review]
If RESPONSE_SEQUENCER_TYPE is a permant flag it could be moved toPermanentFlags

**Comment by baldersheim** [comment]
Not permanent, but there are a set of flags related to feeding that we will be experimenting with probably then a 6-12 months.

**Comment by hmusum** [comment]
👍

**Review by vekterli — COMMENTED** [review]
:+1:

**Pull request merged**
