### PR TITLE
Revert to single-threaded update of metrics

### PR DESCRIPTION
**Pull request by mpolden**
The implementation of `MetricsService` doesn't seem to handle multiple threads well, need to look into it. Revert to single thread temporarily.

### CODE REVIEW

**Review by jonmv — APPROVED** [review]
Could be my fault, for already using parallelStream in DeploymentTrigger, also on IO.

**Comment by jonmv** [comment]
I guess we should use dedicated Executors for these blocking calls, if we want to parallelise :)

**Comment by jonmv** [comment]
Argh, misclick.

**Comment by mpolden** [comment]
Yes, suspected something that. Will change it.

**Pull request merged**
