### PR TITLE
Jvenstad/generify and fix deployment issue reporter

### PR DESCRIPTION
**Pull request by jonmv**
@bratseth does this look OK? 

The plan is to replace Issues, Contacts and Properties with this — perhaps with a different name — and move those three to our Oath-specific repo, to be used by an implementation of this. 

I would like to have this merged, so I can program against it in the Oath-specific repo — or perhaps you know a simpler way of doing cross-repo compilation?

### CODE REVIEW

**Comment by bratseth** [comment]
Looks good to me, although I don't really condone carbonism.

Fyi, if you mvn install on your machine your local repo will be updated and you can use those changes from the other repo. Feel free to merge though.

**Comment by jonmv** [comment]
Do suggest a proper name :]

**Comment by bratseth** [comment]
How about "Issues"?

**Comment by jonmv** [comment]
I was saving "Issues" for the JIRA interface.

**Comment by bratseth** [comment]
That's what I was expecting, not sure we need 2 layers?

**Comment by jonmv** [comment]
Well, this interface is very controller-specific; as long as we only use JIRA for failing deployments, I guess it's fine, but if we some day want to use it for other things, we should separate out (and add more specifics to) the JIRA interface, I think.

**Comment by jonmv** [comment]
@mpolden please review :]

**Comment by jonmv** [comment]
Ended up with a proper wrapping of our internal integration databases (OpsDB and JIRA) in the Organization interface. This one will be useful for the dashboard, as well — or at least, that was the idea.

**Comment by jonmv** [comment]
Must be merged with https://git.corp.yahoo.com/vespa/hosted/pull/4871

**Comment by jonmv** [comment]
Replaced by https://github.com/vespa-engine/vespa/pull/3873/

**Pull request closed without merging**
