### PR TITLE
Add includes needed for linking of attribute test.

### PR DESCRIPTION
**Pull request by toregge**
@baldersheim : please review

### CODE REVIEW

**Comment by toregge** [comment]
Linker errors on Darwin without the changes in this PR applied:
```
[100%] Linking CXX executable searchlib_attribute_test_app
Undefined symbols for architecture x86_64:
  "search::MultiValueAttribute<search::EnumAttribute<search::StringAttribute>, vespalib::datastore::AtomicEntryRef>::onShrinkLidSpace()", referenced from:
      vtable for search::MyMultiValueAttribute in attribute_test.cpp.o
  "search::MultiValueAttribute<search::EnumAttribute<search::StringAttribute>, vespalib::datastore::AtomicEntryRef>::addDoc(unsigned int&)", referenced from:
      vtable for search::MyMultiValueAttribute in attribute_test.cpp.o
  "search::MultiValueAttribute<search::EnumAttribute<search::StringAttribute>, vespalib::datastore::AtomicEntryRef>::clearDocs(unsigned int, unsigned int, bool)", referenced from:
      vtable for search::MyMultiValueAttribute in attribute_test.cpp.o
  "search::MultiValueAttribute<search::EnumAttribute<search::StringAttribute>, vespalib::datastore::AtomicEntryRef>::onAddDocs(unsigned int)", referenced from:
      vtable for search::MyMultiValueAttribute in attribute_test.cpp.o
  "search::MultiValueEnumAttribute<search::EnumAttribute<search::StringAttribute>, vespalib::datastore::AtomicEntryRef>::fillValues(search::NoLoadedVector&)", referenced from:
      vtable for search::MyMultiValueAttribute in attribute_test.cpp.o
```

**Comment by baldersheim** [comment]
Why would this be an issue here, these are symbols that should be present in libsearchlib as they are part of a multivalue string attribute ?

**Comment by toregge** [comment]
The symbols are present but not public:
```
$ nm -C ../../vespa/searchlib/libsearchlib.dylib  | grep onShrinkLidSpace | grep StringAttribute 
000000000007c170 t search::MultiValueAttribute<search::EnumAttribute<search::StringAttribute>, vespalib::datastore::AtomicEntryRef>::onShrinkLidSpace()
000000000007c170 t search::MultiValueAttribute<search::EnumAttribute<search::StringAttribute>, search::multivalue::WeightedValue<vespalib::datastore::AtomicEntryRef> >::onShrinkLidSpace()
000000000024efd0 T search::SingleValueEnumAttribute<search::EnumAttribute<search::StringAttribute> >::onShrinkLidSpace()
```

**Comment by baldersheim** [comment]
This is how it looks with gcc 12.
00000000005a77f0 W search::MultiValueAttribute<search::EnumAttribute<search::StringAttribute>, vespalib::datastore::AtomicEntryRef>::onShrinkLidSpace()

Let us discuss tomorrow.

**Pull request closed without merging**
