### PR TITLE
Tag cpu category on service layer threads

### PR DESCRIPTION
**Pull request by geirst**
@vekterli please review
@baldersheim @havardpe FYI

### CODE REVIEW

**Review by havardpe — COMMENTED** [review]
I think std::nullopt is better than {} for empty optionals

**Comment by havardpe** [comment]
An alternative to optional cpu usage would be to use OTHER as the fallback. This will have a small additional overhead only in the cases where no cpu usage is ever tagged in the thread (~10ns per 5s, paid by the metrics hook thread).

**Comment by geirst** [comment]
> I think std::nullopt is better than {} for empty optionals

Fixed.

**Review by vekterli — APPROVED** [review]
:+1: TIL `std::nullopt` is a thing

**Pull request merged**
