### PR TITLE
allow newer onnx runtime

### PR DESCRIPTION
**Pull request by havardpe**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

@aressem please review

### CODE REVIEW

**Comment by havardpe** [comment]
@arnej27959 FYI

**Comment by toregge** [comment]
This might trigger issues with older version of vespa needing libonnxruntime.so.1.4.0
while libonnxruntime.so.1.7.1 is installed instead. The library version is encoded in the
run time link dependy (cf. `objdump -p vespa-proton-bin  | grep libonnx`).

**Comment by havardpe** [comment]
so, it is better to just bump directly to exactly 1.7.1 and allow some temporary breakage?
(the plan was to update spec references, then update to 1.7.1, then update references again, possibly with = instead of >=...)

**Comment by toregge** [comment]
Yes. We have a similar issue with protobuf version.

**Pull request closed without merging**
