### PR TITLE
Enable full linting with errors. Use SuppressWarning explicit where n…

### PR DESCRIPTION
**Pull request by baldersheim**
…eeded

@hmusum or @bjorncs PR
Contains the safe parts of #30836

### CODE REVIEW

**Review by hmusum — APPROVED** [review]

**Review by hmusum — CHANGES_REQUESTED** [review]
Some compilation errors: 

16:51:15 [ERROR] /sd/workspace/src/github.com/vespa-engine/vespa/document/src/main/java/com/yahoo/document/datatypes/Array.java:[392,39] incompatible types: java.lang.Object cannot be converted to E
16:51:15 [ERROR] /sd/workspace/src/github.com/vespa-engine/vespa/document/src/main/java/com/yahoo/document/datatypes/Array.java:[409,46] incompatible types: java.lang.Object cannot be converted to E
16:51:15 [ERROR] /sd/workspace/src/github.com/vespa-engine/vespa/document/src/main/java/com/yahoo/document/datatypes/Array.java:[416,45] incompatible types: java.lang.Object cannot be converted to E
16:51:15 [ERROR] /sd/workspace/src/github.com/vespa-engine/vespa/document/src/main/java/com/yahoo/document/datatypes/Array.java:[443,50] incompatible types: java.lang.Object cannot be converted to E
16:51:15 [ERROR] /sd/workspace/src/github.com/vespa-engine/vespa/document/src/main/java/com/yahoo/document/datatypes/Array.java:[448,39] incompatible types: java.lang.Object cannot be converted to E
16:51:15 [ERROR] /sd/workspace/src/github.com/vespa-engine/vespa/document/src/main/java/com/yahoo/document/datatypes/Array.java:[501,34] incompatible types: java.lang.Object cannot be converted to E
16:51:15 [ERROR] /sd/workspace/src/github.com/vespa-engine/vespa/document/src/main/java/com/yahoo/document/datatypes/Array.java:[505,34] incompatible types: java.lang.Object cannot be converted to E
16:51:15 [ERROR] /sd/workspace/src/github.com/vespa-engine/vespa/document/src/main/java/com/yahoo/document/datatypes/Array.java:[521,33] java.lang.Object cannot be safely cast to com.yahoo.document.datatypes.Array<T>.ListWrapper<E>

**Comment by baldersheim** [comment]
Indeed, accident due to cleaning branch first. Fixed.

**Review by hmusum — DISMISSED** [review]

**Review by bjorncs — CHANGES_REQUESTED** [review]
```
20:31:01 [INFO] -------------------------------------------------------------
20:31:01 [WARNING] COMPILATION WARNING : 
20:31:01 [INFO] -------------------------------------------------------------
20:31:01 [WARNING] Cannot find annotation method 'value()' in type 'edu.umd.cs.findbugs.annotations.SuppressFBWarnings': class file for edu.umd.cs.findbugs.annotations.SuppressFBWarnings not found
20:31:01 [WARNING] Cannot find annotation method 'justification()' in type 'edu.umd.cs.findbugs.annotations.SuppressFBWarnings'
20:31:01 [INFO] 2 warnings 
20:31:01 [INFO] -------------------------------------------------------------
20:31:01 [INFO] -------------------------------------------------------------
20:31:01 [ERROR] COMPILATION ERROR : 
20:31:01 [INFO] -------------------------------------------------------------
20:31:01 [ERROR] warnings found and -Werror specified
20:31:01 [INFO] 1 error
20:31:01 [INFO] -------------------------------------------------------------
```

**Comment by baldersheim** [comment]
@bjorncs Fixed

**Review by hmusum — APPROVED** [review]

**Review by bjorncs — APPROVED** [review]

**Pull request merged**
