### PR TITLE
More generic error response exception

### PR DESCRIPTION
**Pull request by jonmv**
@bjorncs please review.

### CODE REVIEW

**Comment by jonmv** [comment]
Or @hakonhall 
The idea is that users of this interface will defined their own error handling, and wrap calls to this client in helper code that sets a default error response mapper, where applicable.

**Review by bjorncs — APPROVED** [review]

**Comment by jonmv** [comment]
Hmm, there are some missing building blocks here, though.

**Review by hakonhall — APPROVED** [review]

**Comment by jonmv** [comment]
Please take a new look. I think this is better. Gives separation between the different concerns, at the cost of being able to return normally from an IOException, which I think is a niche use case anyway.

**Review by hakonhall — APPROVED** [review]

**Comment by jonmv** [comment]
New PR ready, but may as well merge this, as most of these changes are still live ;)

**Pull request merged**
