### PR TITLE
Fail deployment of standalone services.xml in hosted if cluster controllers are specified [run-systemtest]

### PR DESCRIPTION
**Pull request by hmusum**
@oyving please review

### CODE REVIEW

**Comment by hmusum** [comment]
ping @oyving

**Comment by hakonhall** [comment]
It's a feature that developers can take a self-hosted application and deploy it to the dev environment.  @bratseth made this argument when it came to the node count and redundancy.  Perhaps we should allow cluster-controller element in dev too?

**Comment by bratseth** [comment]
Yes, I think we should allow it in dev.

**Comment by hmusum** [comment]
Right, I'll make a new PR where we allow this and make sure it works.

**Pull request closed without merging**
