### PR TITLE
Expose change blockers in application API

### PR DESCRIPTION
**Pull request by mpolden**
This adds a "changeBlockers" field to the application
API (`/application/v4/tenant/tenant1/application/application1`).

### CODE REVIEW

**Comment by mpolden** [comment]
I see #5084 was already created. Do we only want to display "is it blocked now"? Or list all known block windows?

**Comment by bratseth** [comment]
Imho just displaying if it is blocked now is sufficient, I don't think this is worth spending too much effort on ...

**Comment by frodelu** [comment]
@bratseth / @mpolden : Could we discuss on Wednesday? The additional information available here (over #5084) would allow us to answer part two of the "why is this not deploying" question, i.e. "when can we expect it to deploy".

**Comment by mpolden** [comment]
Yes, I think knowing when the window opens up again is useful. Reopening until we conclude.

**Comment by bratseth** [comment]
I'm in Warzaw ... anyway, not against adding more info, it's just more effort than I was prepared to spend, but no point in discussing that when the effort is in the past.

**Comment by mpolden** [comment]
Merge?

**Pull request merged**
