### PR TITLE
Forbid applications without a container cluster in hosted Vespa

### PR DESCRIPTION
**Pull request by jonmv**
@bratseth

### CODE REVIEW

**Review by bratseth — COMMENTED** [review]
👍  but i think we should validate this for self-hosted too

**Review by bratseth — COMMENTED** [review]
Rename validator too I guess ...

**Review by bratseth — DISMISSED** [review]

**Comment by jonmv** [comment]
Hehe yes ... :)

**Comment by jonmv** [comment]
Hmm, this causes lots of other unit tests to fail, though :)

**Pull request closed without merging**
