### PR TITLE
Improve exception message

### PR DESCRIPTION
**Pull request by hmusum**

### CODE REVIEW

**Comment by gjoranv** [comment]
Where did you see this message? I'm not sure "conflicting" is the correct term. It doesn't make sense to set it manually, so I think 'nonsense' is better. Anyway, maybe we should instead say something like " has set its config id manually, which does not make sense."

**Comment by hmusum** [comment]
This was code that did `super(ComponentId.fromString("foo´")`, but had `<component id="bar" ...>`in services.xml. Since the component ids must be equal (it's nothing wrong with the name, as "bogus" hinted at) I think we should say that. Your suggested message sounds fine to me

**Comment by gjoranv** [comment]
@hmusum, please take a look at my suggestion.

**Review by hmusum — COMMENTED** [review]
👍

**Pull request merged**
