### PR TITLE
Revert 7487 revert 7482 balder/obey timeout too

### PR DESCRIPTION
**Pull request by hmusum**

### CODE REVIEW

**Comment by hmusum** [comment]
There are several classes in vespaclient-container-plugin that need to follow API changes in SingleSender, build fails due to this now

**Comment by hmusum** [comment]
ping @baldersheim

**Comment by baldersheim** [comment]
I want to hold this one a bit. I suspect that definition of timeout is inconsistent at feeding.
I need to figure that out until we merge this one again.

**Comment by hmusum** [comment]
Really old, I guess it is not relevant anymore, closing

**Pull request closed without merging**
