### PR TITLE
Convert record to class, since we need to build this for JDK 8

### PR DESCRIPTION
**Pull request by jonmv**
@bratseth

### CODE REVIEW

**Review by freva — APPROVED** [review]

**Comment by baldersheim** [comment]
Why ?
I thought we stopped building this for jdk8 on vespa 7.
And should never ever do that again.
They should use last client built based on vespa  7.

**Comment by jonmv** [comment]
Hmm ... Perhaps it's not quite the reason, but:

```
Request failed: /document/v1/storage_test/music/number/1234/0
exception=
java.util.concurrent.CompletionException: java.lang.ClassFormatError: Weaving hook failed.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1498)
	at java.base/java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1219)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at com.yahoo.jdisc.http.server.jetty.ServletOutputStreamWriter.setFinished(ServletOutputStreamWriter.java:183)
	at com.yahoo.jdisc.http.server.jetty.ServletOutputStreamWriter.writeBuffersInQueueToOutputStream(ServletOutputStreamWriter.java:160)
	at com.yahoo.jdisc.http.server.jetty.ServletOutputStreamWriter$1.onWritePossible(ServletOutputStreamWriter.java:261)
	at org.eclipse.jetty.server.HttpOutput.run(HttpOutput.java:1541)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1525)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:600)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassFormatError: Weaving hook failed.
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.transformClass(BundleWiringImpl.java:2391)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2069)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1550)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1970)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.yahoo.document.json.readers.VespaJsonDocumentReader.createDocumentOperation(VespaJsonDocumentReader.java:81)
	at com.yahoo.document.json.JsonReader.readSingleDocument(JsonReader.java:75)
	at com.yahoo.document.restapi.resource.DocumentV1ApiHandler$DocumentOperationParser.parse(DocumentV1ApiHandler.java:1044)
	at com.yahoo.document.restapi.resource.DocumentV1ApiHandler$DocumentOperationParser.parsePut(DocumentV1ApiHandler.java:1036)
	at com.yahoo.document.restapi.resource.DocumentV1ApiHandler.lambda$postDocument$21(DocumentV1ApiHandler.java:459)
	at com.yahoo.document.restapi.resource.DocumentV1ApiHandler$Operation.dispatch(DocumentV1ApiHandler.java:941)
	at com.yahoo.document.restapi.resource.DocumentV1ApiHandler.dispatchFirst(DocumentV1ApiHandler.java:559)
	at com.yahoo.document.restapi.resource.DocumentV1ApiHandler.enqueueAndDispatch(DocumentV1ApiHandler.java:601)
	at com.yahoo.document.restapi.resource.DocumentV1ApiHandler.lambda$postDocument$22(DocumentV1ApiHandler.java:458)
	at com.yahoo.document.restapi.resource.DocumentV1ApiHandler$ForwardingContentChannel.close(DocumentV1ApiHandler.java:1010)
	at com.yahoo.jdisc.http.server.jetty.ReferenceCountingRequestHandler$ReferenceCountingContentChannel.close(ReferenceCountingRequestHandler.java:176)
	at com.yahoo.jdisc.http.server.jetty.ServletRequestReader.closeRequestContentChannel(ServletRequestReader.java:251)
	at com.yahoo.jdisc.http.server.jetty.ServletRequestReader.doneReading(ServletRequestReader.java:234)
	at com.yahoo.jdisc.http.server.jetty.ServletRequestReader$Listener.onAllDataRead(ServletRequestReader.java:179)
	at org.eclipse.jetty.server.HttpInput.run(HttpInput.java:968)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1525)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:590)
	... 16 more
Caused by: java.lang.UnsupportedOperationException: Records requires ASM8
	at com.yahoo.vespa.spifly.repackaged.asm.ClassVisitor.visit(ClassVisitor.java:111)
	at com.yahoo.vespa.spifly.repackaged.asm.ClassReader.accept(ClassReader.java:569)
	at com.yahoo.vespa.spifly.repackaged.asm.ClassReader.accept(ClassReader.java:424)
	at com.yahoo.vespa.spifly.repackaged.spifly.dynamic.ClientWeavingHook.weave(ClientWeavingHook.java:60)
	at org.apache.felix.framework.util.SecureAction.invokeWeavingHook(SecureAction.java:1408)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.transformClass(BundleWiringImpl.java:2377)
	... 38 more
```
Perhaps @bjorncs or @gjoranv is able to explain this more precisely?

**Comment by jonmv** [comment]
Looking more closely, it looks rather like our felix doesn't support records?

**Comment by jonmv** [comment]
In any case, didn't we have to keep building something for JDK because of the grid? @bjorncs ? Or did you find a way around that?

**Comment by baldersheim** [comment]
I think that we need to wait with records due to some asm/spifly not ready for it yet.
@bjorncs and @gjoranv knows the details.

**Comment by jonmv** [comment]
Yes, it could be that we can't export them to other bundles, perhaps? We do use them a lot in some bundles, already, but all the usages I can think of off the top of my head are not exported.

**Comment by gjoranv** [comment]
This is spifly using old asm. This is only a problem in jetty, not with felix.

**Comment by bjorncs** [comment]
Tracked in https://issues.apache.org/jira/browse/ARIES-2080.

**Pull request merged**
