### PR TITLE
Start node-repository maintainers with fixed spacing

### PR DESCRIPTION
**Pull request by freva**
Basically the same as #7467, but for node-repository `Maintainer`

### CODE REVIEW

**Review by jonmv — APPROVED** [review]
... assuming localhost is found in the curator cluster :)

**Comment by freva** [comment]
@jonmv Should be fine, this is how a configserver finds its zookeeper ID https://github.com/vespa-engine/vespa/blob/6cf7e45914d4f02cd3e41ecd26ac0201098ce788/config-model/src/main/java/com/yahoo/vespa/model/container/configserver/ConfigserverCluster.java#L56

And even if that fails, it will result it current behavior.

**Review by mpolden — APPROVED** [review]
LGTM, but why is it needed?

**Comment by freva** [comment]
Things will happen faster without consuming any extra resources. 

For example, I often see convergence checker saying that "Zone upgrade has not yet started" even though I know that the target version has been set. The `InfrastructureProvisioner` interval is 3 minutes, with this change we should be guaranteed that version will be propagated within 1 minute.

This is even more important for maintainers with longer period. I guess maintainers with interval ~15 minutes (~time it takes to upgrade 1 cfg) will run on all 3 config servers within just a few minutes of each other and then nothing will happen for 10 minutes.

**Pull request merged**
