### PR TITLE
Wire in mallopt(in param, int value) interface in vespamalloc and ver…

### PR DESCRIPTION
**Pull request by baldersheim**
…ify simple wiring.

@vekterli @havardpe @toregge  PR

### CODE REVIEW

**Review by toregge — APPROVED** [review]

**Review by vekterli — APPROVED** [review]
:+1: Nice, I didn't know `M_MMAP_THRESHOLD` was an existing thing

**Comment by havardpe** [comment]
Are we planning to be able to revert back to a previously set value? How will this work? Will settings be inherited when starting new threads?

**Comment by baldersheim** [comment]
It is thread local, so no effect on other threads for vespamalloc. Effect is implementation dependant for others.
Will also only be used if vespamalloc is used.

**Comment by baldersheim** [comment]
The usage is scoped.  See #21120 This is just adapting to an existing incomplete API.

**Pull request merged**
