### PR TITLE
Remove @PublicApi from package c.y.document.select

### PR DESCRIPTION
**Pull request by gjoranv**

### CODE REVIEW

**Review by geirst — APPROVED** [review]
👍

**Comment by vekterli** [comment]
A bit late to the party, but are we sure no one is actually using document selectors as part of custom logic? I.e. do we expect the only usage of selections to be opaque strings passed down to the backend?

**Comment by bratseth** [comment]
This is not breaking anything since it is still exported. 
I agree we should have a programmatic API for this, not sure if this is a good one though. Why are we changing this?

**Comment by gjoranv** [comment]
This came up because someone suggested to rename Result.INVALID to UNKNOWN. I searched git.ouroath for usage and found none for the whole package. Then there was consensus (or so I thought) to set it non-public so we could change/improve what we want. Feel free to revert.

**Comment by bratseth** [comment]
I'm fine with that (our contract holds for external users too ... but it doesn't really forbid making this change). We can do this, make sure the API is good and then publish at some later point.

**Pull request merged**
