### PR TITLE
Enable ABI checking on modules with public APIs

### PR DESCRIPTION
**Pull request by lonemeow**

### CODE REVIEW

**Comment by lonemeow** [comment]
Requested review from all relevant module owners, please do a quick sanity check on the relevant `abi-spec.json` file(s).

**Review by bratseth — APPROVED** [review]
I did some spot checking - it looks right to me.

**Comment by hmusum** [comment]
LGTM

**Review by hmusum — APPROVED** [review]

**Review by lesters — APPROVED** [review]
:+1:

**Comment by gjoranv** [comment]
Great, but I suggest to move the plugin configuration to the `pluginManagement` of `parent/pom.xml`, and just declare the plugins in the child modules that use it:
```
      <plugin>
        <groupId>com.yahoo.vespa</groupId>
        <artifactId>abi-check-plugin</artifactId>
    </plugin>
```

**Review by havardpe — APPROVED** [review]

**Review by baldersheim — APPROVED** [review]

**Review by gjoranv — DISMISSED** [review]
Please move the plugin configuration to the pluginManagement of parent/pom.xml, ensuring we use the same config for all modules. In the child modules, just declare the plugin like so, and they will inherit the config.

    <plugin>
        <groupId>com.yahoo.vespa</groupId>
        <artifactId>abi-check-plugin</artifactId>
    </plugin>

**Review by freva — APPROVED** [review]

**Review by gjoranv — APPROVED** [review]
👍

**Review by geirst — APPROVED** [review]
👍

**Review by bjorncs — APPROVED** [review]

**Review by vekterli — APPROVED** [review]
:+1:

**Review by toregge — APPROVED** [review]

**Review by arnej27959 — APPROVED** [review]
👍

**Pull request merged**
