### PR TITLE
Prepare for making node admin components optional

### PR DESCRIPTION
**Pull request by hakonhall**

### CODE REVIEW

**Review by hmusum — APPROVED** [review]
Delete NodeAdminProvider too?

**Comment by hakonhall** [comment]
Right, I should have mentioned that. Unfortunately it's referenced from another repository, so I was thinking getting this out first and if OK, update reference in other and if OK remove here.

**Comment by hakonhall** [comment]
FYI @freva

**Comment by hmusum** [comment]
I see, no problem then

**Pull request merged**
