### PR TITLE
Revert "Write secret-agent config"

### PR DESCRIPTION
**Pull request by freva**
Reverts vespa-engine/vespa#5293

### CODE REVIEW

**Review by ldalves — APPROVED** [review]

**Comment by yngveaasheim** [comment]
Should this be merged now?

**Comment by freva** [comment]
If
```
1. Upgrade to stable version across hosted Vespa nodes
```
is done, then yes.

**Comment by yngveaasheim** [comment]
@freva right; I somehow thought that was implied by the request for the new config. We still need to confirm that.

**Comment by yngveaasheim** [comment]
@freva , @ldalves - I believe we are good to merge this one now; all remaining nodes on older versions of Vespa are either ghost nodes (nuwa) or BM nodes (mediasearch)

**Comment by yngveaasheim** [comment]
Of course, we have to wait for merge stop lifted first.

**Pull request merged**
