### PR TITLE
Add onnx output caching to embedder  (allow different post-processing of model outputs)

### PR DESCRIPTION
**Pull request by jobergum**
After https://github.com/vespa-engine/vespa/pull/30769 & https://github.com/vespa-engine/vespa/pull/30766 we can cache the output of a model inference and perform different post-processing depending on the tensor cell type and dimensionality. 

The primary use cases are:

- Dimension flexibility 🪆 using only the first k vector dimensions 
- Dimension precision flexibility - using binary quantization packing k floats into k/8 int8  
- Future native embedder implementations supporting models that emits both sparse, dense and mixed representations, e.g [M3](https://pyvespa.readthedocs.io/en/latest/examples/mother-of-all-embedding-models-cloud.html) 

```
field embedding type tensor<int8>(x[16]) {
  input | text | embed my-embedder-id | attribute
}

field embedding type tensor<float>(x[128]) {
  input | text | embed my-embedder-id | attribute
}
```

And per query request

```
rank-profile coarse-to-fine {
  inputs {
    query(q) tensor<float>(x[128])
    query(q_binary) tensor<int8>(x[16])
  }
}
```
Then the following should will be one inference call, but with different post processing
of the model output. 

```
input.query(q)=embed(my-embedder-id,"the text to embed")
input.query(q_binary)=embed(my-embedder-id,"the text to embed")
```

Without invoking the expensive model inference part twice, only the post-processing of the model changes. 

## Important assumptions 

The PR makes an important assumption that there is a single Context instance per embedder instance per request since it uses the input text string as they cache key. If this assumption is wrong then then it would break when inputting the same text contents to multiple embedder instances as the model outputs would not be compatible, leading to all kinds of issues. 

Also this is only a per request cache (not a cache across requests as discussed in https://github.com/vespa-engine/vespa/issues/27967) .

```
field embedding type tensor<float>(x[128]) {
  input | text | embed my-embedder-id
}

field embedding type tensor<float>(x[128]) {
  input | text | embed my-other-embedder-id
}
```

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by bjorncs — DISMISSED** [review]

**Comment by jobergum** [comment]
It looks like my assumption is wrong. The cache instance is owned by ExecutionContext so it's global and not unique per embedder id.

**Comment by bratseth** [comment]
Yes, it's shared for the duration of the processing of the document/update.
I suggest creating a CacheKey that contains both the value and the embedder id:

record EmbedderCacheKey(ComponentId embedderId, Object embeddedValue) { }

**Review by bratseth — COMMENTED** [review]
Otherwise, LGTM!

**Comment by bratseth** [comment]
I also think we shouldn't build the tensor input if it turns out we won't need it because we have a cached value. I'm working on a commit to add to this PR.

**Comment by bratseth** [comment]
@jobergum please take a look

**Review by bjorncs — DISMISSED** [review]

**Comment by jobergum** [comment]
Thanks @bratseth. I' will adapt the HF embedder as well to cache more of the compute and change the hash key from string to a record.

**Comment by bjorncs** [comment]
With any object allowed as key it's important that all types of the composite key do have a sensible `equals()`/`hashcode()` implementation.

**Review by bjorncs — APPROVED** [review]

**Comment by jobergum** [comment]
Updated performance test to use multiple embed calls, so need a couple of runs before merging https://github.com/vespa-engine/system-test/pull/3740

**Pull request merged**
