### PR TITLE
Handle failures when triggering individual jobs

### PR DESCRIPTION
**Pull request by jonmv**
@andreer

### CODE REVIEW

**Comment by jonmv** [comment]
or @hmusum or @mpolden or @freva please review.

**Review by hmusum — APPROVED** [review]

**Review by hmusum — CHANGES_REQUESTED** [review]
Need to update unit test

**Comment by jonmv** [comment]
Hmm, guess I messed up some renaming there at the end >_<

**Comment by jonmv** [comment]
Oh, it was the exception message ...

**Review by freva — APPROVED** [review]

**Review by hmusum — APPROVED** [review]

**Pull request merged**
