### PR TITLE
Install fat flags jar

### PR DESCRIPTION
**Pull request by hakonhall**

### CODE REVIEW

**Comment by hakonhall** [comment]
FYI @gjoranv @toregge

**Comment by aressem** [comment]
You will also need do add the flags directory as a subdirectory in the top level CMakeLists.txt.

**Comment by hakonhall** [comment]
Done

**Comment by hakonhall** [comment]
woops, saw the three green bullets and merged... but @toregge has verified the config server works with this PR.

**Comment by aressem** [comment]
👍

**Pull request merged**
