### PR TITLE
Provide service-monitor and application-model, try 2

### PR DESCRIPTION
**Pull request by hakonhall**
Reverts vespa-engine/vespa#3818

### CODE REVIEW

**Comment by hakonhall** [comment]
The first commit is a revert-revert of PR 3615.
The second adds fat jars to base installation.

**Comment by hakonhall** [comment]
FYI @gjoranv who approved the original PR.
@aressem has last touched the code this PR adds in the last commit.

**Comment by aressem** [comment]
👍

**Comment by gjoranv** [comment]
🤞

**Pull request merged**
