### PR TITLE
Lesters/log to deploylogger

### PR DESCRIPTION
**Pull request by lesters**
@bratseth Please review.

### CODE REVIEW

**Comment by bratseth** [comment]
@hmusum does it work to create a new BaseDeployLogger or do we have to pass the existing instance down?

**Comment by hmusum** [comment]
You need to pass the existing logger down

**Comment by lesters** [comment]
@bratseth Please take a look. Moved the warning to search definition processing because to deploy logger is readily available there.

**Comment by bratseth** [comment]
Great

**Pull request merged**
