### PR TITLE
Eliminate clang warnings in eval.

### PR DESCRIPTION
**Pull request by toregge**
@baldersheim : please review
@vekterli : FYI

### CODE REVIEW

**Review by baldersheim — COMMENTED** [review]
What is the warning ?
I guess it it should be a class or fast_type should be removed

**Comment by toregge** [comment]
[ 80%] Building CXX object eval/src/vespa/eval/tensor/dense/CMakeFiles/eval_tensor_dense.dir/mutable_dense_tensor_view.cpp.o
/home/tegge/git/vespa/eval/src/vespa/eval/tensor/dense/mutable_dense_tensor_view.cpp:24:23: error: field '_concreteType' is uninitialized when used here [-Werror,-Wuninitialized]
    : DenseTensorView(_concreteType.fast_type(), CellsRef()),
                      ^
/home/tegge/git/vespa/eval/src/vespa/eval/tensor/dense/mutable_dense_tensor_view.cpp:30:23: error: field '_concreteType' is uninitialized when used here [-Werror,-Wuninitialized]
    : DenseTensorView(_concreteType.fast_type(), cells_in),
                      ^
2 errors generated.
make[3]: *** [eval/src/vespa/eval/tensor/dense/CMakeFiles/eval_tensor_dense.dir/build.make:284: eval/src/vespa/eval/tensor/dense/CMakeFiles/eval_tensor_dense.dir/mutable_dense_tensor_view.cpp.o] Error 1

**Comment by baldersheim** [comment]
But this construction is not safe as _concreteType used before initialization.
Should you not use type_in directly instead ?

**Comment by toregge** [comment]
No. type_in can be an abstract tensor type, with unbound dimensions.

**Review by baldersheim — APPROVED** [review]
I see that DenseTensorView takes in a reference. That is why it is done like this I guess.
But I fail to see why _type is more valid than fast_type().
But it does not make it any worse.

**Comment by toregge** [comment]
_concreteType._type is modified as different documents are passed to the feature executor, thus DenseTensorView can see different concrete tensor types according to which document is being evaluated.

The least dirty fix is likely to use multiple inheritance, e.g. change MutableDenseTensorView to
inherit from MutableValueType and DenseTensorView, in that order.

**Pull request merged**
