### PR TITLE
Add runtime dependency to vespa-gtest.

### PR DESCRIPTION
**Pull request by toregge**
@aressem : please review

### CODE REVIEW

**Comment by toregge** [comment]
This is related to vespa-engine/vespa-3rdparty-deps#85

**Review by aressem — APPROVED** [review]

**Review by baldersheim — COMMENTED** [review]
Why does vespa need gtest as runtime dependency at all ?

**Comment by toregge** [comment]
vespa-tensor-instructions-benchmark is part of vespa and links with gtest.

**Comment by baldersheim** [comment]
Why is that part of runtime install ?
If is benchmarking it does not sound right to depend on gtest.
I noticed that it seemed to be used in a system test. If that is the only use it should be in a different package.

**Review by baldersheim — APPROVED** [review]
Since this PR does not introduce any dependency, approve. Fix root issue later on.

**Pull request merged**
