### PR TITLE
Produce new bucket spaces config for distributor nodes.

### PR DESCRIPTION
**Pull request by geirst**
This config contains all document types handled by a content cluster
and the bucket space each document type belongs to.

@vekterli and @toregge please review

### CODE REVIEW

**Review by vekterli — APPROVED** [review]
:+1:

**Comment by toregge** [comment]
Missing cmake glue to generate C++ code and install def file.

**Comment by geirst** [comment]
@toregge please review again

**Review by toregge — APPROVED** [review]
LGTM

**Pull request merged**
