### PR TITLE
GC unused yapache log and derivatives.

### PR DESCRIPTION
**Pull request by baldersheim**
@bratseth PR
@kkraune @jobergum @frodelu Scream if you think someone is using yapache log

### CODE REVIEW

**Comment by bratseth** [comment]
I'm finding a number of usages of this. Don't think we can do it.

**Comment by bratseth** [comment]
According to @baldersheim he checked and none of those are in use.

**Review by bratseth — APPROVED** [review]

**Comment by kkraune** [comment]
I found only PINT, which is not in prod yet, and could be legacy non-used, so OK with me - LGTM

**Comment by kkraune** [comment]
I will remove https://git.ouroath.com/pages/vespa/documentation/documentation/logging-in-yapache-format.html and references to it, then

**Review by kkraune — APPROVED** [review]

**Comment by baldersheim** [comment]
I found none in hosted.

**Comment by frodelu** [comment]
OK. Ideally, I'd argue this was a Vespa 8 thing (we cannot remove a log format mid major?), but since it's VZM/Oath/Yahoo internal and we cannot find the use, we should be OK.

Are we certain none of the grid/data highway stuff @lesters did once upon a time didn't use yapache access logs?

**Comment by lesters** [comment]
@frodelu Grid logging uses some yapache schemas to package payload, not dependent on anything here.

**Pull request merged**
