### PR TITLE
Bratseth/remove dead code

### PR DESCRIPTION
**Pull request by bratseth**
@lesters please review

Last bit of cleanup. "UnprocessingSearchBuilder" should run all the processors in reverse in my opinion ...

### CODE REVIEW

**Review by baldersheim — CHANGES_REQUESTED** [review]
There are test failures

**Comment by bratseth** [comment]
Thanks. These tests create temp files and don't clean up, so the run history may impact success or failure. Oh well ... I removed this test at least.

**Comment by bratseth** [comment]
Feel very free to approve now.

**Comment by lesters** [comment]
LGTM!

**Pull request merged**
