### PR TITLE
Bratseth/store provisioninfo without version

### PR DESCRIPTION
**Pull request by bratseth**
@hmusum please review

Well this got more complicated than expected.
I did not manage to make it very reviewable, here are the highlight:
- I renamed ProvisionInfo to AllocatedHosts so that the name actually means something.
To maintain compatibility there is a (logically) empty subclass ProvisionInfo for now.
- We now only store one AllocatedHosts instance, with no version in the path, as discussed.
- Bootstrap of this change: If there is no AllocatedHosts instance stored, I read all the versioned AllocatedHosts instances and merge them in the same way as happened earlier, at a later stage, when the AllocatedHosts were to be actually used -  see ZkApplicationPackage.importAllocatedHosts
- Instead of requesting allocations for each cluster (note, not service, but "cluster" in the sense of the node repository) for each model, I now only do it once per cluster and reuse those allocations for models built later and requesting the same cluster. We build models by descending version so this means that the newest model version requesting a cluster decides the size and state of nodes for that cluster, and all other model version then uses that information without having a say on their own, which is correct. Since we don't require all model versions to request the same clusters, this also means we can evolve the set of clusters requested by models without running into deadlocks in production. See SessionPrepared, PreparedModelsBuilder and StaticProvisioner.

Please think this over a bit before merging since I gave up creating unit tests for the detailed semantics above, and I guess this is only capable of giving us problems in production.

### CODE REVIEW

**Review by hmusum — APPROVED** [review]
Overall looks good and the changes to logic seem fine to me. I tried to follow code when adding or removing clusters and I cannot find any flaws. Bootstrapping also looks good.

That said, this is a big change and I wonder what we do if it fails...

**Comment by bratseth** [comment]
>  I wonder what we do if it fails...

I guess we'll have to downgrade the config servers then.

**Comment by bratseth** [comment]
Unless you have any ideas for how to safeguard this further with reasonable amount of work, I'll merge the next time we have green weather.

**Comment by hmusum** [comment]
No, sorry, I don't. We just have to try it out and see what happens

**Comment by bratseth** [comment]
Great. Merge?

**Pull request merged**
