### PR TITLE
Log at a lower level

### PR DESCRIPTION
**Pull request by hmusum**
Missed some log statements in https://github.com/vespa-engine/vespa/pull/12147

### CODE REVIEW

**Review by gjoranv — APPROVED** [review]
I generally recommend to use supplier syntax for debug messages to avoid string interpolation and other processing.
`log(LogLevel.DEBUG, () -> "message")`

**Comment by hmusum** [comment]
Agreed, and I forgot this time, fixed

**Review by baldersheim — APPROVED** [review]

**Comment by jonmv** [comment]
Seems this broken a system test.

**Comment by jonmv** [comment]
Made https://github.com/vespa-engine/system-test/pull/559 to remedy.

**Pull request merged**
