### PR TITLE
Add a BERT embedder

### PR DESCRIPTION
**Pull request by bratseth**

### CODE REVIEW

**Review by jobergum — COMMENTED** [review]
I think that we should use WordPieceEmbedder, we have SentencePieceEmbedder which also can be used for BERT models (e.g mBERT).

**Comment by bratseth** [comment]
Or BertWordPieceEmbedder since I think the "##" prefix is a BERT thing, long name though.
I guess I can just make that configurable and then it will be general enough to take the WordPiece name.

**Comment by jobergum** [comment]
I'm fine with BertWordPieceEmbedder

**Comment by bratseth** [comment]
PTAL @jobergum

**Review by jobergum — APPROVED** [review]

**Comment by jobergum** [comment]
Once this is in we need to have a sprint on fixing sample apps to use this instead :)

**Comment by bratseth** [comment]
Yes.

**Pull request merged**
