### PR TITLE
Queue all apps eligible for redeployment on each run

### PR DESCRIPTION
**Pull request by mpolden**

### CODE REVIEW

**Review by freva — APPROVED** [review]
Looks good, maybe relax the `PeriodicApplicationMaintainer` interval a little bit? Currently at 1 minute.

**Comment by mpolden** [comment]
> maybe relax the PeriodicApplicationMaintainer interval a little bit? Currently at 1 minute.

Not sure that's needed?  The interval just controls how often we check for and queue up eligible applications. There will still be minimum 30 minutes between deployments of an application.

**Comment by freva** [comment]
Its not needed, just no point in running it that often since the `maintain()` will iterate over several applications in `pendingDeployments` every time it is called, so making frequent changes to `pendingDeployments` is pointless as they wont be picked up until the current `maintain()` finishes and next one is called. If the `maintain()` takes more than 30 minutes, almost all applications will be in the `pendingDeployments` by the time `maintain()` is called again.

This also affects job control. If we just disable `PeriodicApplicationMaintainer`, it will keep on deploying all already scheduled applications before stopping.

**Comment by mpolden** [comment]
> maintain() will iterate over several applications in pendingDeployments every time it is called

`maintain()` doesn't iterate over `pendingDeployments`, the former is only used to ensure uniqueness of the queue in `deploymentExecutor` (the executor is backed by a `BlockingQueue`).

> If the maintain() takes more than 30 minutes, almost all applications will be in the pendingDeployments by the time maintain() is called again.

`maintain()` will never block for long periods as deployments are async in this maintainer. The whole idea is too fill the queue with unique applications as often as possible.

> it will keep on deploying all already scheduled applications before stopping

This behavior is true for all our maintainers.

**Review by freva — APPROVED** [review]

**Review by freva — APPROVED** [review]

**Comment by mpolden** [comment]
Test hangs on Travis for some reason. Checking.

**Pull request merged**
