### PR TITLE
Use config subscriber for slobroks config

### PR DESCRIPTION
**Pull request by hmusum**

### CODE REVIEW

**Review by baldersheim — APPROVED** [review]
Perhaps @gjoranv should have a look too.

**Comment by hmusum** [comment]
This needs more work, standalone-container and application do not work with these changes

**Comment by gjoranv** [comment]
What is the functional difference here?

**Comment by hmusum** [comment]
The change is to use a config subscribe, Register will then get new slobroks when config changes (if I understand the code correctly) and take care of registering container.

**Comment by hmusum** [comment]
@gjoranv please have a look

**Comment by gjoranv** [comment]
Is the purpose to avoid the container restart when slobroksConfig changes?

**Comment by hmusum** [comment]
The purpose is to make sure that container is registered in slobrok when slobroks move (e.g. when retiring a node with slobrok on it).

**Comment by gjoranv** [comment]
Yes, and that is now handled by the container restarting and reading the slobroks config again. This is the same for QrConfig, but while QrConfig requires internal changes in the container, the slobroksConfig is only used internally in ´ConfiguredApplication`. Therefore, I assume it's safe to _not_ restart the container when slobroksConfig changes.

If you agree, I suggest to add a comment in the "slobroks area" of in the class header.

**Review by gjoranv — APPROVED** [review]

**Comment by gjoranv** [comment]
👍

**Pull request merged**
