### PR TITLE
benchmark type detection

### PR DESCRIPTION
**Pull request by havardpe**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

type_index seems to be a hidden gem

@arnej27959 please review

### CODE REVIEW

**Review by arnej27959 — APPROVED** [review]
👍

**Comment by havardpe** [comment]
```
[dynamic_cast] cost is 20.20 ns (true 17.67, false 24.02, baseline  0.65)
  [type_index] cost is  0.27 ns (true  0.95, false  0.88, baseline  0.65)
      [typeid] cost is  0.59 ns (true  0.93, false  1.56, baseline  0.65)
  [dynamic id] cost is  1.43 ns (true  2.26, false  1.89, baseline  0.65)
   [static id] cost is  0.00 ns (true  0.63, false  0.67, baseline  0.65)
```

**Comment by havardpe** [comment]
@baldersheim @toregge FYI

**Review by baldersheim — COMMENTED** [review]
👍

**Comment by geirst** [comment]
@vekterli FYI

**Comment by vekterli** [comment]
TIL: `std::type_index` is a thing! And a neat thing it is!

**Pull request merged**
