### PR TITLE
access-control is implicit

### PR DESCRIPTION
**Pull request by bjormel**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by gjoranv** [comment]
Build fails due to a change in the public api:
´´´
[ERROR] Failed to execute goal com.yahoo.vespa:abi-check-plugin:7-SNAPSHOT:abicheck (default) on project config-model-api: ABI spec mismatch. To update run 'mvn package -Dabicheck.writeSpec' -> [Help 1]
´´´

@musum, is this enum intentionally public api?

**Comment by hmusum** [comment]
Sorry, I don't know if this API is intentionally public.

**Comment by gjoranv** [comment]
It seems strange that the enum should be public. @bratseth, any ideas why (ValidationId in config-model-api)?

**Comment by hmusum** [comment]
Anyway, you can't remove `accessControl` until no config-model is using it.

**Comment by bjorncs** [comment]
@bjormel `config-model-api` is public-api just to have the abi-check-plugin detect binary incompatibility. It's safe to remove once all model versions in hosted/cloud no longer use it.

**Review by bjorncs — APPROVED** [review]
Keep `ValidationId.accessControl`, otherwise ok.

**Review by bjorncs — APPROVED** [review]

**Pull request merged**
