### PR TITLE
Sort IP addresses when serializing

### PR DESCRIPTION
**Pull request by mpolden**
No point in doing it every time we create a Node object. This was rumoured to be
too expensive.

FYI @hmusum @baldersheim

### CODE REVIEW

**Review by hakonhall — APPROVED** [review]
FYI @baldersheim @hmusum

**Review by baldersheim — COMMENTED** [review]
Can we drop sorting on read until everything is sorted ?

**Review by baldersheim — APPROVED** [review]
After discussing with @hakonhall and @freva it seems we ar egood to go. Apparently we do a full read/rewrite on startup of cfg

**Comment by mpolden** [comment]
> Apparently we do a full read/rewrite on startup of cfg

That's correct.

**Comment by baldersheim** [comment]
Then I guess we can also get rid of the sanitychecking that also takes place during construction of Node in requireIpAddresses() which does a foreach InetAddress.forString(). If that can be moved till write it would be very good.

**Comment by mpolden** [comment]
Sure, I'll have a look.

**Pull request merged**
