### PR TITLE
Count Docker nodes when throttling in node failure

### PR DESCRIPTION
**Pull request by freva**

### CODE REVIEW

**Comment by mpolden** [comment]
If we count Docker nodes, failing a single Docker _host_ will always put us above the throttle limit in most zones. I don't think having them count against the limit independently of their host makes sense as they share the same underlying network and hardware after all.

**Comment by freva** [comment]
After some thinking:
This PR has 2 main changes: 
* The first is that docker hosts and nodes are no longer ignored when looking for "dead" nodes, this should have no effect since `ready` docker containers do not exist, and `ready` docker hosts exists only in a zone without zone-app.
* The second is that we include docker nodes in `throttle` count. This will actually fail spectacularly with this change: 
1) Docker host gets a hardware failure, updates node-repo for self and children
2) Docker host ask orchestrator to suspend each child, if permitted, will stop services
3) NodeFailer will fail out child nodes after 1h as they are down, but only 2 nodes are allowed to fail
4) The host itself will only attempt to suspend and stop services when it has successfully done so for all its children
5) Node allocator will likely allocate more nodes to this host as it will be the least used nodes

Repeat 3-5 :sob:

**Comment by freva** [comment]
@mpolden Here's a possible solution: Allow to fail `host` if we are on the throttle limit. This way we are (almost) guaranteed to be able to fail out a docker host/day (including all its children).

**Comment by mpolden** [comment]
I still don't understand why containers should be counted when throttling. What problem do we solve?

Counting containers as regular hosts doesn't make sense when the reasons for failure are always at the host level, for the cases we care about when making a throttle decision.

**Comment by mpolden** [comment]
Discussed elsewhere. Merge when merge stop is lifted.

**Pull request merged**
