### PR TITLE
Gjoranv/vagrant fixes

### PR DESCRIPTION
**Pull request by gjoranv**
FYI: @bjorncs 

We should add an environment var to allow using it without CPP tools and GUI, e.g. USE_CPP_TOOLS which defaults to true. Also, I don't really understand why Vagrantfile requires VESPA_VAGRANT_VM_BOX_URL to be set. Vagrant handles boxes perfectly well, and updates if necessary, without `config.vm.box_url`.

### CODE REVIEW

**Comment by geirst** [comment]
@vekterli FYI

**Review by geirst — APPROVED** [review]
👍

**Comment by bjorncs** [comment]
🥇

**Comment by vekterli** [comment]
@gjoranv `VESPA_VAGRANT_VM_BOX_URL` is required to be set simply because that's 1 out of 2 variables that we had to manually set in our own Vagrantfiles locally, and I just moved them indiscriminately to environment variables as part of 15b35cb 🙂

**Comment by gjoranv** [comment]
@vekterli I found this in the Vagrant doc:

> If config.vm.box is a shorthand to a box in HashiCorp's Vagrant Cloud then this value does not need to be specified. Otherwise, it should point to the proper place where the box can be found if it is not installed.

I guess it means you are using a box that is not in HashiCorp's Vagrant Cloud then? I use plain 'centos/7'. I think specifying an url could be optional.

**Comment by vekterli** [comment]
Indeed, several of us use a home brewed box with GUI etc installed and set up in advance, so it's not a vanilla box in _Da Cloud™️_.

**Pull request merged**
