### PR TITLE
Arnej/allow struct types with same name

### PR DESCRIPTION
**Pull request by arnej27959**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

@bratseth and @baldersheim please review

### CODE REVIEW

**Review by bratseth — COMMENTED** [review]
Finally there! But are we changing ids of struct definitions that works today here?

**Comment by arnej27959** [comment]
> But are we changing ids of struct definitions that works today here?

yes, this is alternative "A": change name (and id) of user-defined struct types so they can be registered in DocumentTypeManager simultaneously.

if feels like we can just go with alternative "B" which is to stop registering struct types in the DocumentTypeManager at all;  I'm going to test that tomorrow and see what the fallout is.

**Comment by arnej27959** [comment]
now: this is alternative "B" and it passes some struct-related system tests; if there are no objections I'll merge this once factory is green.

**Review by baldersheim — APPROVED** [review]

**Comment by bratseth** [comment]
But we're still changing ids of structs that can be deployed today - doesn't that mean that we'll be unable to read existing data stored in such structs once this version rolls out?

**Comment by arnej27959** [comment]
Re: changing IDs of structs - these aren't serialized, instead the reader knows from config which struct type to use for deserializing.  Only field IDs are truly critical; these are calculated using a hash from field name and type ID, but can also be overridden when creating fields.

Anyway, now on alternative "B" we keep the name and ID of the struct types but stop registering them in (global) maps, so we can have different types with same name and ID.  This feels like a safer change, even if the user-visible changes are (in theory) bigger.

**Comment by bratseth** [comment]
I don't know how structs are deserialized so if you're sure you know the consequences here feel free to merge, but I notice there's still a lot of changes to ids in documentmanager.cfg's in this PR which seems to contradict your second paragraph.

**Comment by baldersheim** [comment]
Arne is correct struct ids has no effect on serialisation. Only name is used.

**Review by baldersheim — APPROVED** [review]

**Comment by arnej27959** [comment]
Sorry about the confusion, the changes in documentmanager.cfg are only for "idx" numbers (those counting from 10000) which aren't type IDs at all, just indexes for referencing between types in that config.

**Comment by arnej27959** [comment]
>  Arne is correct struct ids has no effect on serialisation. Only name is used.

actually name isn't used either - only the contents of the struct type (the fields) really matter.

**Pull request merged**
