### PR TITLE
Consider reservedTo before switch priority

### PR DESCRIPTION
**Pull request by mpolden**
@bratseth

FYI @yngveaasheim

### CODE REVIEW

**Comment by bratseth** [comment]
Hmm, are we sure we want this? They will just be moved afterwards when switch rebalancing is enabled.

**Comment by yngveaasheim** [comment]
At the moment, this is a problem due to VESPA-19616, making it pretty hard to avoid nodes ending up on another host with bad SSD, eg as experienced in VESPA-19879. Also ref VESPA-19882.

**Comment by bratseth** [comment]
Yes, we're missing a feature for dealing with this problem (we's want something like the reverse of reservedTo), and are trying to make do with what we have.

Fine, but could you add a todo on correcting the order again later @mpolden ?

**Comment by mpolden** [comment]
> They will just be moved afterwards when switch rebalancing is enabled.

Yes, but I think that's fine. This also applies to rebalancing, if skew can be reduced by using a non-reserved host Rebalancer will move away from the reserved host eventually (since `reservedTo` is cleared after first deployment).

Additionally if a non-reserved host is always picked over a reserved one, the latter will never become available to other tenants (`reservedTo` is never cleared).

**Comment by bratseth** [comment]
> Additionally if a non-reserved host is always picked over a reserved one, the latter will never become available to other tenants (reservedTo is never cleared).

Good point. Reminds me why I don't like the reservedTo feature.

**Review by bratseth — APPROVED** [review]

**Pull request merged**
