### PR TITLE
Allocate 2Gb to tester app, and 75% of the rest to Surefire

### PR DESCRIPTION
**Pull request by jonmv**
@freva please review.

### CODE REVIEW

**Comment by jonmv** [comment]
Or @hmusum

**Review by freva — COMMENTED** [review]
... what are these magic numbers :confused:

**Comment by jonmv** [comment]
Aren't the comments clear enough? :p

**Review by freva — APPROVED** [review]
Sure, as long as the flavor doesn't change too much... Might as well have hardcoded those values.

**Comment by jonmv** [comment]
The new thing is that users may ask for larger containers, and this sets aside only the minimum required for the tester app, and lets the user have the rest for tests.

**Pull request merged**
