### PR TITLE
Add build() method to config builders

### PR DESCRIPTION
**Pull request by bratseth**
@gjoranv please review

### CODE REVIEW

**Comment by gjoranv** [comment]
1. Are the changes in QueryTestCase intentional? If so, please split to a separate commit.
2. My intention was to add the build method at the root builder only. Having it in the inner builders encourage breaking the dot-chaining when building a config. I assume that you will argue that it doesn't matter and that you want symmetry.

**Review by gjoranv — CHANGES_REQUESTED** [review]
1. Are the changes in QueryTestCase intentional? If so, please split to a separate commit.
2. My intention was to add the build method at the root builder only. Having it in the inner builders encourage breaking the dot-chaining when building a config. I assume that you will argue that it doesn't matter and that you want symmetry.

**Comment by bratseth** [comment]
1. Why? It would make the history slightly nicer, but we're optimizing quality given limited available resources, not unconditionally trying to make everything perfect.
2. Right, I will  :-) I suggest we merge this now and then you can change your existing intention to be to improve it this further rather than making it.

**Comment by gjoranv** [comment]
1. I thought your resources were unlimited.
2. Ok, I realize that my arguments are not objectively better than yours.

**Comment by gjoranv** [comment]
👍 Just in case, as I originally requested changes, and didn't approve before merge.

**Pull request merged**
