### PR TITLE
Balder/enable metrics reporting earlier in proton

### PR DESCRIPTION
**Pull request by baldersheim**
@geirst PR Only the last commit has any semantic change.

### CODE REVIEW

**Comment by geirst** [comment]
Proton is passed as a reference to StateServer via ComponentConfigProducer API. The getComponentConfig() impl in Proton is taking a lock on the same mutex as is taken in waitForInitDone(). getComponentConfig() is called when StateApi (member of StateServer) is handling a "state/v1/config" request. This means we are not able handle such request while Proton is waiting in waitForInitDone(). Not sure if this is ok or not? @havardpe / @toregge any additional comments?

**Comment by baldersheim** [comment]
I see that it uses both a shared lock and an exclusive lock guard. I think that mean that it is like a reader/writer lock. So all readers will be allowed to commence except during addDocumentDB and removeDocumentDB.

**Comment by baldersheim** [comment]
@toregge Any comments ?

**Comment by toregge** [comment]
This might cause issues due to structures not being up when asked about them, e.g.
document meta stores for subds (c.f DocumentSubDbinitializerResult being passed to document subdb setup method when structures are initialized).

DocumentDBExplorer::get_state() tries to instantiate a DocumentMetaStoreReadGuards, but that will fail due to null pointers in the constructor.

**Comment by baldersheim** [comment]
I have added protection against following the nullptr where I saw the possibility.
I will let factory root out the rest.

**Pull request merged**
