### PR TITLE
Allow unpinning when change is otherwise empty

### PR DESCRIPTION
**Pull request by jonmv**
@mpolden please review.

### CODE REVIEW

**Review by mpolden — APPROVED** [review]

**Comment by mpolden** [comment]
Test?

**Comment by jonmv** [comment]
I think it's trivial enough not to add a test for it?

**Comment by jonmv** [comment]
Merging fix, in any case.

**Comment by mpolden** [comment]
Since this wasn't caught in the initial test I would argue that the test wasn't comprehensive enough. Remember that we also often use API tests as documentation.

**Pull request merged**
