### PR TITLE
Get the Vespa version for flags from the model version

### PR DESCRIPTION
**Pull request by bratseth**
A flag value which depends on Vespa version should not take
effect immediately when a deployment wants that version
but only for nodes which are actually upgraded to that version.

Take the flag version from the Vespa model version to achieve this.

@hakonhall and @hmusum and/or @arnej27959  please review.

(I'm going to clean this up a bit, but I wanted to keep the change small for now.)

### CODE REVIEW

**Review by jonmv — APPROVED** [review]
Good idea!

**Review by hakonhall — APPROVED** [review]
nice

**Review by arnej27959 — APPROVED** [review]
looks good to me

**Review by hmusum — APPROVED** [review]
👍

**Pull request merged**
