### PR TITLE
Avoid holding the application lock while deploying — just when writing

### PR DESCRIPTION
**Pull request by jonmv**
@bratseth and @mpolden please review. 

@hmusum FYI.

### CODE REVIEW

**Review by bratseth — COMMENTED** [review]
Couldn't this lead to a race where threads A and B attempt to deploy to the same zone but with different parameters, and finishes the deploy calls in order A B but writes the result in order B A?

**Comment by bratseth** [comment]
A smaller issue before I forget: The javadoc of lockForDeployment is wrong now, and if we decide to do this we can probably remove it (which would be good).

**Comment by jonmv** [comment]
1. Yes, I believe that's possible, but not without manual interference. Automatic deployments are already locked on a job-level. Perhaps we should add a separate lock for deployments, then, which would be held for the duration of the deployment to a specific zone?
2. Will take care of that.

**Comment by bratseth** [comment]
1. Yes, I think we should use deployment-level locks if we do his.

**Comment by jonmv** [comment]
PTAL,

**Comment by bratseth** [comment]
Great! Feel free to merge.

**Pull request merged**
