### PR TITLE
Add node to system info

### PR DESCRIPTION
**Pull request by gjoranv**
The new user api is `systemInfo.node().id()`, which is meant as a discriminator between Jdisc containers.
Node can be extended with other properties as we find appropriate.

### CODE REVIEW

**Review by bratseth — COMMENTED** [review]
Would it make sense to just use the integer node index here? That would make this easier to use.

Could we also pass the count of nodes in the cluster?

**Comment by gjoranv** [comment]
Omitting the cluster id and the 'container'/'qrserver' prefix is a good idea. After all, you don't need to keep the id/index unique between clusters. Should we change the name to 'index'?

I'll look into the node count as well.

**Comment by bjorncs** [comment]
`Node` can expose index and full config id in separate methods, or alternatively expose cluster name in addition to index?

**Comment by bratseth** [comment]
> Should we change the name to 'index'?

Yes? And document it is guaranteed to be unique but not contiguous from 0.

**Comment by gjoranv** [comment]
Starting fresh in a new PR.

**Pull request closed without merging**
