### PR TITLE
Jonmv/token tell handler

### PR DESCRIPTION
**Pull request by jonmv**
@bjorncs or @tokle please review. 
@ldalves FYI, token fingerprints will get an additional `"state"` field, and _may_ have only the `"fingerprint"` and `"state"` fields, if deleted, but still present on some nodes. See the unit test for an example payload:
```json 
                                  {
                                    "tokens": [
                                      {
                                        "id": "myTokenId",
                                        "versions": [
                                          {
                                            "fingerprint": "%s",
                                            "created": "2020-09-13T12:26:40Z",
                                            "author": "user@test",
                                            "expiration": "2020-10-13T12:26:40Z",
                                            "state": "active"
                                          },
                                          {
                                            "fingerprint": "ff:01",
                                            "state": "deactivating"
                                          }
                                        ]
                                      }
                                    ]
                                  }
```
The possible `"state"` values are `"active"`, `"deploying"`, "`deactivating"`.

### CODE REVIEW

**Comment by jonmv** [comment]
Hmm, come to think of it, we _do_ need to store the _tokens_ in use by each deployment, for retriggering. That'll let us differentiate between tokens which aren't referenced in any deployment (`"unused"`), and those that are, but just aren't present anywhere yet (`"deploying"`).

**Comment by jonmv** [comment]
If someone wants different names for these states, just holler, btw. Perhaps "inactive", "activating", "active", "deactivating"?

**Comment by bjorncs** [comment]
My suggestion is `revoking` and `revoked` which common nomenclature for invalidating credentials

**Review by bjorncs — DISMISSED** [review]

**Comment by jonmv** [comment]
Hmm. A token could be created, but not in use anywhere, though. Not yet. We need a name for that as well. Versions that are completely revoked are not shown, because they are, indeed, irrelevant.

**Review by tokle — DISMISSED** [review]

**Review by bjorncs — APPROVED** [review]

**Pull request merged**
