### PR TITLE
[VESPA-15011] Avoid average of averages.

### PR DESCRIPTION
**Pull request by yngveaasheim**

### CODE REVIEW

**Comment by yngveaasheim** [comment]
@hmusum Please review and merge.

**Comment by gjoranv** [comment]
I don't have an opinion about the metrics added, but big changes to the default metric set should probably be brought up in the architect meeting or at least sent out to vespa-architects.

I suggest to move the TODO comment to the class header. In the short term we can model the aggregator in the Metric class to make it less confusing, and more convenient to add a "default" set of aggregators for each metric.

**Review by hmusum — APPROVED** [review]

**Comment by yngveaasheim** [comment]
@gjoranv I have sent a mail on the details to vespa-architects, will call for a meeting if requested.

**Comment by yngveaasheim** [comment]
I have discussed offline with @gjoranv on the TODO comments, we agreed to keep this as suggested. I did some minor changes after feedback on removal of 'last' values.

@hmusum or @gjoranv Please review last commit and merge.

**Review by hmusum — APPROVED** [review]

**Review by gjoranv — APPROVED** [review]

**Comment by gjoranv** [comment]
Build error is unrelated.

**Pull request merged**
