### PR TITLE
Move lock metrics to MetricsReporter

### PR DESCRIPTION
**Pull request by hakonhall**
Adds two new metrics:

 - The load of acquiring each lock path: The average number of threads waiting
   to acquire the lock within the last minute (or unit of time).  Aka the lock
   queue (depth).

 - The load of the lock for each lock path: The average number of threads
   holding the lock within the last minute (or unit of time).  This is always
   <= 1.  Aka the lock utilization.

Changes the LockCounters to LockMetrics, and exporting those once every minute
through MetricReporter which is designed for this.

### CODE REVIEW

**Comment by hakonhall** [comment]
The load of an ongoing lock is reported only at the end, and causes a spike there.  Working on smoothing that out.

**Review by mpolden — APPROVED** [review]
👍

**Comment by hakonhall** [comment]
Let me merge to try to get into the release tomorrow - please post-review...

**Comment by mpolden** [comment]
👍

**Pull request merged**
