### PR TITLE
Use timeout from request parameter in config convergence checker

### PR DESCRIPTION
**Pull request by mpolden**

### CODE REVIEW

**Review by hmusum — CHANGES_REQUESTED** [review]
Looks good to me, but a unit test fails (although it works locally for me).

**Review by hmusum — APPROVED** [review]

**Review by hmusum — CHANGES_REQUESTED** [review]
Accidentally approved after requesting changes

**Comment by mpolden** [comment]
Yes, I noticed. I suspect the exception message for `SocketTimeoutException` is platform specific (Linux vs macOS). Will have a look tomorrow.

**Comment by mpolden** [comment]
@hmusum PTAL

**Review by hmusum — APPROVED** [review]

**Pull request merged**
