### PR TITLE
Bratseth/cleanup hit 2

### PR DESCRIPTION
**Pull request by bratseth**
@arnej please review

### CODE REVIEW

**Comment by bratseth** [comment]
Ping @arnej27959

**Comment by arnej27959** [comment]
it looks like you now have 4 identical asXML() methods, could you make it static and use the same one for all 4?

**Comment by bratseth** [comment]
Is it really worth it when all of them will be removed in a quarter?

**Review by arnej27959 — APPROVED** [review]
looks good to me, your call if you want to change the asXML() thing

**Pull request merged**
