### PR TITLE
Bjorncs/configserver dual rpc

### PR DESCRIPTION
**Pull request by bjorncs**

### CODE REVIEW

**Comment by bjorncs** [comment]
FYI @hmusum

**Review by vekterli — COMMENTED** [review]
:+1: to the code overall, awaiting the extra environment variable as per the meeting discussion to only trigger mixed security mode when explicitly configured.

**Comment by bjorncs** [comment]
@vekterli PTAL

**Review by vekterli — APPROVED** [review]
:+1:

**Pull request closed without merging**
