### PR TITLE
Move docker containers to dirty on Inactive expire

### PR DESCRIPTION
**Pull request by freva**

### CODE REVIEW

**Review by hakonhall — COMMENTED** [review]
Hm, thinking about this again - this will make it impossible to park containers.

An alternative could be to allow retiring a node admin whose children are all parked with wantToRetire?

**Comment by freva** [comment]
I want the containers to go down if we try to retire them, this requires node-admin to take them down before going down itself. 
Few ways to achive that:
1) This PR.
2) Make node-admin remove containers in `parked`: https://github.com/vespa-engine/vespa/blob/e22eb4aeb1a771b98f3be1d1c15d999847cf4e4f/node-admin/src/main/java/com/yahoo/vespa/hosted/node/admin/nodeagent/NodeAgentImpl.java#L312 and allow retire host whose all children are `parked`.
3) This PR, but also utilizing `wantToDeprovision` flag (f.ex. only `wantToRetire` => `parked`, `wantToRetire` && `wantToDeprovision` => remove? `dirty`?

**Comment by hakonhall** [comment]
I like 3. Can that be done in a user-friendly way? wantToDeprovision on DH should recursivelly set it on the children too.

**Comment by freva** [comment]
Going with 3 in #4969

**Pull request closed without merging**
