### PR TITLE
Separate documentapi artifacts

### PR DESCRIPTION
**Pull request by gjoranv**
This replaces #13573, and is necessary to allow bundle-plugin to fail when a bundle embeds the `component` artifact. This is also a small step in the direction to build slim bundles.

We should now use `container-documentapi` for anything related to the container, while `documentapi` should only be used for standalone clients.

@aressem Is anything else requried to have the new module built on factory and published on maven-central?

### CODE REVIEW

**Comment by gjoranv** [comment]
´´´
CMake Error at CMakeLists.txt:78 (add_subdirectory):
  The source directory
    /source/documentapi
  does not contain a CMakeLists.txt file.
´´´

Why does this module need a CMakeLists, and not the `container` module?

I didn't notice the C++ code in here until now. Why is this a mixed module? Perhaps we should use the name `documentapi-lib` instead.

**Review by bratseth — APPROVED** [review]

**Comment by toregge** [comment]
Consider not moving the C++ code from documentapi module to container-documentapi module.

**Comment by vekterli** [comment]
The documentapi directory contains all the C++ logic required for the content cluster to both receive and send DocumentAPI protocol messages from/to clients. It is a "legacy" module and these had a tendency to be mixed language. But the C++ code should not be moved to a Java-specific target directory.

**Review by geirst — CHANGES_REQUESTED** [review]
As summarised by @toregge and @vekterli, the C++ code should not be moved.

**Comment by gjoranv** [comment]
As agreed with Tor on Slack, I'll create a new PR that does not move the C++ code, and update the OWNERS to reflect reality.

**Pull request closed without merging**
