### PR TITLE
Avoid copy.

### PR DESCRIPTION
**Pull request by baldersheim**
@geirst or @havardpe PR

### CODE REVIEW

**Comment by baldersheim** [comment]
@arnej27959 or @toregge PR

**Review by arnej27959 — CHANGES_REQUESTED** [review]
you should be able to write this without macros pretty easily i think...

**Comment by baldersheim** [comment]
@arnej27959 I have added extra braces and a using clause.

**Review by arnej27959 — APPROVED** [review]
now using templated helper structs instead
@toregge and @baldersheim PTAL

**Pull request merged**
