### PR TITLE
Feature flags

### PR DESCRIPTION
**Pull request by hakonhall**
This defines 2 parts of a feature flag system:

 - A new configsource module which describes sources of "config" in the form
   of JSON. For a given feature, ZooKeeper could have a setting for it, a local
   file could have an override for it, etc. Config sources are merged using
   some policy of preference to produce a single JSON.

 - The JSON is then used by a concrete feature class, e.g. a feature flag class
   for whether something is enabled or not. This is the changes in node-admin.

### CODE REVIEW

**Comment by hakonhall** [comment]
FYI @hmusum

**Comment by baldersheim** [comment]
@hakonhall I guess this one should be closed ?

**Comment by hakonhall** [comment]
we need to implement featureflags in near future, so we'll keep this open for a while longer

**Comment by hakonhall** [comment]
Superseded by #7760

**Pull request closed without merging**
