### PR TITLE
Jonmv/dep cleanup

### PR DESCRIPTION
**Pull request by jonmv**
@bjorncs or @gjoranv please review.

### CODE REVIEW

**Review by bjorncs — APPROVED** [review]

**Comment by gjoranv** [comment]
Note that order is significant in maven, so we should compare dependency:tree output before and after such changes for 'container' and 'container-dev'.

**Review by gjoranv — APPROVED** [review]
Great!

**Review by bjorncs — APPROVED** [review]
Fewer artifacts exposed is great 👍 🥇

**Comment by jonmv** [comment]
I ran what we have of tests using `application`, in our two Vespa repos, without finding any container breakages. I suppose this _could_ break someone using using `httpclient` in their own unit tests, without depending on it, but that's an acceptable tradeoff, I guess :)

**Comment by gjoranv** [comment]
httpclient is explicitly given in com.yahoo.vespa.tenant:base which is used by most hosted vespa apps.

**Pull request merged**
