### PR TITLE
Balder/reduce netty default buffer

### PR DESCRIPTION
**Pull request by baldersheim**
@jonmv or @hmusum or @bjorncs or @geirst PR

### CODE REVIEW

**Review by hmusum — APPROVED** [review]

**Comment by jonmv** [comment]
The best

**Review by bjorncs — COMMENTED** [review]
Should be do the same for all Zookeeper instances (anything using zkfacade or zookeeper-server artifacts)?

**Comment by baldersheim** [comment]
Yes, probably. Where would that be ?

**Comment by jonmv** [comment]
`16Mb` isn't usually as significant as here. What are our other clients? The `vespa-zkcli` family, and the config servers?

**Comment by baldersheim** [comment]
16 is not significant, but 16*N might be. It seems like additional chunks will get allocated with the same size in a thread local cache, which might give you #NioEventLoops * 16

**Comment by jonmv** [comment]
It's surprising  if many such threads are created, though?

**Comment by jonmv** [comment]
It could also be that 16Mb is more suitable for our other clients. The config server and controller zk usage is much heftier.

**Comment by baldersheim** [comment]
CC has at least 6 for zookeeper and 3 for zkfacade

**Comment by bjorncs** [comment]
ZK client config is created by `ZkClientConfigBuilder`. There is an similar class for server-side in zkfacade.

**Pull request merged**
