### PR TITLE
add fork of airlift zstd code

### PR DESCRIPTION
**Pull request by arnej27959**
@gjoranv please verify that this is OK with enforcer rules etc
@vekterli please take a look at the zstd code
@jonmv FYI

### CODE REVIEW

**Review by vekterli — APPROVED** [review]
:+1: with this I can finally retire my hacky branch with manually patched files. As discussed offline, it would be good to get at least a subset of the original unit tests, but this can be a follow-up since we're not changing the semantics of the forked code (and the tests cannot be unreasonably expensive to run).

**Review by gjoranv — APPROVED** [review]
It seems like the original aircompress is now unused, and could be removed. Should we keep it to avoid extra work if/when they decide to merge the mentioned PR?

**Comment by baldersheim** [comment]
I suggest removing it. It is not that hard to add it back. And just blurs how the dots are connected.

**Comment by arnej27959** [comment]
Thanks @gjoranv - this looks good to me

**Review by baldersheim — APPROVED** [review]

**Pull request merged**
