### PR TITLE
Revert "Reapply improve range search performance"

### PR DESCRIPTION
**Pull request by aressem**
Reverts vespa-engine/vespa#29125

System test [ReportCoverage::test_reportcoverage__ELASTIC](https://factory.vespa.oath.cloud/testrun/71432006/test/ReportCoverage::test_reportcoverage__ELASTIC) has failed since this was merged.

### CODE REVIEW

**Comment by baldersheim** [comment]
I think the system test requires an update, @geirst will confirm.

**Comment by aressem** [comment]
Can we fix or merge this one ?

**Comment by geirst** [comment]
The failing system test is set to ignored and will be fixed today.

**Comment by geirst** [comment]
System test fixed in https://github.com/vespa-engine/system-test/pull/3087.

**Pull request closed without merging**
