### PR TITLE
Use InfrastructureApplication

### PR DESCRIPTION
**Pull request by hakonhall**

### CODE REVIEW

**Review by gjoranv — APPROVED** [review]
There are still a few places where e.g. the 'zone-config-servers' string is repeated in this repo. Only one occurrence in production code though (I filtered out a few matches in comments).

```
$ git grep -l zone-config-servers
controller-server/src/main/java/com/yahoo/vespa/hosted/controller/application/SystemApplication.java
controller-server/src/test/java/com/yahoo/vespa/hosted/controller/routing/RoutingPoliciesTest.java
orchestrator/src/test/java/com/yahoo/vespa/orchestrator/OrchestratorUtilTest.java
node-repository/src/test/java/com/yahoo/vespa/hosted/provision/provisioning/LoadBalancerProvisionerTest.java
```

**Comment by hakonhall** [comment]
These paths don't exist in this repo.

**Comment by gjoranv** [comment]
Sorry, I mixed up the repos. Comment is updated.

**Comment by gjoranv** [comment]
I don't know how important it is to replace these strings with their respective constants everywhere, so merge at will.

**Comment by hakonhall** [comment]
SystemApplication.java is fixed in this PR.
The other files are tests, and I think it's OK for them to actually verify everything resolves to e.g. zone-config-servers.

**Pull request merged**
