### PR TITLE
Require validation override for destructive endpoint changes

### PR DESCRIPTION
**Pull request by mpolden**

### CODE REVIEW

**Review by bratseth — APPROVED** [review]
Your class rename has been turned into a remove/add pair. LGTM though.

**Comment by mpolden** [comment]
Yes, that happens if the diff is too large.

**Comment by bratseth** [comment]
By whom? It's two different things in git ...

**Comment by mpolden** [comment]
It's not. Git tracks content, not individual files so `git mv file1 file2` is equivalent to `cp file1 file2 && git rm file1 && git add file2`.

No information about renames is persisted in Git. Renames are only shown as output from e.g. `git diff`, which can detect renames based on similarity in content, i.e. is the diff between `file1` and `file2` small enough to count as a rename. This is decided by a diff threshold, where the default is 50%. See the `-M` option in `git help diff`.

([my second commit](https://github.com/vespa-engine/vespa/pull/11004/commits/a687ead62f2226958327dc37a172f355f73b88f3) vs. t[he total branch diff](https://github.com/vespa-engine/vespa/pull/11004/files) is a good example of this, first diff detects a rename while the latter doesn't because more than 50% of the file has changed).

**Comment by bratseth** [comment]
TIL - thanks. (Although git do know about file names so this is pretty lame.)

**Pull request merged**
