### PR TITLE
Disallow URI type resources for hosted Vespa

### PR DESCRIPTION
**Pull request by jonmv**
@hmusum please review and merge.

### CODE REVIEW

**Review by hmusum — APPROVED** [review]
LGTM, @lesters this is in accordance with the work you are doing?

**Comment by lesters** [comment]
@hmusum No, I think this is for URI resources downloaded to content nodes (defined in document schema). Is that correct @jonmv ?

**Comment by jonmv** [comment]
This is only used for ranking constants now.

**Comment by jonmv** [comment]
URI types are also undocumented: https://docs.vespa.ai/en/reference/schema-reference.html#constant

**Pull request merged**
