### PR TITLE
Bratseth/more field types

### PR DESCRIPTION
**Pull request by bratseth**
@baldersheim here's a start, adding float16 and bool types

### CODE REVIEW

**Comment by bratseth** [comment]
bool: Datatype id 6
BoolFieldValue class id: Ids.document + 17

float16: Datatype id 7
Float16FieldValue class id: Ids.document + 18

Type is called "bool" and "float16" in summary and attribute config classes.

Searching for a boolean produces a word item where the word token is "true" or "false".

**Review by baldersheim — APPROVED** [review]
👍

**Comment by baldersheim** [comment]
The attributes already has support for the bool type as INT1, but it is better to use BOOL. I will clean up the INT1 stuff.

**Comment by kkraune** [comment]
ref #6644

**Pull request merged**
