### PR TITLE
Dense string form

### PR DESCRIPTION
**Pull request by bratseth**
@lesters please review

@havardpe and @jobergum fyi. This allows you to create a tensor from e.g the string
 tensor(x[2],y[3]):[[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]]

Btw, when doing this I somewhat regretted laying out dense tensors with the items of the rightmost dimension adjacent and the leftmost furthest apart as it isn't how you want to write it. Did we ever discuss that decision, and do we even know we have agreement across Java and C++?

### CODE REVIEW

**Comment by lesters** [comment]
A couple of test errors:

```
[ERROR] requireThatInvalidTensorTypeSpecThrowsException(com.yahoo.searchdefinition.processing.RankingExpressionWithTensorTestCase)  Time elapsed: 0.025 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: (an instance of java.lang.IllegalArgumentException and exception with message a string containing "For constant tensor 'my_tensor' in rank profile 'my_profile': Illegal tensor type spec: A tensor type spec must be on the form tensor[<valuetype>]?(dimensionidentifier[{}|[length?]*), but was 'tensor(x)'. Dimension 'x' is on the wrong format. Examples: tensor(x[]), tensor<float>(name{}, x[10])")
     but: exception with message a string containing "For constant tensor 'my_tensor' in rank profile 'my_profile': Illegal tensor type spec: A tensor type spec must be on the form tensor[<valuetype>]?(dimensionidentifier[{}|[length?]*), but was 'tensor(x)'. Dimension 'x' is on the wrong format. Examples: tensor(x[]), tensor<float>(name{}, x[10])" message was "For constant tensor 'my_tensor' in rank profile 'my_profile': Illegal tensor type spec: A tensor type spec must be on the form tensor[<valuetype>]?(dimensionidentifier[{}|[length]*), but was 'tensor(x)'. Dimension 'x' is on the wrong format. Examples: tensor(x[3]), tensor<float>(name{}, x[10])"
Stacktrace was: java.lang.IllegalArgumentException: For constant tensor 'my_tensor' in rank profile 'my_profile': Illegal tensor type spec: A tensor type spec must be on the form tensor[<valuetype>]?(dimensionidentifier[{}|[length]*), but was 'tensor(x)'. Dimension 'x' is on the wrong format. Examples: tensor(x[3]), tensor<float>(name{}, x[10])
```

and

```
[ERROR] requireThatIllegalTensorTypeSpecThrowsException(com.yahoo.searchdefinition.processing.TensorFieldTestCase)  Time elapsed: 0.003 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: (an instance of java.lang.IllegalArgumentException and exception with message a string containing "Field type: Illegal tensor type spec: A tensor type spec must be on the form tensor[<valuetype>]?(dimensionidentifier[{}|[length?]*), but was 'tensor(invalid)'. Dimension 'invalid' is on the wrong format. Examples: tensor(x[]), tensor<float>(name{}, x[10])")
     but: exception with message a string containing "Field type: Illegal tensor type spec: A tensor type spec must be on the form tensor[<valuetype>]?(dimensionidentifier[{}|[length?]*), but was 'tensor(invalid)'. Dimension 'invalid' is on the wrong format. Examples: tensor(x[]), tensor<float>(name{}, x[10])" message was "Field type: Illegal tensor type spec: A tensor type spec must be on the form tensor[<valuetype>]?(dimensionidentifier[{}|[length]*), but was 'tensor(invalid)'. Dimension 'invalid' is on the wrong format. Examples: tensor(x[3]), tensor<float>(name{}, x[10])"
Stacktrace was: java.lang.IllegalArgumentException: Field type: Illegal tensor type spec: A tensor type spec must be on the form tensor[<valuetype>]?(dimensionidentifier[{}|[length]*), but was 'tensor(invalid)'. Dimension 'invalid' is on the wrong format. Examples: tensor(x[3]), tensor<float>(name{}, x[10])
```

**Comment by lesters** [comment]
Following your question, and the comment in the code:

```
A dense tensor is laid out with the rightmost dimension as adjacent numbers, but when we parse a dense tensor we encounter numbers in the leftmost-adjacent order, since that is the most natural way to write it: tensor(x,y)[[1,2],[3,4]] should mean {{x:0, y:0}:1, {x:1, y:0}:2, {x:0, y:1}:3, {x:1, y:1}:4}
```

I don't think this is necessarily the most natural way. The way this is implemented now follows from the column-major ordering which is used in Fortran and R. On the contrary, the row-major order is what is used in C and Python, which would mean `tensor(x[2],y[3])` would be `[[1,2,3],[4,5,6]]`

Perhaps this is me used to dealing with Python in this area, but I would vote for the C/Python ordering as that is also what we have implemented in the code as well for building dense tensors.

**Comment by bratseth** [comment]
Urk, this is like endianness. The next time we make civilization lets make sure to have a meeting first where we agree on the Right Way for any arbitrary decision we'll have to make in the future.

In any case, I agree we should do as people using Python would expect, so I changed it now.

**Comment by bratseth** [comment]
@lesters take a look again please

**Review by lesters — APPROVED** [review]
LGTM! 👍

**Pull request merged**
