### PR TITLE
Report raw numbers instead of a percentage.

### PR DESCRIPTION
**Pull request by baldersheim**
@yngveaasheim PR

### CODE REVIEW

**Comment by yngveaasheim** [comment]
The documents_covered.average and documents_total.average names seems to indicate that the values are pre-aggregated values, assumably for all queries within a minute. We can probably use these values, as we also have access to the number of queries per time unit. But it would be even better to have the raw values, such as the total number of documents searched for all queries within a minute.

**Comment by baldersheim** [comment]
@arnej27959 FYI

**Comment by baldersheim** [comment]
@yngveaasheim Now you can have a look again.

**Comment by yngveaasheim** [comment]
Looks good to me. Thank you!

**Pull request merged**
