### PR TITLE
Remove deprecated and undocumented feed handlers from container model

### PR DESCRIPTION
**Pull request by vekterli**
@bratseth @gjoranv @hmusum please review
@bjorncs FYI

We _probably_ want to hold off merging this one until after we've had the ✨multiple bucket spaces✨ version pushed into production. Also it is likely to break more than zero internal system tests that use old APIs.

More fodder for the "make document V2 API soon" argument.

### CODE REVIEW

**Review by bratseth — APPROVED** [review]

**Review by hmusum — APPROVED** [review]

**Comment by gjoranv** [comment]
Shouldn't the handlers themselves in `vespaclient-container-plugin` be removed too then? Otherwise LGTM.

**Comment by vekterli** [comment]
Baby steps 🙂 The comment in `package-info.java` says
```java
// TODO: This implements the old, deprecated document http API. Remove this package on Vespa 7.
```
so we can also choose to just yank everything out in one go once we're on Vespa 7. I just want these handlers unbound from our endpoints sooner due to their hairy semantics and exciting foot shooting capabilities.

**Comment by gjoranv** [comment]
Ok, unwire them now and remove later. Especially since these handlers are not formally deprecated. Maybe you should add `@Deprecated` now? 

Gotcha: this package is exported via package-info.java in vespaclient-core, not in vespaclient-container-plugin.

**Comment by vekterli** [comment]
I've marked everything under `com.yahoo.feedhandler` as deprecated. I'm also tempted to mark `GetSearcher` as deprecated, though we do not currently have feature parity with Document V1. Yay or nay?

_(I'll use this opportunity to casually seed the idea of a native gRPC container endpoint API, which will give us high performance sync/async API support essentially for free...! 🦄)_

**Comment by bratseth** [comment]
> I'm also tempted to mark GetSearcher as deprecated, though we do not currently have feature parity with Document V1.

Yes, all of that has to go on Vespa 7 because we'll remove things it depends on.

gRPC: Weren't there somebody external working on that?

**Comment by vekterli** [comment]
One issue with removing the `GetSearcher` is that I think there are people in production using it programmatically as a searcher and not as a HTTP request handler. But if we can offer a viable alternative then there's no problem.

Re: gRPC, someone said they were doing _something_ with it, but I haven't received any details on what exactly. Either way I strongly suggest that a potential gRPC<->Document API/search integration be designed and implemented by the Vespa Crew(tm)

**Review by gjoranv — APPROVED** [review]

**Comment by baldersheim** [comment]
@vekterli Should this one be merged, or should it marked do not merge ?

**Comment by vekterli** [comment]
Unless anyone objects, let's merge this today.

**Comment by baldersheim** [comment]
👍

**Comment by vekterli** [comment]
Hurgh, just noticed that we have quite a few internal tests that depend on an API that hasn't been rewritten to use Document V1 yet. Will revert for now and fix this before reapplying.

**Pull request merged**
