### PR TITLE
Escape dollar signs in the CMakeLists.txt on code execution as this i…

### PR DESCRIPTION
**Pull request by aressem**
…s used to populate another cmake script.

### CODE REVIEW

**Comment by aressem** [comment]
@hmusum

**Review by hmusum — APPROVED** [review]

**Comment by bratseth** [comment]
How can we automatically test this?

**Comment by aressem** [comment]
We need to install and start Vespa. Then run some system tests to verify that it works.

**Comment by bratseth** [comment]
Yes, or we could have at least one basic-search system test installing and using these packages?

**Comment by kkraune** [comment]
@lesters has a great idea on how to test the user guide using http://jupyter.org/

**Comment by lesters** [comment]
Actually, I've thought about this and we can do this more easily without using jupyter.

**Comment by lesters** [comment]
The basic idea is 'testable documentation', i.e. annotate pre fields in the documentation and make them executable or saveable (for files) etc. Then have a simple execution framework which runs within a screwdriver or travis build which pulls down a set of URLs which it basically just executes annotated pre's in order. For instance:

Basic running of commands in shell:

```
<pre data-test="exec">
    $ Run this command
    $ Run this command too
</pre>
```

Basic saving of files before for instance running `mvn package`:

```
<pre data-test="file" data-file="src/application/settings.xml">
    <xml>
      <somelement>
        Some content
      </somelement>
    </xml>
</pre>
```

Running a command and waiting for output before continuing:

```
<pre data-test="exec" data-wait-for="200 OK">
  $ Run this command 
</pre>
```

Run this command and expect some output.

```
<pre data-test="exec" data-assert-contains="200 OK">
  $ Run this command 
</pre>
```

This can probably be shelled out more, for instance having a setup or requirements section, teardown, import other files before running etc. But the above is minimally invasive and relatively low effort to implement.

**Comment by aressem** [comment]
I suggest that we take this discussion elsewhere than in this PR.

**Pull request merged**
