### PR TITLE
Revert "Jvenstad/reapply deployment graph api additions"

### PR DESCRIPTION
**Pull request by hmusum**
Reverts vespa-engine/vespa#12114

Requests to /deployment/v1 return
`{"error-code":"INTERNAL_SERVER_ERROR","message":"NullPointerException"}`

log on controller:
`[2020-02-07 17:15:55.944] WARNING : configserver     Container.com.yahoo.vespa.hosted.controller.restapi.deployment.DeploymentApiHandler
	Unexpected error handling 'https://api-cd.vespa.corp.yahoo.com:4443/deployment/v1/'
	exception=
	java.lang.NullPointerException
	at com.yahoo.vespa.hosted.controller.deployment.DeploymentStatus$JobStepStatus.<init>(DeploymentStatus.java:504)
	at com.yahoo.vespa.hosted.controller.deployment.DeploymentStatus$JobStepStatus$3.<init>(DeploymentStatus.java:594)
	at com.yahoo.vespa.hosted.controller.deployment.DeploymentStatus$JobStepStatus.ofTestDeployment(DeploymentStatus.java:594)`

### CODE REVIEW

**Review by freva — APPROVED** [review]

**Comment by jonmv** [comment]
I don't think this is because of the PR reverted here.

**Comment by hmusum** [comment]
Well, requests to ` /deployment/v1` started working after the version with this revert was released

**Comment by jonmv** [comment]
Ok ... >_<

**Comment by jonmv** [comment]
Aha.

**Pull request merged**
