### PR TITLE
Protobuf over jrt support in search

### PR DESCRIPTION
**Pull request by ollivir**
Implements most of the protobuf support needed in container-search. You would need to include `&dispatch.internal=true&dispatch.protobuf=true` in the request to enable the relevant code paths.

The changes are mostly about
- defining the message format
- including protobuf-java in the build and generated artifacts
- creating conversions from/to the query and result objects
- splitting the search invoker creation to be able to produce protobuf/rpc invokers in addition to fs4

### CODE REVIEW

**Review by bratseth — COMMENTED** [review]
This looks good, but I have one ask: Could you move the protobuf serialization out of the model classes and put them in a single ProtobufSerializer  instead?
I know you're following an existing pattern, but it is a bad one ... better to strictly separate model objects and serialization in different layers.

Also, perhaps we should have an rpc package under dispatch?

**Comment by ollivir** [comment]
That's fair. I was thinking about the bloat in model classes while adding those, but mirrored the old serialization. It also has the benefit of being near when you add or change fields. However, moving them to a ..dispatch.rpc package will collect them differently together and will probably be more obvious in the long run once the old serialization can be removed. I'll refactor as suggested.

**Comment by bratseth** [comment]
Good thanks! I should have warned you about this in advance ...

**Comment by ollivir** [comment]
Please have another look.

**Review by bratseth — APPROVED** [review]
Great

**Comment by freva** [comment]
This broke host-admin....
```
.FelixFramework#011debug#011OSGi bundle 'container-disc' requires install from 'protobuf-java-3.7.0.jar'.
Mar 15 16:57:16 ctlhost1 host-admin.sh: 1552669036.866#011ctlhost1.prod.vaas-aws-us-east-1b.vespa-external.aws.oath.cloud#0111914/1#011jdisc/node-admin#011/com.yahoo.jdisc.core
.FelixFramework#011debug#011Installing OSGi bundle from 'file:/opt/vespa/lib/jars/protobuf-java-3.7.0.jar'.
Mar 15 16:57:16 ctlhost1 host-admin.sh: debug#011Unexpected: com.yahoo.jdisc.application.BundleInstallationException: Unable to cache bundle: file:/opt/vespa/lib/jars/protobuf-
java-3.7.0.jar
Mar 15 16:57:16 ctlhost1 host-admin.sh: at com.yahoo.jdisc.core.FelixFramework.installBundle(FelixFramework.java:83)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at com.yahoo.jdisc.core.ApplicationLoader.init(ApplicationLoader.java:118)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at com.yahoo.jdisc.core.StandaloneMain.run(StandaloneMain.java:42)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at com.yahoo.jdisc.core.StandaloneMain.main(StandaloneMain.java:34)
Mar 15 16:57:16 ctlhost1 host-admin.sh: Caused by: org.osgi.framework.BundleException: Unable to cache bundle: file:/opt/vespa/lib/jars/protobuf-java-3.7.0.jar
Mar 15 16:57:16 ctlhost1 host-admin.sh: at org.apache.felix.framework.Felix.installBundle(Felix.java:3231)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:147)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:120)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at com.yahoo.jdisc.core.FelixFramework.installBundle(FelixFramework.java:158)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at com.yahoo.jdisc.core.FelixFramework.installBundle(FelixFramework.java:168)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at com.yahoo.jdisc.core.FelixFramework.installBundle(FelixFramework.java:168)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at com.yahoo.jdisc.core.FelixFramework.installBundle(FelixFramework.java:81)
Mar 15 16:57:16 ctlhost1 host-admin.sh: ... 3 more
Mar 15 16:57:16 ctlhost1 host-admin.sh: Caused by: java.io.FileNotFoundException: /opt/vespa/lib/jars/protobuf-java-3.7.0.jar (No such file or directory)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at java.base/java.io.FileInputStream.open0(Native Method)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at org.apache.felix.framework.util.SecureAction.getURLConnectionInputStream(SecureAction.java:526)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at org.apache.felix.framework.cache.JarRevision.initialize(JarRevision.java:166)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:76)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:799)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:480)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:148)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:462)
Mar 15 16:57:16 ctlhost1 host-admin.sh: at org.apache.felix.framework.Felix.installBundle(Felix.java:3227)
Mar 15 16:57:16 ctlhost1 host-admin.sh: ... 9 more
```

**Pull request merged**
