### PR TITLE
Jonmv/messagebus avoid config self subscription

### PR DESCRIPTION
**Pull request by jonmv**
@baldersheim please review and merge.

### CODE REVIEW

**Review by hmusum — CHANGES_REQUESTED** [review]
Branch has conflicts that must be resolved. Changes look good to me, although this PR does not live up to its name (more changes coming?)

**Review by baldersheim — APPROVED** [review]

**Comment by jonmv** [comment]
Oof, branch name used as PR name. Will change. Yes, just reading code so far :)

**Comment by jonmv** [comment]
Guess those conflicts were resolved by a revert of something else? :P

**Comment by hmusum** [comment]
Yeah, this one: https://github.com/vespa-engine/vespa/pull/15495

**Pull request merged**
