### PR TITLE
Bjorncs/cleanup

### PR DESCRIPTION
**Pull request by bjorncs**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by baldersheim — APPROVED** [review]
@bratseth and @jonmv PR

**Review by bratseth — APPROVED** [review]

**Comment by jonmv** [comment]
Are we sure the interrupts are not eaten elsewhere?

**Comment by jonmv** [comment]
(ˆڡˆ)v

**Comment by jonmv** [comment]
Ok, it's continually interrupted. Fine.

**Pull request merged**
