### PR TITLE
Add XGBoost missing feature support for Java

### PR DESCRIPTION
**Pull request by lesters**

### CODE REVIEW

**Comment by lesters** [comment]
@bratseth Please review. Probably easiest to start with the xgboost test in the last commit as it validates the rest. Note that this does not enable if-inversion, just makes this ready for Java evaluation (including tensors as arguments) when we eventually make the switch.

**Comment by lesters** [comment]
Also note that this does not change default evaluation as contexts still have double 0.0 as default which will be returned when value is missing. The contexts can now be parameterized with a default value, and for model-evaluation this is now NaN, which I think makes it consistent with evaluation on the backend.

**Review by bratseth — APPROVED** [review]
Great! 

With a default value in model-evaluation I think we can relax the "non-scalars must be bound" to "values not type compatible with the default must be bound" and thus get rid of the missing BitSet. If you agree I can take a stab at this in a new PR after this is merged.

**Comment by lesters** [comment]
Sounds good. I'm not sure however how the interaction between the `put` and `getDouble` would work for `arrayContext` then, as NaN is used as a marker there for non-double compatible values, but that is a separate and solvable issue.

**Pull request merged**
