### PR TITLE
Reapply OpenSSL crypto codec with CMake changes

### PR DESCRIPTION
**Pull request by vekterli**
@havardpe Once more, with feeling. Same as previous PRs except added commit which does not try to do any linking for the object-only libraries. Not sure why the previous attempt built OK both locally and on Travis, but might be something weird related to CMake version semantics?

### CODE REVIEW

**Review by havardpe — APPROVED** [review]

**Comment by havardpe** [comment]
/var/builds/workspace/115429-v3-component-build/BUILD_CONTAINER/build/label/DOCKER-HIGHCPU/app_root/repositories/vespa/vespalib/src/vespa/vespalib/net/tls/impl/openssl_tls_context_impl.cpp: In function 'vespalib::net::tls::impl::BioPtr vespalib::net::tls::impl::{anonymous}::bio_from_string(vespalib::stringref)':
/var/builds/workspace/115429-v3-component-build/BUILD_CONTAINER/build/label/DOCKER-HIGHCPU/app_root/repositories/vespa/vespalib/src/vespa/vespalib/net/tls/impl/openssl_tls_context_impl.cpp:91:42: error: invalid conversion from 'const void*' to 'void*' [-fpermissive]
     BioPtr bio(::BIO_new_mem_buf(str.data(), static_cast<int>(str.size())));
                                  ~~~~~~~~^~
In file included from /usr/include/openssl/ssl.h:152:0,
                 from /var/builds/workspace/115429-v3-component-build/BUILD_CONTAINER/build/label/DOCKER-HIGHCPU/app_root/repositories/vespa/vespalib/src/vespa/vespalib/net/tls/impl/openssl_typedefs.h:5,
                 from /var/builds/workspace/115429-v3-component-build/BUILD_CONTAINER/build/label/DOCKER-HIGHCPU/app_root/repositories/vespa/vespalib/src/vespa/vespalib/net/tls/impl/openssl_tls_context_impl.cpp:2:
/usr/include/openssl/bio.h:668:6: note:   initializing argument 1 of 'BIO* BIO_new_mem_buf(void*, int)'
 BIO *BIO_new_mem_buf(void *buf, int len);
      ^~~~~~~~~~~~~~~
/var/builds/workspace/115429-v3-component-build/BUILD_CONTAINER/build/label/DOCKER-HIGHCPU/app_root/repositories/vespa/vespalib/src/vespa/vespalib/net/tls/impl/openssl_tls_context_impl.cpp: In member function 'void vespalib::net::tls::impl::OpenSslTlsContextImpl::enable_ephemeral_key_exchange()':
/var/builds/workspace/115429-v3-component-build/BUILD_CONTAINER/build/label/DOCKER-HIGHCPU/app_root/repositories/vespa/vespalib/src/vespa/vespalib/net/tls/impl/openssl_tls_context_impl.cpp:227:12: error: '::SSL_CTX_set_ecdh_auto' has not been declared
     if (!::SSL_CTX_set_ecdh_auto(_ctx, 1)) {
            ^~~~~~~~~~~~~~~~~~~~~
/var/builds/workspace/115429-v3-component-build/BUILD_CONTAINER/build/label/DOCKER-HIGHCPU/app_root/repositories/vespa/vespalib/src/vespa/vespalib/net/tls/impl/openssl_tls_context_impl.cpp:227:12: note: suggested alternative: 'SSL_CTX_set_ex_data'
     if (!::SSL_CTX_set_ecdh_auto(_ctx, 1)) {
            ^~~~~~~~~~~~~~~~~~~~~
            SSL_CTX_set_ex_data

**Comment by havardpe** [comment]
Seem to break my local build and factory build as well. Do we have the same version of openssl?

**Comment by vekterli** [comment]
Apparently not 😬 OpenSSL parameter constness is a world of hurt, but has gotten better on newer versions.

`SSL_CTX_set_ecdh_auto` was added in 1.0.2, so I'm guessing you have 1.0.1 or similar

**Comment by havardpe** [comment]
seems 1.0.2 on RHEL6 has been in progress since 2016...

**Comment by havardpe** [comment]
OpenSSL 1.0.1e-fips 11 Feb 2013

**Comment by havardpe** [comment]
Not sure if 1.0.2 is available for RHEL6

**Comment by havardpe** [comment]
Jamie Bainbridge's picture
Red Hat Guru 7132 points
16 April 2018 2:32 AM
Jamie Bainbridge

No, the EL6 OpenSSL package will not be updated to 1.0.2.

EL6 is in "Maintenance Support" development phase where only critical bugs are fixed. New features or package versions are not added anymore.

If you need a newer feature which is in OpenSSL 1.0.2 then you need to upgrade to EL7.

The RHEL product lifecycle is explained at: https://access.redhat.com/support/policy/updates/errata/

CentOS consume the RHEL source so that development process applies to them too.

That being said, just because upstream OpenSSL have ended a version does not mean that Red Hat have ended the version. We still offer full usage and configuration support on RHEL6. If there is a critical-grade security bug in EL6's package, it's possible we'll include just the patch which fixes the vulnerability.

**Comment by vekterli** [comment]
Yeah I'll ensure this stuff compiles cleanly on RHEL6 from now on, just a slightly annoying case of diverging build environments giving me a false sense of security.

**Pull request merged**
