### PR TITLE
use-devtoolset-7

### PR DESCRIPTION
**Pull request by baldersheim**
Use devtoolset-7 and fresh gcc
@aressem @bjorncs @toregge PR

### CODE REVIEW

**Comment by aressem** [comment]
Would probably be good if we tried this manually first, but if this one is merged now, please watch Travis and revert if problems.

**Comment by baldersheim** [comment]
@vekterli flex seems to generate code incompatible with gcc 7 (register not allowed with 1z)

**Comment by bjorncs** [comment]
Note: We need to update https://github.com/vespa-engine/docker-image-dev as well for Travis-CI to build.

**Comment by baldersheim** [comment]
We need to resolve flex issue first...

**Comment by vekterli** [comment]
@baldersheim what kind of output is Flex compilation generating? Is it a deprecation warning or an outright compilation error? If it's the former, setting `-Wno-deprecated-register` should fix it. If it's the latter, we might have to get creative with macros or some other dark deeds...

**Comment by baldersheim** [comment]
ISO C++1z does not allow 'register' storage class specifier [-Werror=register]

**Comment by baldersheim** [comment]
-Wno-error did the trick

**Comment by baldersheim** [comment]
I am not able to push anything to  https://github.com/vespa-engine/docker-image-dev 
Anyone can give permission ?

**Comment by aressem** [comment]
@baldersheim You have permission now (the Vespa team was missing from that repo).

**Comment by baldersheim** [comment]
Will rebase

**Pull request closed without merging**
