### PR TITLE
Add builder for ClusterSpec 

### PR DESCRIPTION
**Pull request by hmusum**

### CODE REVIEW

**Review by bratseth — APPROVED** [review]
LGTM, and already an improvement so feel free to merge. The ClusterSpec is used either to request a desired cluster, or to specify an existing one (perhaps including group). I wonder if we couldn't keep the explicit separation between a request and the specification, like e.g replace "builder" by "request" and "specification" and have a boolean in the builder which only allows the correct fields for that context?

**Comment by hmusum** [comment]
That separation was one of the things I wondered if we should somehow keep. Thanks for the suggestion, I'll look into it.

**Comment by hmusum** [comment]
@bratseth please take a look again

**Comment by bratseth** [comment]
Great! You could also validate that a request don't set group (and vespa-version?).

**Pull request merged**
