### PR TITLE
Keep last 1000 lines sorted in log reader

### PR DESCRIPTION
**Pull request by jonmv**
@freva please review and mereg.

### CODE REVIEW

**Comment by jonmv** [comment]
Or @hmusum :)

**Review by freva — APPROVED** [review]
:1st_place_medal:

**Review by hmusum — APPROVED** [review]

**Comment by jonmv** [comment]
This'll unfortunately only solve minor out-of-order issues. 
The real fix would be a sorted write-cache in whatever code receives log entries and writes them to disk. 
When receiving a log entry which was older than the oldest in the cache, it would have to flush the cache, and start a new file, before adding that entry to the (now empty) cache. 
This would work fine with the merge sort we do over all log files per hour, in the log reader code. (The log writer already produces multiple such files, with overlapping time intervals, occasionally.)

So, the problem is I never found the code that writes these log entires. Is it C++? @arnej27959 you probably know :)

**Comment by arnej27959** [comment]
Is this for reading from log archive? It’s written by the logserver.

**Comment by jonmv** [comment]
Yes, I was pointed in the right direction by @hmusum :)

**Pull request merged**
