### PR TITLE
Jvenstad/deployment pipeline

### PR DESCRIPTION
**Pull request by jonmv**
@bratseth if you want to start peeking, you can see where the `JobRunner` takes you.

### CODE REVIEW

**Comment by bratseth** [comment]
Looks great so far  :-)

**Comment by jonmv** [comment]
Should aim at getting this merged soon >_<

It's mergable now, although unfinished. What do you think? Or are you on vacation? ^^

**Comment by bratseth** [comment]
Yes, I think you should merge it.

**Comment by jonmv** [comment]
Great; would you take another look at https://git.ouroath.com/vespa/hosted/pull/6114, then?

**Pull request merged**
