### PR TITLE
Jvenstad/fix node repo cache

### PR DESCRIPTION
**Pull request by jonmv**
@hmusum or @bratseth please review.

### CODE REVIEW

**Comment by hmusum** [comment]
Looks good to me, but I don't think we can enable this without having a way of switching back to the old implementation. If there is a bug here we need a way back to something that is working (and we can't turn the cache off either, as the way we use zookeeper today does not handle the load).

**Comment by jonmv** [comment]
You mean, if there's a worse bug here than the current one? ;) I guess you may be right, though. Could have two separate code paths for CD vs main, and let it stay in CD for a while?

**Comment by hmusum** [comment]
Yes, if there is a bug we would like to be able to go back to the old implementation. I have no problems with running it in CD, but I think you need to try in a zone with a lot of nodes to be sure the cache works as expected. That would be easiest to do using a feature flag.

**Comment by jonmv** [comment]
PTAL now. 

Feature flag to activate new cache invalidation strategy, which is off by default. 
Invalidate cache also on prepare, in case an inconsistent cache causes prepare to fail.

**Review by hmusum — APPROVED** [review]
Great!

**Pull request merged**
