### PR TITLE
Use newest test framework version

### PR DESCRIPTION
**Pull request by jonmv**
@tokle or @bjorncs please review. We should revert this when our hosted apps have upgraded to the next release.

### CODE REVIEW

**Review by bjorncs — APPROVED** [review]

**Comment by bjorncs** [comment]
Is this temporary or permanent?

**Comment by jonmv** [comment]
Just temporary.

**Comment by jonmv** [comment]
Also not sure we really need it.

**Comment by jonmv** [comment]
Let's just work around this instead, _if_ it turns out to be a problem.

**Pull request closed without merging**
