### PR TITLE
Replace joins with same input with a map

### PR DESCRIPTION
**Pull request by lesters**
@bratseth Please review. Most often used when squaring tensors. Allows this to be done in place.

### CODE REVIEW

**Review by bratseth — COMMENTED** [review]
LGTM but shouldn't this be done in searchlib/../TensorOptimizer?

**Comment by lesters** [comment]
The `TensorOptimizer` is for optimizing tensor evaluation Java side. This is for evaluating the graph on the backend, as it is difficult to recognize if the two inputs to the join are the same. So this is most easily done during graph import.

**Comment by bratseth** [comment]
> The TensorOptimizer is for optimizing tensor evaluation Java side.

Yes you are right of course; this should be an ExpressionTransformer.

> it is difficult to recognize if the two inputs to the join are the same

How so?

**Comment by lesters** [comment]
That is a good point that this could be an additional `ExpressionTransformer`, however the additional effect here was to not generate the function representing the inputs (when an operation is used more than once, we automatically create a function). The effect is that the map can then be done in-place, i.e. without requiring memory allocations. As far as I understand, this is difficult to resonate about on the backend.

**Pull request merged**
