### PR TITLE
Do not expose the headless role in the APIs - only used for keys

### PR DESCRIPTION
**Pull request by oyving**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by smorgrav — APPROVED** [review]
LGTM

**Review by jonmv — APPROVED** [review]

**Review by jonmv — CHANGES_REQUESTED** [review]
I think this will also stop generation of these groups in underlying access control store, which will make it impossible to add users to these roles.

**Comment by jonmv** [comment]
The MockAccessControl and test(s) using it should catch this.

**Comment by oyving** [comment]
But we don't want to add users to these roles - right? They are only used internally when the API is presented with a key?

**Comment by jonmv** [comment]
You're right, of course. Sorry :)

**Review by jonmv — APPROVED** [review]

**Pull request merged**
