### PR TITLE
Make SimpleLinguistics simple again

### PR DESCRIPTION
**Pull request by bratseth**
- Remove SimpleLinguistics config and optional use of Optimaize
- Add Optimaize to OpennlpLinguistics; on by default and config to disable

@arnej27959 please review

### CODE REVIEW

**Comment by arnej27959** [comment]
must also fix 
container-core/src/main/java/com/yahoo/language/provider/SimpleLinguisticsProvider.java

**Comment by arnej27959** [comment]
also
container-search/src/main/java/com/yahoo/search/query/parser/ParserEnvironment.java

**Comment by bratseth** [comment]
Thanks!

**Review by arnej27959 — APPROVED** [review]
looks good to me

**Pull request merged**
