### PR TITLE
Validate that document ids only contain text characters.

### PR DESCRIPTION
**Pull request by geirst**
@baldersheim or @vekterli please review

### CODE REVIEW

**Review by baldersheim — APPROVED** [review]
👍

**Review by vekterli — APPROVED** [review]
LGTM, although I have a slight concern on how this will affect existing corpuses that have already fed IDs with bad chars. Deserialization of messages (get replies, visited docs) from the content layer will fail since DocumentId instances will be created in the process. Guess we'll find out soon enough 😬

**Comment by geirst** [comment]
@bratseth FYI

**Comment by bratseth** [comment]
Summary of discussion: Accept only text characters in incoming documents, but allow anything except 0-byte when retrieving existing documents.

**Comment by geirst** [comment]
@baldersheim and @vekterli please review again. @bratseth FYI

**Review by baldersheim — APPROVED** [review]
👍

**Review by vekterli — APPROVED** [review]
:+1:

**Pull request merged**
