### PR TITLE
Add hint for empty API key

### PR DESCRIPTION
**Pull request by kkraune**

### CODE REVIEW

**Review by mpolden — COMMENTED** [review]
I think this will only generate confusion as this hint may also show up when Auth0 is being used. We don't document that `VESPA_CLI_API_KEY` can be empty anywhere and I think we should keep it that way.

**Comment by kkraune** [comment]
I am open to suggestions. We will point users to an example GitHub Action with Dataplane credentials only, that writes to Vespa Cloud with no warnings - the current version is at https://github.com/vespa-engine/documentation/blob/master/.github/workflows/feed.yml

What do you suggest we do to get to this?

**Comment by baldersheim** [comment]
Complete or close ?

**Comment by mpolden** [comment]
There's a ticket tracking the solution to this.

**Pull request closed without merging**
