### PR TITLE
Restore public method

### PR DESCRIPTION
**Pull request by bratseth**
@jonmv please review

I missed this when reviewing your zone changes - this is a public API.

### CODE REVIEW

**Comment by smorgrav** [comment]
LGTM

**Comment by jonmv** [comment]
Thanks for pointing it out. I already reverted this in a different PR, which has been approved, but for which a sister PR in the hosted repo is still pending (and will be, until New Years). 

Thanks again.!

**Comment by baldersheim** [comment]
Should this one be be merged. Is it necessary for the next release ?

**Comment by bratseth** [comment]
It seems Jonm is saying this will be reverted next year? Not soon enough - I'll merge this then.

**Pull request merged**
