### PR TITLE
Support specifying a distance metric for nearest neighbor search when…

### PR DESCRIPTION
**Pull request by geirst**
… not having a hnsw index.

This also changes the syntax in the sd file to specifying the distance metric in the attribute tag.

@toregge and @arnej27959 please review

### CODE REVIEW

**Review by toregge — APPROVED** [review]

**Review by arnej27959 — APPROVED** [review]
this looks good to me

**Comment by geirst** [comment]
Can be merged when https://github.com/vespa-engine/system-test/pull/716 is approved.

**Comment by arnej27959** [comment]
we also need to update the system test checking MD5 of attributes.def

**Comment by geirst** [comment]
I will fix the system test as well.

**Comment by geirst** [comment]
MD5 checksum updated in https://github.com/vespa-engine/system-test/pull/718.

**Pull request merged**
