### PR TITLE
Revert "Add vespa-maven-plugin to the aggregator maven-plugins "

### PR DESCRIPTION
**Pull request by bjorncs**
Reverts vespa-engine/vespa#9465

### CODE REVIEW

**Comment by bjorncs** [comment]
Breaks build on Travis-CI

**Review by freva — APPROVED** [review]

**Comment by jonmv** [comment]
What broke?

**Comment by bjorncs** [comment]
The maven plugin aggregator should only listed the Maven plugins required for building Vespa itself. The "vespa-maven-plugin" has multiple Vespa dependencies which are not built as part of the bootstrap process.

**Comment by jonmv** [comment]
Aha, thanks for the explanation.

**Pull request merged**
