### PR TITLE
Exclude scala-xml to prevent import-package for its packages.

### PR DESCRIPTION
**Pull request by gjoranv**
FYI: @lesters 

- scala-xml is only used to generate config classes, and is not
  needed or provided runtime.

### CODE REVIEW

**Comment by bjorncs** [comment]
Build failed on Travis. Btw, @lesters' issue disappeared after he did a `mvn clean install`. It seems like stale artifacts could have been the problem.

**Comment by gjoranv** [comment]
@bjorncs. PTAL. Hopefully, build goes green now. 6 lines of scala to 20 lines Java with less detailed error message. But there should be no more involuntary loading of scala-xml classes.

**Comment by gjoranv** [comment]
Failed in standalone-container this time..

**Review by bjorncs — APPROVED** [review]
Nice :) LGTM

**Pull request merged**
