### PR TITLE
A tensor field that specifies hnsw index parameters must also specify…

### PR DESCRIPTION
**Pull request by geirst**
… 'index' in 'indexing'.

@bratseth please review
@jobergum FYI

### CODE REVIEW

**Review by bratseth — APPROVED** [review]
👍

**Comment by hmusum** [comment]
You're sure there are no existing applications with this problem? We would fail to deploy an existing app with this issue when upgrading Vespa in such a system and the upgrade would fail.

**Comment by geirst** [comment]
No, we are not sure about that. But without this validation, you can deploy an application thinking you are using an hnsw index when you are not. So it is better to fail at deploy time so the application can be fixed.

**Comment by kkraune** [comment]
I will have a go at existing apps

**Comment by hmusum** [comment]
Yes, I agree that this needs to be validated at deploy time. The problem is that if there are existing apps with this issue the rollout to production will be blocked and we cannot get new releases out until the customer has fixed the application or we have rolled back infrastructure to previous version manually. 

There is an internal ticket 'Allow for "warn-only" config validations' that is related to this.

**Pull request merged**
