### PR TITLE
Deprecate binary encoding outside VDS

### PR DESCRIPTION
**Pull request by bratseth**

### CODE REVIEW

**Comment by arnej27959** [comment]
Henning should look at this - can we switch to using protobuf serialization?

**Review by baldersheim — APPROVED** [review]

**Comment by baldersheim** [comment]
Yes, we can add a new map entry and let the backend handle both.
If we are quick and enable protobuf now, we can drop the old one at 8.

**Comment by bratseth** [comment]
I don't think we need a major version change to do that?

**Comment by baldersheim** [comment]
Currently we require you have a recent MAJOR version in order to do rolling upgrade to next MAJOR.
We do not have any such requirement/procedure/enforcement for minor upgrades. We should have that as that would make it a lot easier to maintain our code base.

**Comment by bratseth** [comment]
Good point, how about https://github.com/vespa-engine/frontpage/pull/232
Though we already say that if you don't want to maybe lose your data you need to upgrade content nodes through every minor so I'm not sure this makes any difference in practice.

**Comment by baldersheim** [comment]
@geirst @vekterli FYI

**Comment by bratseth** [comment]
How about changing the content node data compatibility to 2 months as well?
Requiring everyone to goo through every minor seems a bit unrealistic.

**Pull request merged**
