### PR TITLE
Always consider on-prem node-admin to be up

### PR DESCRIPTION
**Pull request by hakonhall**

### CODE REVIEW

**Comment by hakonhall** [comment]
We'll test out this value in various zones first, before flipping the default. Adding DO_NOT_MERGE label.

**Review by hmusum — APPROVED** [review]
Looks OK, merge provided that we have tested it out in some zone(s) first

**Comment by hakonhall** [comment]
We're ready to test host-admin in CD, so merging this PR.

However this PR will roll out to main too, so from now on we're unable to catch node admins that doesn't come up.

**Comment by hakonhall** [comment]
FYI @freva

**Pull request merged**
