### PR TITLE
Geirst/add buckets pending stats on clustercontroller status page

### PR DESCRIPTION
**Pull request by geirst**
@vekterli please review
@toregge FYI

### CODE REVIEW

**Review by vekterli — APPROVED** [review]
:+1: only nitpicks

**Comment by vekterli** [comment]
As an aside, we know there is some _O(n^2)_ behavior here for the status page rendering, but since _n_ is expected to be small we'll observe if it's even measurable in practice before adding complexity to reduce complexity, so to speak.

**Comment by geirst** [comment]
@vekterli PTAL

**Review by vekterli — APPROVED** [review]
:+1:

**Pull request merged**
