### PR TITLE
Jonmv/more validation

### PR DESCRIPTION
**Pull request by jonmv**
@hmusum please review.

### CODE REVIEW

**Review by hmusum — APPROVED** [review]
LGTM. We are sure there are no applications or other data that uses now invalid names?

**Review by hmusum — CHANGES_REQUESTED** [review]
Unit test failed:

eTest
15:05:05 [ERROR] test(com.yahoo.vespa.hosted.controller.api.integration.deployment.JobTypeTest)  Time elapsed: 0.064 s  <<< ERROR!
15:05:05 java.lang.IllegalArgumentException: region name must match '[a-z]([a-z0-9-]*[a-z0-9])*', but got: 'snøhetta'

**Comment by jonmv** [comment]
Can't be absolutely sure. 

Haha, nice, I added those "regions" last week :)

**Comment by jonmv** [comment]
I think I found that it's highly unlikely the application names will no longer match. The `.` is the only real issue here, and we shouldn't be using that ourselves, at least (in system tests).

**Pull request merged**
