### PR TITLE
Define enable logserver flag.

### PR DESCRIPTION
**Pull request by hakonhall**
There are 2 strategies to guard features in the config model:
1. Make FlagSource injectable and Flags accessible in the config model. The flags bundle would need to be a preinstalled bundle and backwards compatible until old config models no longer exists.
1. Pass resolved flag values to config model as part of context or the like.

This PR tries (2): It resolves a new enable-logserver flag in the ModelContextImpl in the configserver bundle, which is passed through various config-model-api calls. The ModelContext interface itself is defined in config-model-api and accessible by config-model. It reuses the ModelContext.Properties interface, which already seems to be filled with feature flag like members.

For enabling logserver, we really need a boolean in DomAdminV4Builder, and the best way seems to be through DeployState and its DeployProperties. DeployProperties unfortunately does not just expose ModelContext.Properties, but builds, copies, and exposes most/all fields incurring a big overhead for each feature flag added or removed.

It would be great if someone can confirm or deny whether it's a good idea to expose Properties and remove all the redundancy. Perhaps there's a good reason for the indirection. This PR is NOT ready for merge until this is resolved and I have cleaned up the code either way.

The problems with backwards compatibility of (1) is certainly still there with (2), but is kept to ModelContext.Properties in config-model-api, which is an obvious place to take care of backwards compatibility instead of in the flags module where one might not think about it.

### CODE REVIEW

**Comment by hakonhall** [comment]
I'll pop by to discuss this with you tomorrow @hmusum

**Comment by hakonhall** [comment]
FYI @olaaun

**Comment by hakonhall** [comment]
Conclusions from discussion is that the strategy in this PR (2) seems viable:
* ModelContext + ConfigModelContext (which will have access to ModelContext.Properties through deployState DeployContext) should be accessible or nor far away from any code that wants to test a feature flag.
* I'll look into exposing ModelContext.Properties directly from DeployProperties to avoid excessive wiring. Possibly also ConfigModelContext from deploy state's DeployProperties' Properties (too many indirections).
* Instead of adding a new getter enableLogServer() on Properties, I'll reuse useDedicatedNodeForLogserver() which was made for exactly this same feature.

**Review by hmusum — APPROVED** [review]

**Comment by hakonhall** [comment]
FYI Merging with master (7) caused 0 conflicts and same diff as before.

**Pull request merged**
