### PR TITLE
Jonmv/remove tags wiring

### PR DESCRIPTION
**Pull request by jonmv**
@bratseth

### CODE REVIEW

**Review by bratseth — APPROVED** [review]
Great! Now we _really_ can never use it for something else, which i quite like ...

**Comment by bratseth** [comment]
Failed to execute goal com.yahoo.vespa:abi-check-plugin:8-SNAPSHOT:abicheck (default) on project config-model-api: ABI spec mismatch.

**Comment by jonmv** [comment]
Yes, fixed. Removed method is in use in older models, just not on my branching point ...

**Review by bratseth — APPROVED** [review]

**Comment by jonmv** [comment]
Sorry, accidentally removed a line of xml unit test helper. Resulted in killing the dependency instead. PTAL.

**Review by mpolden — APPROVED** [review]

**Pull request merged**
