### PR TITLE
Add coverage info to access log

### PR DESCRIPTION
**Pull request by baldersheim**
@bratseth @frodelu @jobergum PR

### CODE REVIEW

**Comment by bratseth** [comment]
Couldn't it be done the other way around as we discussed? This is one big layer violation where search specific concepts are pulled into a generic package.

**Comment by baldersheim** [comment]
There is already an even bigger violation with HitCounts so I thought that hiding it there would be fine.
Also the existing key-value support only support a flat structure for adding either a single value or an array, all of type string. So it would a very ugly, or we would add a better thing than key-value.

**Review by bratseth — APPROVED** [review]
Well, this is terrible  :-)

**Comment by baldersheim** [comment]
:)

**Pull request merged**
