### PR TITLE
Deprecate score-threshold

### PR DESCRIPTION
**Pull request by bratseth**
@arnej27959 I don't think we're going to bring that back?

### CODE REVIEW

**Comment by arnej27959** [comment]
I’m not sure if the part about RISE is really true. Some people also wanted a distance threshold for ANN, and said they wanted it to be similar to this threshold, for some reason. @geirst can you check if this score threshold is potentially useful?

**Comment by geirst** [comment]
The score threshold is no longer used by the WeakAnd operator in the backend. RISE is long gone. I think it's fine to remove.

**Review by geirst — APPROVED** [review]
👍

**Review by arnej27959 — APPROVED** [review]
so the WandItem score threshold is in use, but not the WeakAndItem one? very well..

**Pull request merged**
