### PR TITLE
Revert "Bjorncs/jdisc http2 preps [run-systemtest]"

### PR DESCRIPTION
**Pull request by hmusum**
Reverts vespa-engine/vespa#17366

Build fails:

[ERROR] Class com.yahoo.jdisc.http.ConnectorConfig$Builder: Extra method public com.yahoo.jdisc.http.ConnectorConfig$Builder http2Enabled(boolean)
[ERROR] Class com.yahoo.jdisc.http.ConnectorConfig: Extra method public boolean http2Enabled()

### CODE REVIEW

**Comment by jonmv** [comment]
This is a reapply, not a revert, though. Hmm ...

**Comment by jonmv** [comment]
Not sure we really need that config def, though—nothing was upgraded to the new version?

**Comment by bjorncs** [comment]
We just need to update the abi-spec. I'll make a new PR.

**Comment by hmusum** [comment]
I have no idea, @bjorncs please fix

**Comment by bjorncs** [comment]
Yes, the previous PR was a revert, this would actually reapply the changes.

**Pull request closed without merging**
