### PR TITLE
Stop using legacy proton metrics that have been removed on Vespa 7.

### PR DESCRIPTION
**Pull request by geirst**
@toregge please review
@arnej27959 FYI

### CODE REVIEW

**Review by arnej27959 — APPROVED** [review]
looks fine to me

**Comment by yngveaasheim** [comment]
This implies we need to go through all dashboards and update metric names for non-working graphs.

**Comment by geirst** [comment]
@yngveaasheim yes, you are correct. This commit doesn't change the names outputted, but it will add the dimension 'documenttype'. Later we will remove all renaming of metrics in this file.

**Review by toregge — COMMENTED** [review]
LGTM

**Pull request merged**
