### PR TITLE
- Add fieldlist to docsum request.[run-systemtest]

### PR DESCRIPTION
**Pull request by baldersheim**
- Only return fields requested from the backend.

@bratseth @geirst @toregge PR

### CODE REVIEW

**Review by bratseth — APPROVED** [review]
👍

**Review by geirst — APPROVED** [review]
👍  But I think searchlib/src/tests/engine/proto_converter/proto_converter_test.cpp should be extended.

**Review by toregge — APPROVED** [review]
Consider adding similar wiring of field list for streaming search.

**Comment by baldersheim** [comment]
Test added, and conversion done.
Will look into streaming search separately.

**Pull request merged**
