### PR TITLE
Remove 'attribute: huge' from config def file and C++ code.

### PR DESCRIPTION
**Pull request by geirst**
@toregge please review

### CODE REVIEW

**Review by toregge — APPROVED** [review]

**Comment by geirst** [comment]
@gjoranv or @arnej27959 please merge when factory is ok

**Comment by gjoranv** [comment]
Merged in another PR, right @geirst ?

**Comment by toregge** [comment]
The original changes in this PR (`Remove 'attribute: huge' from config def file and C++ code.`) have not been merged.

**Comment by gjoranv** [comment]
Superseded by #22911

**Pull request closed without merging**
