### PR TITLE
Avoid spotbugs annotations by including them in provided scope to tri…

### PR DESCRIPTION
**Pull request by baldersheim**
…ck compiler.

@bjorncs PR

### CODE REVIEW

**Review by bjorncs — DISMISSED** [review]
FYI Spotbug-annotation is an OSGi bundle. Bundles embedding zkfacade will fail to load at runtime.

**Comment by bjorncs** [comment]
@gjoranv Is it possible to deny-list certain packages from being imported in bundle-plugin configuration?

**Comment by baldersheim** [comment]
clustercontroller-core does the same thing and that seems to work fine.

**Comment by bjorncs** [comment]
@baldersheim Ok, let's try this in CI then.

**Comment by gjoranv** [comment]
> @gjoranv Is it possible to deny-list certain packages from being imported in bundle-plugin configuration?

Not out of the box. Probably should be.

**Comment by baldersheim** [comment]
Closing in favor of #30854

**Pull request closed without merging**
