### PR TITLE
Add relevance @k metric tracking

### PR DESCRIPTION
**Pull request by lesters**
@yngveaasheim PTAL. For discussion.

### CODE REVIEW

**Comment by lesters** [comment]
BTW, this does not export the metric yet.

**Comment by lesters** [comment]
This PR is now complete, just pending architectural review for metric names.

**Review by yngveaasheim — APPROVED** [review]
Looks good to me. 👍

**Comment by lesters** [comment]
@yngveaasheim Final update after architectural review. Please verify before I merge.

**Comment by yngveaasheim** [comment]
👍

**Pull request merged**
