### PR TITLE
Arnej/add builder lambda convenience

### PR DESCRIPTION
**Pull request by arnej27959**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

@gjoranv please review
@hmusum @baldersheim FYI

### CODE REVIEW

**Review by gjoranv — APPROVED** [review]
It would be nice if a few unit tests were updated to use the new method. Perhaps it's even scriptable?

**Comment by arnej27959** [comment]
> It would be nice if a few unit tests were updated to use the new method.

Agreed, which unit tests did you have in mind?
Looking at .def files, all of these seem like candidates:

config-lib/src/test/resources/configdefinitions/test.function-test.def
config/src/test/resources/configdefinitions/function-test.def
config/src/test/resources/configs/def-files/function-test.def

**Comment by gjoranv** [comment]
How about

- ConfigInstanceBuilderTest.createVariableAccessBuilder
- ConfigInstanceUtilTest

**Comment by gjoranv** [comment]
Great!

**Pull request merged**
