### PR TITLE
support binary formats with cell type in reference implementation

### PR DESCRIPTION
**Pull request by havardpe**
@arnej27959 please review
@lesters FYI

### CODE REVIEW

**Review by arnej27959 — APPROVED** [review]
looks good to me

**Comment by aressem** [comment]
Merge stop ?

**Comment by havardpe** [comment]
sorry about that, should be relatively safe though, since it is mostly testing code related to the non-production tensor implementation.

**Comment by bratseth** [comment]
The other problems are that the slot machine gets reset if we need luck to get the 3 cherries on it, and that a delay between runs are introduced. (In general - not right now since we have something that needs fixing.)

**Comment by havardpe** [comment]
It would be nice if there was a way to force the commit stop checker to re-run on all pull requests when a merge stop was introduced...

**Pull request merged**
