### PR TITLE
Add generation counter to StorageComponent to detect if repos have ch…

### PR DESCRIPTION
**Pull request by baldersheim**
…anged and need reload.

Happy path where you do not need any reload is a single atomic relaxed load as opposed to at least 3 atomic locked instructions.

@vekterli and @toregge PR
@vekterli if you think this is a feasible way I will add tests and complete the PR
This should significantly reduce cost for get() and test-and-set operations.

### CODE REVIEW

**Review by toregge — APPROVED** [review]
Consider _type_repo_generation and _last_type_repo_generation instead of _generation and _lastGeneration.

**Review by vekterli — APPROVED** [review]
:+1:

**Comment by vekterli** [comment]
Eventually we very much want to move away from the "the world changes under your feet" model of reconfiguration, but this is a good stop-gap before then.

**Comment by baldersheim** [comment]
yes, it is a step on the way to a better world.
@toregge I kept a general name as I intend to also use it for some of the other synchronized members sometime in a not too distant future.

**Pull request merged**
