### PR TITLE
Use yolean Exceptions instead of IOExceptionUtil

### PR DESCRIPTION
**Pull request by hakonhall**

### CODE REVIEW

**Review by bratseth — COMMENTED** [review]
I don't think we should have special handling of NoSuchFileException in a general Exception class, perhaps you can parametrize it?

**Comment by hakonhall** [comment]
Something like this?

**Comment by bratseth** [comment]
Yes, but it still mentions IOException, I guess that's hard to avoid since you want to throw UncheckedIOException. Perhaps you should put these in vespajlib/../com.yahoo.io?

**Comment by hakonhall** [comment]
This class can define overloads/methods to uncheck other exceptions too, it's just that IOException should be wrapped to UncheckedIOException.

**Comment by bratseth** [comment]
Ah, right. It's good to go then.

**Pull request merged**
