### PR TITLE
Allow override of keep-rank-count via the internal vespa.hitcollector…

### PR DESCRIPTION
**Pull request by baldersheim**
….arraysize rank param.

@havardpe PR
This should help with #24899

### CODE REVIEW

**Comment by baldersheim** [comment]
@bratseth PR
@jobergum FYI

**Review by havardpe — APPROVED** [review]

**Comment by baldersheim** [comment]
@bratseth You should verify the java changes.

**Review by bratseth — APPROVED** [review]
LGTM!

**Comment by geirst** [comment]
@baldersheim : Can you update the reference documentation as well? (https://docs.vespa.ai/en/reference/query-api-reference.html#ranking)

**Comment by baldersheim** [comment]
Documented in https://github.com/vespa-engine/documentation/pull/2735

**Pull request merged**
