### PR TITLE
Jonmv/no more serviceview/v1

### PR DESCRIPTION
**Pull request by jonmv**
@freva don' merge yet.

### CODE REVIEW

**Comment by jonmv** [comment]
@gjoranv perhaps the second commit enables some more cleanup as well?

**Comment by jonmv** [comment]
We must also expose `/orchestrator/v1/` through `/application/v4/` before we can do this, so we have a starting point for getting the services and hosts.

**Review by freva — APPROVED** [review]
:trophy:

**Comment by gjoranv** [comment]
Please revert the changes related to jersey bundles. configserver provides jersey to the controller components.

**Comment by jonmv** [comment]
Already done in #22154

**Comment by gjoranv** [comment]
Thanks, and great job removing serviceview. Only orchestrator uses Jersey client in vespa-engine now.

**Pull request merged**
