### PR TITLE
Remove hardwareFailureType

### PR DESCRIPTION
**Pull request by freva**
This was replaced with `hardwareFailureDescription` in #3103

### CODE REVIEW

**Comment by hakonhall** [comment]
Hm, I have a feeling we should really keep some type of classification of hw failures. Perhaps 'type' is not correct, but say... we'd like a metric for the various type of hw and spec failures. This could be very valuable when talking to openstack/siteops. My experience is that we have a lot of disk hw failures, and could bring this up with openstack.

So, an alternative could be to save the various metrics to db, and to have the controller export a metric.

**Comment by freva** [comment]
`hardwareFailureType` in its former form is gone already anyway. Currently it's just mirroring `hardwareFailureDescription`, so I'll merge this PR and we'll have to add the type in some later PR.

**Comment by mpolden** [comment]
This changed the API which we should try to avoid. At the very least we should try to keep it backwards compatible with old field names when we rename or introduce new ones.

It would be great if we could include a FYI to at least one module owner in the future, especially for API changes.

**Comment by hakonhall** [comment]
You mean because there may be non-git code that depends on the API, or for discussions about API changes?

**Comment by mpolden** [comment]
@hakonhall In my opinion we should never change the API, but yes, mainly because there might be usages of the API that we forget to change or that are not revealed by usage search.

**Comment by bratseth** [comment]
We should never break the API (i.e files can be added but not removed).
If we really need to break it we can create a new version and keep the old one around for a while. That is what the version in the url path is for.

**Pull request merged**
