### PR TITLE
Flavor interface

### PR DESCRIPTION
**Pull request by freva**
# Summary of the changes

## Changes to `Flavor`:
* Is now an `interface`. 

Following methods were **renamed**:
`name()` -> `flavorName()` `name()` cannot be overwritten for an enum (`VespaFlavor`)
`getMinMainMemoryAvailableGb()` -> `memory().sizeInGb()`
`getMinDiskAvailableGb()` -> `disk().sizeInBase10Gb()`
`hasFastDisk()` -> `disk().isFast()`
`getBandwidth()` -> `bandwidth().mbits()`
`getMinCpuCores()` -> `cpu().cores()`
`getType()` -> `environment()` This was called environment everywhere (`flavors.def`, `VespaFlavors`, `/nodes/v2/` API) except here. The enum was also renamed `Type` -> `Environment`, and `undefined` value has been removed. Only used as default in `flavors.def`.

Following methods were **removed**:
`getDescription()` Only used by `/nodes/v2/` API, I don't think this provides any value. The description (in practice) can be derived by fields we already show in the API
`isDocker()` Not used anywhere
`getIdealHeadroom()` Not used since 6.282
`isCanonical()` Only used inside the class, is now a private method in the interface
`isLargerThan(Flavor)` Only used by `provision-service`, but only in a non-general way (for example, `provision-flavor` doesn't care to compare bandwidth or if disk is fast)
`freeze()` Moved to `ConfigFlavor`

Following methods were **unchanged**:
`cost()`, `isStock()`, `canonicalName()`, `isRetired()`, `satisfies(Flavor)`, `replaces()`

## Changes to `flavors.def`:
Following fields were **renamed**:
`minMainMemoryAvailableGb` -> `memory.sizeInGb`
`minDiskAvailableGb` -> `disk.sizeInGb`
`fastDisk()` -> `disk.fast`
`bandwidth()` -> `bandwidth.mbits`
`minCpuCores()` -> `cpu.cores`

Following fields were **removed**:
`description`, `idealHeadroom`

## Changes to `NodeFlavors`:
* Is now an `interface`

The goal of this change is to make it easier to work with `Flavor`/`NodeFlavors` by not having to deal with the config and to facilitate some other changes (see internal PRs).

### CODE REVIEW

**Review by bratseth — APPROVED** [review]
I've checked for usages of Flavor in applications on our cloud and there are none (as expected). External users have zero use for this, so I think you can go ahead and change whatever you want in Flavor,.

**Comment by freva** [comment]
Other considerations: Ideally `bandwidth()` and `disk().isFast()` should return an `Optional`, which for docker flavors would be empty, and the value would be derived from the parent flavor. Also there would need to be a way to compute `cost()` as a function of parent somehow. Then, all docker flavors could be generated on demand rather than being explicitly defined. But this seems to be a way to big of a change for now.

**Review by mpolden — APPROVED** [review]
Great!

**Comment by hmusum** [comment]
Deploying apps fail in CD with the followin in vespa log on config servers:
`[2019-03-09 06:02:09.537] ERROR   : configserver     Container.com.yahoo.vespa.config.server.rpc.GetConfigProcessor
	Unexpected error handling config request
	exception=
	java.lang.IncompatibleClassChangeError: Found interface com.yahoo.config.provision.Flavor, but class was expected
	at com.yahoo.vespa.model.admin.amender.MetricsProxy.lambda$hostedVespaGlobalDimensions$2(MetricsProxy.java:276)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.yahoo.vespa.model.admin.amender.MetricsProxy.hostedVespaGlobalDimensions(MetricsProxy.java:275)
	at com.yahoo.vespa.model.admin.amender.MetricsProxy.getConfig(MetricsProxy.java:227)
	at com.yahoo.cloud.config.metricsproxy.MetricsproxyConfig$Builder.dispatchGetConfig(MetricsproxyConfig.java:233)
	at com.yahoo.config.model.producer.AbstractConfigProducer.cascadeConfig(AbstractConfigProducer.java:212)
	at com.yahoo.vespa.model.VespaModel.populateConfigBuilder(VespaModel.java:365)
	at com.yahoo.vespa.model.VespaModel.getConfig(VespaModel.java:360)`

**Pull request merged**
