### PR TITLE
Update InternalStepRunner.java

### PR DESCRIPTION
**Pull request by jonmv**

### CODE REVIEW

**Comment by jonmv** [comment]
@mpolden please review. iPhone Edit, so need PR job :)

**Comment by jonmv** [comment]
Urgh :)

**Review by mpolden — APPROVED** [review]
LGTM, but why?

**Comment by jonmv** [comment]
The problems we SAW yesterday, where deployments for one app were failing due to restarts which required reshuffling of docs.

**Comment by jonmv** [comment]
Needs unit test uodates too. Eillgave to wait :op

**Pull request closed without merging**
