### PR TITLE
Add org.apache.httpcomponents httpcore for mvn install

### PR DESCRIPTION
**Pull request by sunmeng007**
Hi,
    when i mvn install in my mac 10.13.2,it can not compile,so i add httpcore in these poms which can not compile, resolve it.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by sunmeng007** [comment]
I have agree CLA

**Comment by gjoranv** [comment]
@sunmeng007 Which maven and Java versions are you using? Could you please add the _complete_ output of `mvn -v`. Thanks!

**Comment by sunmeng007** [comment]
@gjoranv 
vespa git:(mengsun) ✗ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

vespa git:(mengsun) ✗ mvn -v
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /Users/sunmeng/apache-maven-3.3.9
Java version: 1.8.0_77, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.2", arch: "x86_64", family: "mac"

**Comment by gjoranv** [comment]
@sunmeng007 Could you please try upgrading to maven 3.5, e.g. via Homebrew (`brew install maven`).  `httpcore` should be pulled in transitively by `httpclient`, so your additions should not be necessary. If upgrading doesn't help, I need more info on how you are building.

**Comment by sunmeng007** [comment]
@gjoranv 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:testCompile (default-testCompile) on project jdisc_http_service: Compilation failure: Compilation failure: 
[ERROR] /Users/sunmeng/Desktop/recommend/sunmeng007/vespa/jdisc_http_service/src/test/java/com/yahoo/jdisc/http/server/jetty/SimpleHttpClient.java:[5,23] 程序包org.apache.http不存在
[ERROR] /Users/sunmeng/Desktop/recommend/sunmeng007/vespa/jdisc_http_service/src/test/java/com/yahoo/jdisc/http/server/jetty/SimpleHttpClient.java:[6,23] 程序包org.apache.http不存在
[ERROR] /Users/sunmeng/Desktop/recommend/sunmeng007/vespa/jdisc_http_service/src/test/java/com/yahoo/jdisc/http/server/jetty/SimpleHttpClient.java:[7,23] 程序包org.apache.http不存在
[ERROR] /Users/sunmeng/Desktop/recommend/sunmeng007/vespa/jdisc_http_service/src/test/java/com/yahoo/jdisc/http/server/jetty/SimpleHttpClient.java:[12,30] 程序包org.apache.http.config不存在
[ERROR] /Users/sunmeng/Desktop/recommend/sunmeng007/vespa/jdisc_http_service/src/test/java/com/yahoo/jdisc/http/server/jetty/SimpleHttpClient.java:[13,30] 程序包org.apache.http.config不存在
[ERROR] /Users/sunmeng/Desktop/recommend/sunmeng007/vespa/jdisc_http_service/src/test/java/com/yahoo/jdisc/http/server/jetty/SimpleHttpClient.java:[16,30] 程序包org.apache.http.entity不存在
[ERROR] /Users/sunmeng/Desktop/recommend/sunmeng007/vespa/jdisc_http_service/src/test/java/com/yahoo/jdisc/http/server/jetty/SimpleHttpClient.java:[17,30] 程序包org.apache.http.entity不存在
[ERROR] /Users/sunmeng/Desktop/recommend/sunmeng007/vespa/jdisc_http_service/src/test/java/com/yahoo/jdisc/http/server/jetty/SimpleHttpClient.java:[22,28] 程序包org.apache.http.util不存在
[ERROR] /Users/sunmeng/Desktop/recommend/sunmeng007/vespa/jdisc_http_service/src/test/java/com/yahoo/jdisc/http/server/jetty/SimpleHttpClient.java:[140,17] 找不到符号
[ERROR]   符号:   类 HttpEntity
[ERROR]   位置: 类 com.yahoo.jdisc.http.server.jetty.SimpleHttpClient.RequestExecutor

vespa git:(master) ✗ mvn -v
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T15:58:13+08:00)
Maven home: /Users/sunmeng/apache-maven-3.5.2
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.2", arch: "x86_64", family: "mac"

**Comment by gjoranv** [comment]
Are you building directly under mac os, or inside a container or vm?

Could you please try to run `mvn -B dependency:tree` on these three modules, and look for 'httpcomponents'. You should see httpclient and httpcore like this:

jdisc_http_service:
```
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.3.6:test
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.3.3:test
```

container-disc:
```
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.3.6:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.3.3:compile
```

node-maintainer:
```
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.3.6:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.3.3:compile
```

**Comment by sunmeng007** [comment]
@gjoranv 
I am in mac os
jdisc_http_service git:(master) ✗ mvn -B dependency:tree | grep httpcomponents
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.3.6:test
[INFO] +- org.apache.httpcomponents:httpmime:jar:4.3.6:test

container-disc git:(master) ✗ mvn -B dependency:tree | grep httpcomponents
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.3.6:compile

node-maintainer git:(master) ✗ mvn -B dependency:tree | grep httpcomponents
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.3.6:compile


jdisc_http_service git:(mengsun) ✗ mvn -B dependency:tree | grep httpcomponents
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.3.6:test
[INFO] +- org.apache.httpcomponents:httpcore:jar:4.3.3:test
[INFO] +- org.apache.httpcomponents:httpmime:jar:4.3.6:test

container-disc git:(mengsun) ✗ mvn -B dependency:tree | grep httpcomponents
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.3.6:compile
[INFO] +- org.apache.httpcomponents:httpcore:jar:4.3.3:compile

node-maintainer git:(mengsun) ✗ mvn -B dependency:tree | grep httpcomponents
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.3.6:compile
[INFO] +- org.apache.httpcomponents:httpcore:jar:4.3.3:compile

**Comment by gjoranv** [comment]
I see that you ran each module twice. What's the difference between the two runs? Can you create a gist with the full output of dependency:tree for e.g. container-disc without your changes? Maybe that could give me some clue of why you're seeing the "package not found" error.

**Comment by sunmeng007** [comment]
@gjoranv 
hi,first run,it is on master branch.second run,it is on my branch mengsun.

**Comment by bratseth** [comment]
I think we can close this?

**Comment by gjoranv** [comment]
Yes, I'm unable to reproduce the problem.

**Pull request closed without merging**
