### PR TITLE
Reduce number of config server worker threads from default (500)

### PR DESCRIPTION
**Pull request by bjorncs**
Reduce the number of worker threads will have a positive impact on
the memory consumption.

### CODE REVIEW

**Comment by hmusum** [comment]
This changes the default. That is considered ok also for the large installations we already have?

**Review by hmusum — APPROVED** [review]

**Comment by bjorncs** [comment]
It should be more than enough as long as the queries are not very expensive (<100ms).

**Comment by bratseth** [comment]
It's not uncommon that we tell people to increase the number of threads in this pool, which indicates that reducing it will cause problems, so I don't think we can do this.

I think we could change to prestart just 100 of the 500 threads though. We need to introduce a new setting for that.

**Comment by hmusum** [comment]
@bratseth this changes the number of threads for the config server only, nothing else.

**Comment by bratseth** [comment]
Ah, ok nm then  :-)

**Pull request merged**
