### PR TITLE
Balder/balder arnej default down

### PR DESCRIPTION
**Pull request by baldersheim**
@arnej27959 and @bratseth PR
Now it is down until proven up. We need to discuss the passive aggressive case which has changed behaviour.

### CODE REVIEW

**Review by arnej27959 — APPROVED** [review]
i think this is necessary to get the initial start-up behaviour right, but it's hard to say if it will have even further side-effects.  on a minor note i have looked more at DirectSearchTestCase and will have some minor improvements (ensuring that tests pass for the right reasons) later.  Also, we may want to change the other set of NodeMonitor/ClusterSearcher classes to have the same initially-down logic also, to make it slightly easier to understand what the rules are.

**Comment by bratseth** [comment]
The regular search code path uses the prelude cluster monitor.
External connectors (such as HTTP services) *and* the new Java dispatch uses the search cluster monitor.

The idea is that the old prelude cluster monitor can die when we have switched to the new Java dispatch.

We used to be initially up, but of course that is not ideal so I changed the prelude cluster monitor to initially down earlier. I guess the problem that is attempted solved here is that the new Java dispatch now uses the new search cluster monitor where this change had not been made which cause the container to believe it is up anyway.

However, when we change to initially down we encounter a new problem: When the container is already up but is reconfigured due to downstream topology changes we get a new cluster monitor instance, which from inside it looks identical to the bootstrapping situation, such that it will decide to mark nodes as down, causing the container to go out of service on reconfiguration.

To make this work correctly for the search cluster monitor I think we need to make the same change as I did to the prelude cluster monitor, which is to 1) explicitly track whether we have information or not (so we have 3 states "is working", "is not working" and "unknown status"), and 2) only update the VIP status when we have a known status. This works in tandem with the change in VipStatus to store the current in/out of rotation state of clusters such that it survives reconfiguration to make sure we only change status when we have positive information from the nodes that status has changed.

... so I suggest closing this and I'll make the necessary changes to the search cluster and node monitor.

**Comment by bratseth** [comment]
Yes, but the problem with that is that we need to set up everything to prove that it is up.

**Comment by bratseth** [comment]
Yes, there are no dependencies the wrong way for the search cluster monitor, so I agree that would work too.

**Comment by arnej27959** [comment]
if the vipStatus for a cluster is supposed to survive reconfiguration, must we also make sure to use a key that will match between old and new SearchCluster instance?

**Comment by bratseth** [comment]
Yes, good point.

**Comment by baldersheim** [comment]
I think all is good in this area now.

**Pull request closed without merging**
