### PR TITLE
No CPU capping in test zones

### PR DESCRIPTION
**Pull request by hmusum**
Try without CPU capping to see if it helps with first query after start taking a long time.

### CODE REVIEW

**Review by bratseth — APPROVED** [review]

**Review by baldersheim — APPROVED** [review]

**Comment by bratseth** [comment]
If this works we need to followup somehow since staging tests should support performance validation.

**Comment by freva** [comment]
This value is already controlled by the `container-cpu-cap` feature flag, except for the method changed in this PR which bypasses the flag entirely. In this case I'd recommend just using the flag, then change the code if you want it to be permanent.

Though ideally we should remove the method and always use the feature flag.

**Comment by hmusum** [comment]
Nice, then we can control this per app in staging and this will have no impact on other apps. I'll try to remove the method and always use the flag

**Comment by hmusum** [comment]
https://github.com/vespa-engine/vespa/pull/27343 changes this to only use the feature flag

**Pull request merged**
