### PR TITLE
Node-Repo: Always lock by application ID

### PR DESCRIPTION
**Pull request by freva**
I've looked at the usage of all the locking methods that I could find in node-repo and created a graph of all paths where we take more than 1 lock concurrently:
image

Red boxes are the application locks. Green is the "unallocated" lock, i.e. the lock we take when we want to modify a node that does not have any allocation, when we are allocating or doing anything that could affect allocation (e.g. adding/removing nodes). The cyan boxes are the `lock(Node)` methods which will take either the application or the unallocated lock depending on if the given node has `Allocation` set or not. Finally, yellow is the session lock in `configserver` module, probably not relevant for this.

Gradient that goes top-down means we first take the top colored lock, then while still holding it, the bottom colored lock. Gradient that goes sideways means first take the left colored lock, then release it, then take the right colored lock.

We have already eliminated the obvious deadlocks, but they still occasionally happen. The reason for that are the cyan boxes which may take either lock depending on the node allocation state, before taking the other locks.

This PR turns all the cyan boxes red:
* All infrastructure nodes will lock by their application ID, which we know ahead of time even if the node is not yet allocated.
* Tenant nodes will continue locking by the application in their `Allocation`, but we will no longer ever remove `Allocation` from a node. Since nodes are created with an `Allocation`, that means that all tenant nodes should effectively always have it (though actually enforcing it will require rewriting many unit tests :cry: )

### CODE REVIEW

**Comment by bratseth** [comment]
Great!

"Tenant nodes will continue locking by the application in their Allocation, but we will no longer ever remove Allocation from a node. Since nodes are created with an Allocation, that means that all tenant nodes should effectively always have it (though actually enforcing it will require rewriting many unit tests 😢 )"

Yes, we are testing a lot of stuff which we never do any more. Maybe it is time to fix this, I think it will unlock other simplifications too.

**Review by bratseth — APPROVED** [review]

**Comment by freva** [comment]
Besides all the unit tests, there is also the allocation code that briefly creates `Node`s without allocation via `NodeCandidate::withNode`/`Node::reserve` (the last one is used in a few classes outside of node-repository). This one is harder to fix since it requires `Membership`, which requires index, which we cant assign before we actually decide to accept the node. So need to rewrite the allocation code to work on `NodeCandidate` or something all the way through.

**Comment by freva** [comment]
Requiring allocation for non-tenant nodes this is much harder since these nodes can be added at any time via the REST API and the proxy app also depends on application package

**Review by mpolden — APPROVED** [review]
Great!

> Since nodes are created with an Allocation, that means that all tenant nodes should effectively always have it (though actually enforcing it will require rewriting many unit tests)

We did this multiple times in controller-server after the initial rewrite. Very boring, but worth it since we can simplify a lot of code.

> Yes, we are testing a lot of stuff which we never do any more. Maybe it is time to fix this, I think it will unlock other simplifications too.

Agree! One example is that we still kind of support allocating directly on hosts. We never do this in practice, but tests do.

**Pull request merged**
