### PR TITLE
Filter also on isRunning

### PR DESCRIPTION
**Pull request by jonmv**
@bratseth please merge.

### CODE REVIEW

**Comment by jonmv** [comment]
The `upgrading()` filter doesn't check the same things. It doesn't check age of `lastTriggered`, or `isRunning(jobTimeoutLimit)`.

**Comment by bratseth** [comment]
True, but I don't think that's the problem?

And shouldn't we fix upgrading() then?

**Comment by jonmv** [comment]
I'm starting to wonder about that as well :p

**Comment by jonmv** [comment]
I think this would help. I also think the `! job.lastTriggered().get().at().isBefore(job.lastCompleted().get().at())` could get wrong in this condition, assuming jobs are triggered within the same millisecond as the completion is registered. This should be fixed as well, but it's not trivial, I seem to remember.

**Comment by jonmv** [comment]
I do remember there were lots of applications shown as running, even a day after triggering (and cancellation), and this would certainly help remove those. That all of those were aborted, however, seems unlikely. Then again, we may have had the writing-stale-data maintainers running at that time, which could have caused the job completion report to get lost ... ?

**Comment by jonmv** [comment]
Perhaps this isn't important enough to bother. 

I think there'll be a rewrite of much of the model and logic soon, in any case?

**Comment by bratseth** [comment]
>  That all of those were aborted, however, seems unlikely.

No, afaik this happens when we cancel an upgrade due to broken confidence (for the reason I mentioned). Never seen it happen otherwise.

Anyway, I believe upgrading() is slightly wrong and we should fix it, not add another filter to correct that it is wrong (the latter is the kind of change which kills the code base long term (although it reduces risk in the short term)).

**Comment by jonmv** [comment]
No risk to change `upgrading()` here, though. However, I still don't see why the jobs were shown as running, since `upgrading()` does compare time stamps of `lastTriggered` and `lastCompleted`. 

Ah ... your explanation suddenly makes sense:
We have put all these apps in the triggering queue, and the `lastTriggered` is set that that point, not on actual triggering. And then we leave them in the queue, so all of the get triggered, even though we have lost confidence in the version already. ...

I'll revisit this.

**Comment by bratseth** [comment]
Almost. We remove them from the que (when cancelling the upgrades), but we leave the triggered event in the job status data structure, so it will look as if they are running.

**Pull request closed without merging**
