### PR TITLE
henrhoi/rank-profiles-and-sources-in-configuration-file

### PR DESCRIPTION
**Pull request by henrhoi**
… Added the predetermined sources from the genreated config.json to the autocompletion of yql-syntax. Now also possible to add possible values for all parameters, just put the parameter (full name with underscore instead of dots) and a list of possible values in the config-file to be generated. Model.sources, Ranking.rankprofile, Ranking.properties, ranking.features have now possible values on value-input.

### CODE REVIEW

**Comment by henrhoi** [comment]
Missing to get rankprofiles, ranking.features, ranking.properties programatically (if they should).

**Comment by henrhoi** [comment]
Now the GUIHandler also sends all the parameter-names, instead of having it in the JS.

**Comment by henrhoi** [comment]
> Will remove import of util.*

**Comment by bratseth** [comment]
Great. Other parameters which should get this treatment: queryProfile, searchChain, model.type, model.restrict, model.defaultIndex, presentation.format, presentation.summary, collapsefield.

Some of these (the ones which needs the list of fields?) may be more effort than it is worth ...

**Pull request merged**
