### PR TITLE
Don't spam log with stack trace if application did not request GPU

### PR DESCRIPTION
**Pull request by bjorncs**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by mpolden** [comment]
I don't understand this. If the application does not have a GPU device, we don't try to load CUDA support at all: https://github.com/vespa-engine/vespa/pull/28406/files#diff-4d521eb135ccd5e000c93aea500daf7c213e06652d38b482d82f0df8fa8fcd31R143

**Comment by bjorncs** [comment]
That's not the case for the Huggingface and Bert embedders, which optimistically tries to load CUDA.

**Comment by mpolden** [comment]
How? OrtSession::addCUDA needs a GPU device number.

**Comment by bjorncs** [comment]
By using device number `0` as default.

**Comment by mpolden** [comment]
In that case I would make it:
```
if (loadCuda) {
  // log same as before as the exception is useful when you explicitly request GPU and it fails
} else {
  log.info("Ignoring optimistic attempt to load CUDA blabla")
}

**Comment by bjorncs** [comment]
Replaced by https://github.com/vespa-engine/vespa/pull/29107

**Pull request closed without merging**
