### PR TITLE
Use same heap size at start as max heap size

### PR DESCRIPTION
**Pull request by hmusum**

### CODE REVIEW

**Review by baldersheim — COMMENTED** [review]
Do you know why it was set like this. Perhaps it was to reduce memory usage for small opensource machines ?
If so and we are overriding where we use it, it might be fine.

**Comment by hmusum** [comment]
Good point, I'll need to look into when we are overriding.

**Comment by baldersheim** [comment]
@hmusum Should we just close this one ?

**Comment by hmusum** [comment]
Yes, couldn't find out why the heap sizes where different, so better leave it as is.

**Comment by baldersheim** [comment]
I am quite sure it was to enable it to run on small instances allowing testing on small public instances.

**Pull request closed without merging**
