### PR TITLE
add ContainerLatencySearcher

### PR DESCRIPTION
**Pull request by arnej27959**
@jobergum please check if this looks like what you wanted
@bratseth please review - I would like to have some more constraints in searchers to ensure that this one is really "just before clustersearcher", the best i could think of was to specify that it's "part of" the backend in the "After" annotation.

### CODE REVIEW

**Comment by jobergum** [comment]
👍 This is great!

**Comment by bratseth** [comment]
Yes, we don't have a way to do exactly that ... this should work ok though.

However, I don't think you can use Point like this. It is not multithread safe so other threads may observe an invalid Point. Also, a searcher instance can be a member of multiple chains, so you may end up using the wrong value indefinitely.

**Review by bratseth — APPROVED** [review]

**Comment by arnej27959** [comment]
the Point is immutable so that part should be OK, but if the same searcher instance is used for multiple chains it won't work anyway.

**Comment by bratseth** [comment]
Immutable but not atomic I think? Anyway, it doesn't matter, as you say.

**Pull request merged**
