### PR TITLE
Jersey cleanup 1

### PR DESCRIPTION
**Pull request by gjoranv**

### CODE REVIEW

**Review by bjorncs — APPROVED** [review]

**Comment by bjorncs** [comment]
```
Failed to execute goal on project application: Could not resolve dependencies for project com.yahoo.vespa:application:jar:7-SNAPSHOT: Could not find artifact com.yahoo.vespa.container-test-jars:jersey-resources:jar:7-SNAPSHOT
```

**Review by bjorncs — CHANGES_REQUESTED** [review]
PR build fails

**Comment by gjoranv** [comment]
ah.. forgot to clear it from the m2 cache.

**Comment by bjorncs** [comment]
```
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project clustercontroller-core: There are test failures.
```

**Comment by gjoranv** [comment]
clustercontroller-core tests fail a lot locally as well. There is an open ticket.

**Review by bjorncs — APPROVED** [review]

**Pull request merged**
