### PR TITLE
Revert "Revert "Revert "Added logserver feature flag (#8065)"" "

### PR DESCRIPTION
**Pull request by hakonhall**
Reverts vespa-engine/vespa#8101

### CODE REVIEW

**Review by freva — APPROVED** [review]

**Comment by hakonhall** [comment]
Config server fails with the unhelpful:

```
[2019-01-11 14:38:07.313] INFO    : jdisc/configserver /com.yahoo.jdisc.core.FelixFramework     OSGi bundle 'standalone-container' states that it requires privileged initialization, but privileges are not available. YMMV.
[2019-01-11 14:38:07.405] WARNING : configserver     stderr     org.osgi.framework.BundleException: Unable to resolve standalone-container [1](R 1.0): missing requirement [standalone-container [1](R 1.0)] osgi.wiring.package; (&(osgi.wiring.package=com.yahoo.config.model.builder.xml)(version>=1.0.0)(!(version>=2.0.0))) [caused by: Unable to resolve config-model [6](R 6.0): missing requirement [config-model [6](R 6.0)] osgi.wiring.package; (&(osgi.wiring.package=com.yahoo.vespa.flags)(version>=1.0.0)(!(version>=2.0.0)))] Unresolved requirements: [[standalone-container [1](R 1.0)] osgi.wiring.package; (&(osgi.wiring.package=com.yahoo.config.model.builder.xml)(version>=1.0.0)(!(version>=2.0.0)))]
[2019-01-11 14:38:07.405] WARNING : configserver     stderr             at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4149)
[2019-01-11 14:38:07.405] WARNING : configserver     stderr             at org.apache.felix.framework.Felix.startBundle(Felix.java:2119)
[2019-01-11 14:38:07.405] WARNING : configserver     stderr             at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
[2019-01-11 14:38:07.405] WARNING : configserver     stderr             at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
[2019-01-11 14:38:07.405] WARNING : configserver     stderr             at com.yahoo.jdisc.core.FelixFramework.startBundles(FelixFramework.java:100)
[2019-01-11 14:38:07.405] WARNING : configserver     stderr             at com.yahoo.jdisc.core.ApplicationLoader.init(ApplicationLoader.java:120)
[2019-01-11 14:38:07.405] WARNING : configserver     stderr             at com.yahoo.jdisc.core.StandaloneMain.run(StandaloneMain.java:42)
[2019-01-11 14:38:07.405] WARNING : configserver     stderr             at com.yahoo.jdisc.core.StandaloneMain.main(StandaloneMain.java:34)
```

**Comment by hakonhall** [comment]
FYI @olaaun

**Comment by hakonhall** [comment]
This even broke host-admin:

```
Jan 11 15:26:56 controllerhost-cd-1.vespahosted.corp.bf1.yahoo.com host-admin.sh[12384]: 1547220416.738        controllerhost-cd-1.vespahosted.corp.bf1.yahoo.com        12486/1        jdisc/node-admin        /com.yahoo.jdisc.core.FelixFramework        info        OSGi bundle 'standalone-container' states that it requires privileged initialization, but privileges are not available. YMMV.
Jan 11 15:26:56 controllerhost-cd-1.vespahosted.corp.bf1.yahoo.com host-admin.sh[12384]: debug        Unexpected: org.osgi.framework.BundleException: Unable to resolve standalone-container [1](R 1.0): missing requirement [standalone-container [1](R 1.0)] osgi.wiring.package; (&(osgi.wiring.package=com.yahoo.config.model.builder.xml)(version>=1.0.0)(!(version>=2.0.0))) [caused by: Unable to resolve config-model [6](R 6.0): missing requirement [config-model [6](R 6.0)] osgi.wiring.package; (&(osgi.wiring.package=com.yahoo.vespa.flags)(version>=1.0.0)(!(version>=2.0.0)))] Unresolved requirements: [[standalone-container [1](R 1.0)] osgi.wiring.package; (&(osgi.wiring.package=com.yahoo.config.model.builder.xml)(version>=1.0.0)(!(version>=2.0.0)))]
Jan 11 15:26:56 controllerhost-cd-1.vespahosted.corp.bf1.yahoo.com host-admin.sh[12384]: at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4149)
Jan 11 15:26:56 controllerhost-cd-1.vespahosted.corp.bf1.yahoo.com host-admin.sh[12384]: at org.apache.felix.framework.Felix.startBundle(Felix.java:2119)
Jan 11 15:26:56 controllerhost-cd-1.vespahosted.corp.bf1.yahoo.com host-admin.sh[12384]: at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
Jan 11 15:26:56 controllerhost-cd-1.vespahosted.corp.bf1.yahoo.com host-admin.sh[12384]: at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
Jan 11 15:26:56 controllerhost-cd-1.vespahosted.corp.bf1.yahoo.com host-admin.sh[12384]: at com.yahoo.jdisc.core.FelixFramework.startBundles(FelixFramework.java:100)
Jan 11 15:26:56 controllerhost-cd-1.vespahosted.corp.bf1.yahoo.com host-admin.sh[12384]: at com.yahoo.jdisc.core.ApplicationLoader.init(ApplicationLoader.java:120)
Jan 11 15:26:56 controllerhost-cd-1.vespahosted.corp.bf1.yahoo.com host-admin.sh[12384]: at com.yahoo.jdisc.core.StandaloneMain.run(StandaloneMain.java:42)
Jan 11 15:26:56 controllerhost-cd-1.vespahosted.corp.bf1.yahoo.com host-admin.sh[12384]: at com.yahoo.jdisc.core.StandaloneMain.main(StandaloneMain.java:34)
```

For clarity:

```
 org.osgi.framework.BundleException: Unable to resolve standalone-container [1](R 1.0): 
missing requirement [standalone-container [1](R 1.0)] osgi.wiring.package; 
(&(osgi.wiring.package=com.yahoo.config.model.builder.xml)(version>=1.0.0)(!(version>=2.0.0))) 

[caused by: Unable to resolve config-model [6](R 6.0): missing requirement [config-model [6](R 6.0)] osgi.wiring.package; 
(&(osgi.wiring.package=com.yahoo.vespa.flags)(version>=1.0.0)(!(version>=2.0.0)))] 

Unresolved requirements: [[standalone-container [1](R 1.0)] osgi.wiring.package; (&(osgi.wiring.package=com.yahoo.config.model.builder.xml)(version>=1.0.0)(!(version>=2.0.0)))]
```

**Comment by hakonhall** [comment]
@gjoranv we're trying to make config-model depend on flags bundle

I'm guessing we need to provide the flags bundle in another way than we currently do:
 - For config server, flags jar in lib/jars with a symlink from components directory
 - For host-admin, the flags jar in components directory

**Pull request merged**
