### PR TITLE
Disable filedistribution by default.

### PR DESCRIPTION
**Pull request by aressem**
@hmusum 

FYI, @baldersheim

### CODE REVIEW

**Review by baldersheim — APPROVED** [review]
As 2 made the same conclusion it must be right

**Comment by hmusum** [comment]
Doesn't this turn it on for all installations (hosted, standalone, open-source)? I think it will fail for the first two (due to deadlocks when using new file distribution code when having concurrent requests for files)

**Comment by aressem** [comment]
According to @arnej27959 we rewrite this file internally at install time.

**Comment by arnej27959** [comment]
i think that this file (in vespabase/conf) will only be packaged in RPMs and not in yinst packages; there's a script in factory/modules/platform/gen-default-env.pl instead.

**Pull request merged**
