### PR TITLE
Remove docker.def.

### PR DESCRIPTION
**Pull request by hakonhall**

### CODE REVIEW

**Comment by hakonhall** [comment]
Hm, on second reading at that URL, we should probably keep some read timeout, but I'm not entirely sure of a sane value. 20m?

**Review by freva — COMMENTED** [review]
Looks to me like this would just block forever without printing stack trace instead?

**Comment by hakonhall** [comment]
It wouldn't affect the AFUNIXSocketException situation, I think: That exception is not from a time out - presumably that error is received ASAP.

It's rather to allow commands ... that doesn't print out anything for more than 1s, is how I interpret it. So we just need to figure out a safe upper limit to that.

**Review by freva — APPROVED** [review]

**Comment by hakonhall** [comment]
.

**Comment by hakonhall** [comment]
Travis is green - I'm unable to make a green bullet though.

**Pull request merged**
