### PR TITLE
Log less

### PR DESCRIPTION
**Pull request by bratseth**

### CODE REVIEW

**Review by gjoranv — APPROVED** [review]
Why only the providers and resources, and not AbstractComponents?

**Comment by gjoranv** [comment]
FYI: @baldersheim I think you have been using these log messages from time to time.

**Comment by bratseth** [comment]
> Why only the providers and resources, and not AbstractComponents?

These are the ones I see way too many of but yes, I'll change that one as well.

**Review by gjoranv — APPROVED** [review]

**Comment by bratseth** [comment]
@baldersheim you ok with this?

**Comment by bratseth** [comment]
Ok

**Pull request closed without merging**
