### PR TITLE
Remove legacy protocol from logserver

### PR DESCRIPTION
**Pull request by bjorncs**
FYI @toregge @arnej27959

### CODE REVIEW

**Review by arnej27959 — CHANGES_REQUESTED** [review]
this change can't be done at this point in time.  you'll need to wait until all hosted applications are on a version that supports RPC.  Then, we must remove the code from logd that allows sending on the legacy protocal.  Then we must wait (again) until that version is live on all hosted applications.  After that, this change can be applied.

**Review by geirst — COMMENTED** [review]
The changes itself LGTM, but I agree with @arnej27959 that we should wait and do the removal in logd first.

**Comment by bjorncs** [comment]
All applications in hosted Vespa (except those on 6.330) are now using the RPC protocol. What we remove first, legacy protocol in logd or logserver, should not matter afaik.

**Comment by bjorncs** [comment]
@arnej27959 Feel free to merge if necessary.

**Pull request merged**
