### PR TITLE
Jonmv/log handler with blocking flush

### PR DESCRIPTION
**Pull request by jonmv**
@bjorncs please review and merge.

### CODE REVIEW

**Comment by jonmv** [comment]
I decided `flush()` was an appropriate place to synchronise here.

**Comment by jonmv** [comment]
Or @bratseth

**Review by bratseth — APPROVED** [review]

**Comment by baldersheim** [comment]
Is the LogHandler involved with logging in a container application ?
It sounds like it will the request threads block. If so this sounds like a very bad idea.

**Comment by jonmv** [comment]
The threads that will block are those serving logs from the logserver archive. You're afraid these are a shared resource, used for things that will now block, and cause havoc elsewhere? 

This handler is hardly ever used, so I don't think we'll notice anything now, but to be future proof, we should probably consider if this could be a problem.

**Comment by jonmv** [comment]
Conclusion: it's fine.

**Pull request merged**
