### PR TITLE
Less lecturing of user

### PR DESCRIPTION
**Pull request by kkraune**
- and yes, I got this in a GitHub Action output ;-)

### CODE REVIEW

**Review by mpolden — CHANGES_REQUESTED** [review]
> I got this in a GitHub Action output 

We should fix that instead. This warning is only shown when `CI` is unset. It shouldn't be shown at all in CI environments.

```
$ vespa status -t cloud
Warning: Authenticating with API key. This is discouraged in non-CI environments
Hint: Authenticate with 'vespa auth login' instead
Container (query API) at xxx is ready
$ env CI=true vespa status -t cloud
Container (query API) at xxx is ready
```

`CI` should always be set according to https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables, so not sure what's up with your action.

Is there a way to show all the variables set in the action?

**Comment by kkraune** [comment]
I agree we should fix the root cause, but regardless of that I do not need the "This is discouraged in non-CI environments" string :-)

I can do a run to print the environment, hang on ...

**Comment by kkraune** [comment]
I think we found the reason why CI was not set in the env.

**Comment by mpolden** [comment]
Yes. Instead of removing the explaination, how about rephrasing it? "Authenticating with API key, which is intended for use in CI environments". That way we still explain the purpose of an API key.

**Comment by kkraune** [comment]
yes, that is better!

**Review by mpolden — APPROVED** [review]

**Pull request merged**
