### PR TITLE
Deprecate DocumentTypeManager and DocumentTypeManagerConfigurer. They…

### PR DESCRIPTION
**Pull request by baldersheim**
… should not be used directly by applications.

We should make a new one with an interface that preserves the type hierachy.

@arnej27959 and @bratseth @jonmv PR

### CODE REVIEW

**Comment by arnej27959** [comment]
I agree that this shouldn't be used from users' code; but I think the Jon's will have to agree also.

**Comment by jonmv** [comment]
Shouldn't the replacement be available at the time off deprecation, though?

**Comment by baldersheim** [comment]
There will be no replacement that is public.
User are supposed to have the thing you made some sprints ago injected.

**Comment by bratseth** [comment]
Also agree, but what should they use? The @deprecation Javadoc comment should say.

**Comment by arnej27959** [comment]
I don't know what "thing you made some sprints ago" is, but in system tests I see that document processors
typically use `processing.getService().getDocumentTypeManager().getDocumentType(...)`
We should have something, possibly an interface with `getDocumentType(String name)` as the only method,
which can be used instead of DocumentTypeManager here.

**Comment by jonmv** [comment]
If they use the document manager to access document meta data, the injectable document access won't help with that. It gives them a fully configure DocumentManager, but if they're not allowed to use it, that doesn't help much. Perhaps the `getDocumentType(String name)` should be added to this, then?

**Pull request closed without merging**
