### PR TITLE
allow filter in HNSW index

### PR DESCRIPTION
**Pull request by arnej27959**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

For discussion: we can reduce some code duplication by sending the filter by pointer, optionally nullptr, and testing for that in the appropriate place - what do you think?

missing for now: unit test

@geirst @toregge please review

### CODE REVIEW

**Review by geirst — COMMENTED** [review]
Yes, I think we should try to avoid as much code duplication as possible, collapsing search_l0(),  find_top_k_with_filter() and top_k_candidates() (that takes filter) into generic ones that can optionally handle the filter. Passing the filter as a pointer to the underlying functions sounds good, and we can check whether to use it or not (nullptr indicating we are not using it). As calculation of distance is the costly part of searching, we will probably not notice these extra checks. If we observe it on profiling we can template the functions on whether to use filter or not. The new function on the index API seems good, there it makes sense to have an explicit function for using filter.

**Comment by arnej27959** [comment]
@geirst PTAL - now with unit test and reduced code duplication

**Review by geirst — APPROVED** [review]
👍 I don't see the unit test, did you forget to push it?

**Review by geirst — APPROVED** [review]
👍

**Pull request merged**
