### PR TITLE
skeleton doc, first cut

### PR DESCRIPTION
**Pull request by kkraune**
lets add stuff here, strawman doc for now, to be able to link from frontpage

@frodelu please merge

### CODE REVIEW

**Comment by bratseth** [comment]
Are you planning to write more on this right now?

**Comment by frodelu** [comment]
Didn't we agree to use the start of Screwdriver's contributing doc as template for this?

**Comment by bratseth** [comment]
Yes. That one isn't very good though.

**Comment by kkraune** [comment]
yes must write more, this is just a link target from front page for now. but I think it is better to err on the side of too little and add as we need to. and I think having the full text in the .md file makes the repo more self contained, and other big projects do this, too.

but no strong opinions, just want to get this going

**Comment by frodelu** [comment]
For inspiration: https://facebook.github.io/react/contributing/how-to-contribute.html

**Pull request merged**
