### PR TITLE
Vespa <> Gradle

### PR DESCRIPTION
**Pull request by ohad7**
### Gradle build system for all vespa modules

Compilation:
**./gradlew compileJava compileTestJava**

Build with test:
**./gradlew build** 

This gradle task will generate a test report under **./build/reports/allTests/index.html**

Tests are still work in progress, out of 10812 tests, 43 failing 

Some advantages to using gradle:
1. Modern and readable build configuration
2. Time saving - compilation and test parallelization by default (each module is compiled/tested/packaged in parallel based on the dependency graph)
3. Easier control over jarhell issues
4. Great support for IDEs - full control over the IDE project files

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by bratseth** [comment]
@gjoranv @bjorncs @aressem opinions?

**Comment by aressem** [comment]
I think it is great looking forward for modern development tools like gradle and we should welcome efforts helping us along the way. However, internally I don't see us switching to gradle in the short term, and we don't want to maintain a mix of gradle and maven ( I think). This means that we would probably not use these files in CI/CD and the will become stale. But I don't think it would hurt to merge this and it might be that developers will start experimenting with gradle and start paving the road ahead.

**Comment by kkraune** [comment]
what is next step?

**Comment by ohad7** [comment]
I think the main thing is to understand whether this is in fact worth the effort, beyond catching up with the current master version, there's a significant effort still required to make sure that c++ compilation is not broken, and if there's any other maven related workflow that I missed or was added in the interim it should be added.

**Comment by aressem** [comment]
Timed out.

**Pull request closed without merging**
