### PR TITLE
Disabled stemming for significance model generator

### PR DESCRIPTION
**Pull request by glebashnik**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

Significance model is applied to queries before stemming, thus it makes sense to disable stemming when generating significance models as well.

### CODE REVIEW

**Review by geirst — APPROVED** [review]
👍

**Review by geirst — CHANGES_REQUESTED** [review]
There seems to be failing unit tests:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.3.1:test (default-test) on project vespaclient-java: There are test failures.
--
  | [ERROR]
  | [ERROR] Please refer to /workspace/build/buildkite/vespaai/vespa-engine-vespa/vespaclient-java/target/surefire-reports for the individual test results.


```

**Comment by glebashnik** [comment]
> There seems to be failing unit tests:
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.3.1:test (default-test) on project vespaclient-java: There are test failures.
> --
>   | [ERROR]
>   | [ERROR] Please refer to /workspace/build/buildkite/vespaai/vespa-engine-vespa/vespaclient-java/target/surefire-reports for the individual test results.
> ```

Fixed tests.

**Review by geirst — APPROVED** [review]
👍

**Pull request merged**
